FLipMouse/FABI ESP32 firmware: Task Class Reference
Task Class Reference abstract
Encapsulate a runnable task.
#include <Task.h>
Public Member Functions
Task (std::string taskName="Task", uint16_t stackSize=10000, uint8_t priority=5)
Create an instance of the task class.
virtual ~Task ()
void setStackSize (uint16_t stackSize)
Set the stack size of the task.
void setPriority (uint8_t priority)
Set the priority of the task.
void setName (std::string name)
Set the name of the task.
void setCore (BaseType_t coreId)
Set the core number the task has to be executed on. If the core number is not set, tskNO_AFFINITY will be used.
void start (void *taskData=nullptr)
Start an instance of the task.
void stop ()
Stop the task.
virtual void run (void *data)=0
Body of the task to execute.
void delay (int ms)
Suspend the task for the specified milliseconds.
Detailed Description
Encapsulate a runnable task.
This class is designed to be subclassed with the method:
void run(void *data) { ... }
For example:
class CurlTestTask : public Task {
   void run(void *data) {
      // Do something
   }
};
implemented.
Definition at line 34 of file Task.h.
Constructor & Destructor Documentation
Task()
Task::Task (std::string taskName = "Task", uint16_t stackSize = 10000, uint8_t priority = 5)
Create an instance of the task class.
Parameters
[in] taskName The name of the task to create.
[in] stackSize The size of the stack.
Returns
N/A.
Definition at line 27 of file Task.cpp.
~Task()
Task::~Task () virtual
Definition at line 36 of file Task.cpp.
Member Function Documentation
delay()
void Task::delay (int ms)
Suspend the task for the specified milliseconds.
Parameters
[in] ms The delay time in milliseconds.
Returns
N/A.
Definition at line 46 of file Task.cpp.
run()
virtual void Task::run (void * data) pure virtual
Body of the task to execute.
This function must be implemented in the subclass that represents the actual task to run. When a task is started by calling start(), this is the code that is executed in the newly created task.
Parameters
[in] data The data passed in to the newly started task.
Referenced by delay().
setCore()
void Task::setCore (BaseType_t coreId)
Set the core number the task has to be executed on. If the core number is not set, tskNO_AFFINITY will be used.
Parameters
[in] coreId The id of the core.
Returns
N/A.
Definition at line 130 of file Task.cpp.
setName()
void Task::setName (std::string name)
Set the name of the task.
Parameters
[in] name The name for the task.
Returns
N/A.
Definition at line 119 of file Task.cpp.
setPriority()
void Task::setPriority (uint8_t priority)
Set the priority of the task.
Parameters
[in] priority The priority for the task.
Returns
N/A.
Definition at line 109 of file Task.cpp.
setStackSize()
void Task::setStackSize (uint16_t stackSize)
Set the stack size of the task.
Parameters
[in] stackSize The size of the stack for the task.
Returns
N/A.
Definition at line 99 of file Task.cpp.
Referenced by halBLEInit().
start()
void Task::start (void * taskData = nullptr)
Start an instance of the task.
Parameters
[in] taskData Data to be passed into the task.
Returns
N/A.
Definition at line 70 of file Task.cpp.
Referenced by halBLEInit().
stop()
void Task::stop ()
Stop the task.
Returns
N/A.
Definition at line 84 of file Task.cpp.
Referenced by delay().
The documentation for this class was generated from the following files:
/home/beni/sync/Projects/FH/FLipMouse-esp32/main/ble_hid/Task.h
/home/beni/sync/Projects/FH/FLipMouse-esp32/main/ble_hid/Task.cpp