FLipMouse/FABI ESP32 firmware: /home/beni/sync/Projects/FH/FLipMouse-esp32/main/config_switcher.c File Reference
config_switcher.c File Reference
CONTINOUS TASK + FUNCTIONAL TASK - This module takes care of configuration loading.
#include "config_switcher.h"
Macros
#define LOG_TAG "cfgsw"
#define CONFIGSWITCHERTASK_PERMANENT_STACKSIZE 4096
Functions
generalConfig_t * configGetCurrent (void)
Get the current config struct.
esp_err_t task_configswitcher_getAT (char *output, void *cfg)
Reverse Parsing - get AT command for configswitcher VB.
esp_err_t configUpdate (void)
Trigger a config update.
esp_err_t configUpdateVB (void *param, command_type_t type, uint8_t vb)
Update one virtual button.
void configSwitcherTask (void *params)
CONTINOUS TASK - Config switcher task, internal config reloading.
void task_configswitcher (taskConfigSwitcherConfig_t *param)
FUNCTIONAL TASK - Load another slot.
esp_err_t configSwitcherInit (void)
Initializing the config switching functionality.
Variables
TaskHandle_t currentTasks [NUMBER_VIRTUALBUTTONS *4]
Array containing all currently running FUNCTIONAL task handles.
void * currentTaskParameters [NUMBER_VIRTUALBUTTONS *4]
Array of pointers to FUNCTIONAL task parameters.
void * currentTaskParametersUpdate [NUMBER_VIRTUALBUTTONS *4]
Array of pointers to FUNCTIONAL task parameters (for updating current config)
TaskHandle_t configswitcher_handle
generalConfig_t currentConfigLoaded
Detailed Description
CONTINOUS TASK + FUNCTIONAL TASK - This module takes care of configuration loading.
The config_switcher module is used to control all tasks assigned to virtual buttons (called FUNCTIONAL TASKS). If a new configuration should be loaded from the storage, all previously loaded tasks are deleted and new tasks are loaded.
A slot configuration is provided by the config_storage, which is controlled by this module.
task_configswitcher is the FUNCTIONAL TASK for triggering a slot switch. configSwitcherTask is the CONTINOUS TASK which monitors the queue for any config switching action.
Note
If you want to add a new FUNCTIONAL TASK, please include headers here & add loading functionality to configSwitcherTask.
Definition in file config_switcher.c.
Macro Definition Documentation
CONFIGSWITCHERTASK_PERMANENT_STACKSIZE
#define CONFIGSWITCHERTASK_PERMANENT_STACKSIZE 4096
Stacksize for continous task configSwitcherTask.
See also
configSwitcherTask
Definition at line 47 of file config_switcher.c.
Referenced by configSwitcherInit().
LOG_TAG
#define LOG_TAG "cfgsw"
Tag for ESP_LOG logging
Definition at line 43 of file config_switcher.c.
Referenced by configSwitcherInit(), configSwitcherTask(), configUpdate(), configUpdateVB(), and task_configswitcher().
Function Documentation
configGetCurrent()
generalConfig_t* configGetCurrent (void)
Get the current config struct.
This method is used to get a reference to the current config struct. The caller can use this reference to change the configuration and update the config afterwards (via the config_switcher queue).
See also
config_switcher
currentConfigLoaded
Returns
Pointer to the current config struct
Definition at line 98 of file config_switcher.c.
Referenced by debouncerCallback(), doGeneralCmdParsing(), doInfraredParsing(), doKeyboardParsing(), doMouthpieceSettingsParsing(), doStorageParsing(), halAdcProcessPressure(), halBLEInit(), halBleTaskKeyboardPress(), halBleTaskKeyboardRelease(), halIOBuzzerTask(), halIOInit(), halIOLEDTask(), infrared_set_edge_timeout(), mouse_get_wheel(), mouse_set_wheel(), printAllSlots(), and task_debouncer().
configSwitcherInit()
esp_err_t configSwitcherInit (void)
Initializing the config switching functionality.
The CONTINOUS task will be loaded to enable slot switches via the task_configswitcher FUNCTIONAL task.
Returns
ESP_OK if everything is fined, ESP_FAIL otherwise
Definition at line 517 of file config_switcher.c.
Referenced by app_main().
configSwitcherTask()
void configSwitcherTask (void * params)
CONTINOUS TASK - Config switcher task, internal config reloading.
This task is used to change the full configuration of this device After sending a request to the config_switcher queue, this task is used to unload all virtual buttons tasks and initializing the virtualbutton tasks with the new functionality.
See also
config_switcher
Parameters
params Not used, pass NULL.
Warning
On a factory reset, it is necessary to load the default slot again!
Todo:
Add __RESTOREFACTORY...
Definition at line 198 of file config_switcher.c.
Referenced by configSwitcherInit().
configUpdate()
esp_err_t configUpdate (void)
Trigger a config update.
This method is simply sending an "__UPDATE" command to the config_switcher queue to trigger an update by re-loading the currentConfig.
See also
config_switcher
currentConfig
Returns
ESP_OK on success, ESP_FAIL otherwise
Definition at line 131 of file config_switcher.c.
Referenced by configUpdateVB(), and task_commands().
configUpdateVB()
esp_err_t configUpdateVB (void * param, command_type_t type, uint8_t vb)
Update one virtual button.
This function is used to update one virtual button config. For example it is triggered by "AT BM xx" and the following AT command. It saves the param pointer to the update param array and calls configUpdate to trigger the reload.
See also
configUpdate
currentTaskParametersUpdate
Parameters
param FUNCTIONAL task parameter memory
type Type of new VB command
vb Number of virtualbutton to update
Returns
ESP_OK on success, ESP_FAIL otherwise
Definition at line 163 of file config_switcher.c.
Referenced by task_commands().
task_configswitcher()
void task_configswitcher (taskConfigSwitcherConfig_t * param)
FUNCTIONAL TASK - Load another slot.
This task is used to switch the configuration to another slot. It is possible to load a slot by name or a previous/next/default slot.
Parameters
param Task configuration
See also
taskConfigSwitcherConfig_t
Definition at line 451 of file config_switcher.c.
Referenced by configSwitcherTask(), and doStorageParsing().
task_configswitcher_getAT()
esp_err_t task_configswitcher_getAT (char * output, void * cfg)
Reverse Parsing - get AT command for configswitcher VB.
This function parses the current configuration of a virtual button to an AT command used to print the configuration.
Parameters
output Output string, where the full AT command will be stored
cfg Pointer to current cfgswitcher configuration, used to parse.
Returns
ESP_OK if everything went fine, ESP_FAIL otherwise
Definition at line 111 of file config_switcher.c.
Referenced by printAllSlots().
Variable Documentation
configswitcher_handle
TaskHandle_t configswitcher_handle
Task handle for the CONTINOUS task responsible for config switching
Definition at line 83 of file config_switcher.c.
Referenced by configSwitcherInit().
currentConfigLoaded
generalConfig_t currentConfigLoaded
Currently loaded configuration.
Definition at line 86 of file config_switcher.c.
Referenced by configGetCurrent().
currentTaskParameters
void* currentTaskParameters[NUMBER_VIRTUALBUTTONS *4]
Array of pointers to FUNCTIONAL task parameters.
This array contains pointers to memory, which is allocated here. Each time a task switch is triggered, the parameters are loaded from hal_storage and saved to an allocated memory area. These pointers are used to pass the parameters to the functional tasks and free this memory after unloading/deleting functional tasks.
Definition at line 63 of file config_switcher.c.
Referenced by configSwitcherInit(), and configSwitcherTask().
currentTaskParametersUpdate
void* currentTaskParametersUpdate[NUMBER_VIRTUALBUTTONS *4]
Array of pointers to FUNCTIONAL task parameters (for updating current config)
This array contains pointers to memory, which is allocated externally. Pointers here have the same function as in currentTaskParameters, except they are used ONLY during config UPDATE.
If an external module wants to update a virtual button config without loading a full slot, following steps are necessary:<br<
Allocate memory for the FUNCTIONAL task parameters
Save this pointer to this array here & fill parameter with data
Set currentConfigLoaded.virtualButtonCommand[vb] accordingly
Request slot update via config_switcher queue
Todo:
Maybe this information should be moved to the corresponding function.
Definition at line 80 of file config_switcher.c.
Referenced by configSwitcherInit(), configSwitcherTask(), and configUpdateVB().
currentTasks
TaskHandle_t currentTasks[NUMBER_VIRTUALBUTTONS *4]
Array containing all currently running FUNCTIONAL task handles.
This array contains task handles, one for each virtual button. NULL if there is no task loaded, the task handle otherwise. Is used to delete running tasks on a config switch
Definition at line 54 of file config_switcher.c.
Referenced by configSwitcherTask().