FLipMouse/FABI ESP32 firmware: /home/beni/sync/Projects/FH/FLipMouse-esp32/main/config_switcher.h File Reference
config_switcher.h File Reference
CONTINOUS TASK + FUNCTIONAL TASK - This module takes care of configuration loading.
#include "esp_log.h"
#include "common.h"
#include "tones.h"
#include "hal_adc.h"
#include "hal_storage.h"
#include "hal_io.h"
#include "hal_ble.h"
#include "hal_serial.h"
#include "task_kbd.h"
#include "task_mouse.h"
#include "task_debouncer.h"
#include "task_infrared.h"
#include "task_macros.h"
#include "task_joystick.h"
Data Structures
struct taskConfigSwitcherConfig
Parameter for functional task task_configswitcher.
Macros
#define TASK_CONFIGSWITCHER_STACKSIZE 2048
Typedefs
typedef struct taskConfigSwitcherConfig taskConfigSwitcherConfig_t
Parameter for functional task task_configswitcher.
Functions
void configPrintHighWaterMark (void)
Print current task stack high water marks.
void task_configswitcher (taskConfigSwitcherConfig_t *param)
FUNCTIONAL TASK - Load another slot.
esp_err_t configSwitcherInit (void)
Initializing the config switching functionality.
generalConfig_t * configGetCurrent (void)
Get the current config struct.
esp_err_t configUpdateVB (void *param, command_type_t type, uint8_t vb)
Update one virtual button.
esp_err_t task_configswitcher_getAT (char *output, void *cfg)
Reverse Parsing - get AT command for configswitcher VB.
esp_err_t configUpdate (void)
Request config update.
esp_err_t configUpdateWaitStable (void)
Wait until current configuration is stable.
Detailed Description
CONTINOUS TASK + FUNCTIONAL TASK - This module takes care of configuration loading.
The config_switcher module is used to control all tasks assigned to virtual buttons (called FUNCTIONAL TASKS). If a new configuration should be loaded from the storage, all previously loaded tasks are deleted and new tasks are loaded.
A slot configuration is provided by the config_storage, which is controlled by this module.
task_configswitcher is the FUNCTIONAL TASK for triggering a slot switch. configSwitcherTask is the CONTINOUS TASK which monitors the queue for any config switching action.
Note
If you want to add a new FUNCTIONAL TASK, please include headers here & add loading functionality to configSwitcherTask.
Definition in file config_switcher.h.
Macro Definition Documentation
TASK_CONFIGSWITCHER_STACKSIZE
#define TASK_CONFIGSWITCHER_STACKSIZE 2048
Stacksize for functional task task_configswitcher.
See also
task_configswitcher
Definition at line 68 of file config_switcher.h.
Referenced by configSwitcherTask().
Typedef Documentation
taskConfigSwitcherConfig_t
typedef struct taskConfigSwitcherConfig taskConfigSwitcherConfig_t
Parameter for functional task task_configswitcher.
See also
task_configswitcher
config_switcher
Function Documentation
configGetCurrent()
generalConfig_t* configGetCurrent (void)
Get the current config struct.
This method is used to get a reference to the current config struct. The caller can use this reference to change the configuration and update the config afterwards (via the config_switcher queue).
See also
config_switcher
currentConfig
Returns
Pointer to the current config struct
This method is used to get a reference to the current config struct. The caller can use this reference to change the configuration and update the config afterwards (via the config_switcher queue).
See also
config_switcher
currentConfigLoaded
Returns
Pointer to the current config struct
Definition at line 111 of file config_switcher.c.
Referenced by debouncerCallback(), doGeneralCmdParsing(), doInfraredParsing(), doKeyboardParsing(), doMouthpieceSettingsParsing(), doStorageParsing(), halAdcProcessPressure(), halIOBuzzerTask(), halIOInit(), halIOLEDTask(), infrared_set_edge_timeout(), mouse_get_wheel(), mouse_set_wheel(), printAllSlots(), and task_debouncer().
configPrintHighWaterMark()
void configPrintHighWaterMark (void)
Print current task stack high water marks.
Definition at line 117 of file config_switcher.c.
Referenced by halSerialReceiveUSBSerial().
configSwitcherInit()
esp_err_t configSwitcherInit (void)
Initializing the config switching functionality.
The CONTINOUS task will be loaded to enable slot switches via the task_configswitcher FUNCTIONAL task.
Returns
ESP_OK if everything is fined, ESP_FAIL otherwise
Definition at line 612 of file config_switcher.c.
Referenced by app_main().
configUpdate()
esp_err_t configUpdate (void)
Request config update.
This method is requesting a config update for the general config. It is used either by the command parser to activate a changed config (by AT commands) or by the config switcher task, to activate a config loaded from flash.
See also
config_switcher
currentConfig
Returns
ESP_OK on success, ESP_FAIL otherwise
Definition at line 215 of file config_switcher.c.
Referenced by configSwitcherTask(), doStorageParsing(), and task_commands().
configUpdateVB()
esp_err_t configUpdateVB (void * param, command_type_t type, uint8_t vb)
Update one virtual button.
This function is used to update one virtual button config. For example it is triggered by "AT BM xx" and the following AT command. It saves the param pointer to the update param array and calls configUpdate to trigger the reload.
See also
configUpdate
currentTaskParametersUpdate
Parameters
param FUNCTIONAL task parameter memory
type Type of new VB command
vb Number of virtualbutton to update
Returns
ESP_OK on success, ESP_FAIL otherwise
Definition at line 251 of file config_switcher.c.
Referenced by task_commands().
configUpdateWaitStable()
esp_err_t configUpdateWaitStable (void)
Wait until current configuration is stable.
If the function configUpdateVB is called, a temporary task parameter buffer is used. The full configuration is loaded if configUpdatePending semaphore is free. If the configuration is to be saved, this semaphore should be checked via this method.
Note
This method blocks on the semaphore.
Returns
ESP_OK if config is stable, ESP_FAIL if timeout happened
Definition at line 186 of file config_switcher.c.
Referenced by doStorageParsing().
task_configswitcher()
void task_configswitcher (taskConfigSwitcherConfig_t * param)
FUNCTIONAL TASK - Load another slot.
This task is used to switch the configuration to another slot. It is possible to load a slot by name or a previous/next/default slot.
Parameters
param Task configuration
See also
taskConfigSwitcherConfig_t
Definition at line 545 of file config_switcher.c.
Referenced by configSwitcherTask(), and doStorageParsing().
task_configswitcher_getAT()
esp_err_t task_configswitcher_getAT (char * output, void * cfg)
Reverse Parsing - get AT command for configswitcher VB.
This function parses the current configuration of a virtual button to an AT command used to print the configuration.
Parameters
output Output string, where the full AT command will be stored
cfg Pointer to current cfgswitcher configuration, used to parse.
Returns
ESP_OK if everything went fine, ESP_FAIL otherwise
Definition at line 136 of file config_switcher.c.
Referenced by printAllSlots().