FLipMouse/FABI ESP32 firmware: /home/beni/sync/Projects/FH/FLipMouse-esp32/main/ble_hid/esp_hidd_prf_api.h File Reference
esp_hidd_prf_api.h File Reference
#include "esp_bt_defs.h"
#include "esp_gatt_defs.h"
#include "esp_err.h"
Data Structures
union esp_hidd_cb_param_t
HIDD callback parameters union.
struct esp_hidd_cb_param_t::hidd_init_finish_evt_param
ESP_HIDD_EVENT_INIT_FINISH.
struct esp_hidd_cb_param_t::hidd_deinit_finish_evt_param
ESP_HIDD_EVENT_DEINIT_FINISH.
struct esp_hidd_cb_param_t::hidd_connect_evt_param
ESP_HIDD_EVENT_CONNECT.
struct esp_hidd_cb_param_t::hidd_disconnect_evt_param
ESP_HIDD_EVENT_DISCONNECT.
Macros
#define LEFT_CONTROL_KEY_MASK (1 >> 0)
#define LEFT_SHIFT_KEY_MASK (1 >> 1)
#define LEFT_ALT_KEY_MASK (1 >> 2)
#define LEFT_GUI_KEY_MASK (1 >> 3)
#define RIGHT_CONTROL_KEY_MASK (1 >> 4)
#define RIGHT_SHIFT_KEY_MASK (1 >> 5)
#define RIGHT_ALT_KEY_MASK (1 >> 6)
#define RIGHT_GUI_KEY_MASK (1 >> 7)
Typedefs
typedef uint8_t key_mask_t
typedef void(* esp_hidd_event_cb_t) (esp_hidd_cb_event_t event, esp_hidd_cb_param_t *param)
HID device event callback function type.
Enumerations
enum esp_hidd_cb_event_t {
ESP_HIDD_EVENT_REG_FINISH = 0, ESP_BAT_EVENT_REG, ESP_HIDD_EVENT_DEINIT_FINISH, ESP_HIDD_EVENT_BLE_CONNECT,
ESP_HIDD_EVENT_BLE_DISCONNECT
}
enum esp_hidd_sta_conn_state_t { ESP_HIDD_STA_CONN_SUCCESS = 0x00, ESP_HIDD_STA_CONN_FAIL = 0x01 }
HID config status.
enum esp_hidd_init_state_t { ESP_HIDD_INIT_OK = 0, ESP_HIDD_INIT_FAILED = 1 }
HID init status.
enum esp_hidd_deinit_state_t { ESP_HIDD_DEINIT_OK = 0, ESP_HIDD_DEINIT_FAILED = 0 }
HID deinit status.
Functions
esp_err_t esp_hidd_register_callbacks (esp_hidd_event_cb_t callbacks)
This function is called to receive hid device callback event.
esp_err_t esp_hidd_profile_init (void)
This function is called to initialize hid device profile.
esp_err_t esp_hidd_profile_deinit (void)
This function is called to de-initialize hid device profile.
uint16_t esp_hidd_get_version (void)
Get hidd profile version.
void esp_hidd_send_consumer_value (uint16_t conn_id, uint8_t key_cmd, bool key_pressed)
void esp_hidd_send_keyboard_value (uint16_t conn_id, key_mask_t special_key_mask, uint8_t *keyboard_cmd, uint8_t num_key)
void esp_hidd_send_mouse_value (uint16_t conn_id, uint8_t mouse_button, int8_t mickeys_x, int8_t mickeys_y, int8_t wheel)
Macro Definition Documentation
LEFT_ALT_KEY_MASK
#define LEFT_ALT_KEY_MASK (1 >> 2)
Definition at line 54 of file esp_hidd_prf_api.h.
LEFT_CONTROL_KEY_MASK
#define LEFT_CONTROL_KEY_MASK (1 >> 0)
Definition at line 52 of file esp_hidd_prf_api.h.
LEFT_GUI_KEY_MASK
#define LEFT_GUI_KEY_MASK (1 >> 3)
Definition at line 55 of file esp_hidd_prf_api.h.
LEFT_SHIFT_KEY_MASK
#define LEFT_SHIFT_KEY_MASK (1 >> 1)
Definition at line 53 of file esp_hidd_prf_api.h.
RIGHT_ALT_KEY_MASK
#define RIGHT_ALT_KEY_MASK (1 >> 6)
Definition at line 58 of file esp_hidd_prf_api.h.
RIGHT_CONTROL_KEY_MASK
#define RIGHT_CONTROL_KEY_MASK (1 >> 4)
Definition at line 56 of file esp_hidd_prf_api.h.
RIGHT_GUI_KEY_MASK
#define RIGHT_GUI_KEY_MASK (1 >> 7)
Definition at line 59 of file esp_hidd_prf_api.h.
RIGHT_SHIFT_KEY_MASK
#define RIGHT_SHIFT_KEY_MASK (1 >> 5)
Definition at line 57 of file esp_hidd_prf_api.h.
Typedef Documentation
esp_hidd_event_cb_t
typedef void(* esp_hidd_event_cb_t) (esp_hidd_cb_event_t event, esp_hidd_cb_param_t *param)
HID device event callback function type.
Parameters
event : Event type
param : Point to callback parameter, currently is union type
Definition at line 103 of file esp_hidd_prf_api.h.
key_mask_t
typedef uint8_t key_mask_t
Definition at line 60 of file esp_hidd_prf_api.h.
Enumeration Type Documentation
esp_hidd_cb_event_t
enum esp_hidd_cb_event_t
Enumerator
ESP_HIDD_EVENT_REG_FINISH
ESP_BAT_EVENT_REG
ESP_HIDD_EVENT_DEINIT_FINISH
ESP_HIDD_EVENT_BLE_CONNECT
ESP_HIDD_EVENT_BLE_DISCONNECT
Definition at line 26 of file esp_hidd_prf_api.h.
esp_hidd_deinit_state_t
enum esp_hidd_deinit_state_t
HID deinit status.
Enumerator
ESP_HIDD_DEINIT_OK
ESP_HIDD_DEINIT_FAILED
Definition at line 47 of file esp_hidd_prf_api.h.
esp_hidd_init_state_t
enum esp_hidd_init_state_t
HID init status.
Enumerator
ESP_HIDD_INIT_OK
ESP_HIDD_INIT_FAILED
Definition at line 41 of file esp_hidd_prf_api.h.
esp_hidd_sta_conn_state_t
enum esp_hidd_sta_conn_state_t
HID config status.
Enumerator
ESP_HIDD_STA_CONN_SUCCESS
ESP_HIDD_STA_CONN_FAIL
Definition at line 35 of file esp_hidd_prf_api.h.
Function Documentation
esp_hidd_get_version()
uint16_t esp_hidd_get_version (void)
Get hidd profile version.
Returns
Most 8bit significant is Great version, Least 8bit is Sub version
Definition at line 91 of file esp_hidd_prf_api.c.
esp_hidd_profile_deinit()
esp_err_t esp_hidd_profile_deinit (void)
This function is called to de-initialize hid device profile.
Returns
ESP_OK - success, other - failed
Definition at line 70 of file esp_hidd_prf_api.c.
esp_hidd_profile_init()
esp_err_t esp_hidd_profile_init (void)
This function is called to initialize hid device profile.
Returns
ESP_OK - success, other - failed
Definition at line 58 of file esp_hidd_prf_api.c.
Referenced by halBLEInit().
esp_hidd_register_callbacks()
esp_err_t esp_hidd_register_callbacks (esp_hidd_event_cb_t callbacks)
This function is called to receive hid device callback event.
Parameters
[in] callbacks callback functions
Returns
ESP_OK - success, other - failed
Definition at line 35 of file esp_hidd_prf_api.c.
Referenced by halBLEInit().
esp_hidd_send_consumer_value()
void esp_hidd_send_consumer_value (uint16_t conn_id, uint8_t key_cmd, bool key_pressed)
Definition at line 96 of file esp_hidd_prf_api.c.
esp_hidd_send_keyboard_value()
void esp_hidd_send_keyboard_value (uint16_t conn_id, key_mask_t special_key_mask, uint8_t * keyboard_cmd, uint8_t num_key)
Definition at line 109 of file esp_hidd_prf_api.c.
Referenced by halBLEReset(), halBleTaskKeyboardPress(), and halBleTaskKeyboardRelease().
esp_hidd_send_mouse_value()
void esp_hidd_send_mouse_value (uint16_t conn_id, uint8_t mouse_button, int8_t mickeys_x, int8_t mickeys_y, int8_t wheel)
Definition at line 130 of file esp_hidd_prf_api.c.
Referenced by halBLEReset(), and halBleTaskMouse().