FLipMouse/FABI ESP32 firmware: /home/beni/sync/Projects/FH/FLipMouse-esp32/main/function_tasks/fct_infrared.c File Reference
fct_infrared.c File Reference
FUNCTION - Infrared remotes.
#include "fct_infrared.h"
Macros
#define LOG_TAG "fct_IR"
Logging tag for this module.
Functions
void fct_infrared_send (char *cmdName)
FUNCTION - Infrared command sending.
esp_err_t fct_infrared_record (char *cmdName, uint8_t outputtoserial)
FUNCTION - Trigger an IR command recording.
esp_err_t fct_infrared_set_edge_timeout (uint8_t timeout)
FUNCTION - Set the time between two IR edges which will trigger the timeout (end of received command)
Detailed Description
FUNCTION - Infrared remotes.
This module is used for recording & sending of infrared commands. Pinning and low-level interfacing for infrared is done in hal_io.c, this part here manages loading & storing the commands.
See also
hal_io.c
Definition in file fct_infrared.c.
Macro Definition Documentation
LOG_TAG
#define LOG_TAG "fct_IR"
Logging tag for this module.
Definition at line 34 of file fct_infrared.c.
Referenced by fct_infrared_record(), and fct_infrared_send().
Function Documentation
fct_infrared_record()
esp_err_t fct_infrared_record (char * cmdName, uint8_t outputtoserial)
FUNCTION - Trigger an IR command recording.
This method is used to record one infrared command. It will block until either the timeout is reached or a command is received. The command is stored vial hal_storage.
See also
halStorageStoreIR
TASK_HAL_IR_RECV_TIMEOUT
Parameters
cmdName Name of command which will be used to store.
outputtoserial If set to !=0, the hex stream will be sent to the serial interface.
Returns
ESP_OK if command was stored, ESP_FAIL otherwise (timeout)
Definition at line 90 of file fct_infrared.c.
Referenced by cmdIr().
fct_infrared_send()
void fct_infrared_send (char * cmdName)
FUNCTION - Infrared command sending.
This task is used to trigger an IR command on a VB action. The IR command which should be sent is identified by a name.
See also
taskInfraredConfig_t
Parameters
param Task config
See also
VB_SINGLESHOT
Definition at line 46 of file fct_infrared.c.
Referenced by cmdIp(), and handler_vb().
fct_infrared_set_edge_timeout()
esp_err_t fct_infrared_set_edge_timeout (uint8_t timeout)
FUNCTION - Set the time between two IR edges which will trigger the timeout (end of received command)
This method is used to set the timeout between two edges which is used to trigger the timeout, therefore the finished signal for an IR command recording.
See also
infrared_record
Warning
Normal NEC codes use a ~18ms start signal, so it is recommended to this value at least to 20!
See also
generalConfig_t
Parameters
timeout Timeout in [ms], 2-100
Returns
ESP_OK if parameter is set, ESP_FAIL otherwise (out of range)
Definition at line 207 of file fct_infrared.c.