FLipMouse/FABI ESP32 firmware: /home/beni/sync/Projects/FH/FLipMouse-esp32/main/ble_hid/GeneralUtils.cpp File Reference
GeneralUtils.cpp File Reference
#include "GeneralUtils.h"
#include <esp_log.h>
#include <esp_system.h>
#include <string.h>
#include <stdio.h>
#include <string>
#include <sstream>
#include <iomanip>
#include <FreeRTOS.h>
#include <esp_err.h>
#include <nvs.h>
#include <esp_wifi.h>
#include <esp_heap_caps.h>
Functions
static int base64EncodedLength (size_t length)
static int base64EncodedLength (const std::string &in)
static void a3_to_a4 (unsigned char *a4, unsigned char *a3)
static void a4_to_a3 (unsigned char *a3, unsigned char *a4)
static int DecodedLength (const std::string &in)
static unsigned char b64_lookup (unsigned char c)
Variables
static const char * LOG_TAG = "GeneralUtils"
static const char kBase64Alphabet []
Function Documentation
a3_to_a4()
static void a3_to_a4 (unsigned char * a4, unsigned char * a3) static
Definition at line 39 of file GeneralUtils.cpp.
Referenced by GeneralUtils::base64Encode().
a4_to_a3()
static void a4_to_a3 (unsigned char * a3, unsigned char * a4) static
Definition at line 47 of file GeneralUtils.cpp.
Referenced by GeneralUtils::base64Decode().
b64_lookup()
static unsigned char b64_lookup (unsigned char c) static
Definition at line 148 of file GeneralUtils.cpp.
Referenced by GeneralUtils::base64Decode().
base64EncodedLength() [1/2]
static int base64EncodedLength (size_t length) static
Definition at line 29 of file GeneralUtils.cpp.
Referenced by GeneralUtils::base64Encode(), and base64EncodedLength().
base64EncodedLength() [2/2]
static int base64EncodedLength (const std::string & in) static
Definition at line 34 of file GeneralUtils.cpp.
DecodedLength()
static int DecodedLength (const std::string & in) static
Definition at line 137 of file GeneralUtils.cpp.
Referenced by GeneralUtils::base64Decode().
Variable Documentation
kBase64Alphabet
const char kBase64Alphabet[] static
Initial value:
= "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    "abcdefghijklmnopqrstuvwxyz"
    "0123456789+/"
Definition at line 25 of file GeneralUtils.cpp.
Referenced by GeneralUtils::base64Encode().
LOG_TAG
const char* LOG_TAG = "GeneralUtils" static
Definition at line 23 of file GeneralUtils.cpp.
Referenced by GeneralUtils::dumpInfo(), and GeneralUtils::hexDump().