FLipMouse/FABI ESP32 firmware: /home/beni/sync/Projects/FH/FLipMouse-esp32/main/hal/hal_adc.c File Reference
hal_adc.c File Reference
HAL TASK + FUNCTIONAL TASK - This module contains the hardware abstraction as well as the calculations of the ADC.
#include "hal_adc.h"
Data Structures
struct adcData
Macros
#define LOG_TAG "hal_adc"
Tag for ESP_LOG logging.
#define LOG_LEVEL_ADC ESP_LOG_INFO
ADC log level.
#define HAL_ADC_RAW_DIVIDER 16
Define how much ADC readings are skipped until one is printed.
#define REPORT_RAW_COUNT 8
Typedefs
typedef enum strong_action strong_action_t
Current strong sip&puff + mouthpiece mode.
typedef struct adcData adcData_t
Enumerations
enum strong_action { STRONG_NORMAL, STRONG_PUFF, STRONG_SIP }
Current strong sip&puff + mouthpiece mode.
Functions
uint32_t validate (uint32_t value, uint32_t min, uint32_t max, uint32_t defaultValue)
Validate the input value and replace with default if not matching.
void halAdcProcessStrongMode (adcData_t *D)
Trigger strong sip/puff + action according to input data.
void halAdcReportRaw (uint32_t up, uint32_t down, uint32_t left, uint32_t right, uint32_t pressure, int32_t x, int32_t y)
Report raw values via serial interface.
void halAdcProcessPressure (adcData_t *D)
Process pressure sensor (sip & puff)
void halAdcCalibrate (void)
Calibration function.
void halAdcTaskThreshold (void *pvParameters)
HAL TASK - Threshold task for ADC.
esp_err_t halAdcUpdateConfig (adc_config_t *params)
Reload ADC config.
void halAdcStrongDelay (TimerHandle_t xTimer)
void halAdcStrongTimeout (TimerHandle_t xTimer)
esp_err_t halAdcInit (adc_config_t *params)
Init the ADC driver module.
Variables
TaskHandle_t adcHandle = NULL
adc_config_t adc_conf
TickType_t adcCalibLast = 0
Last calibrate tick time.
SemaphoreHandle_t adcSem = NULL
Semaphore for ADC readings.
esp_adc_cal_characteristics_t characteristics
static int32_t offsetx
static int32_t offsety
TimerHandle_t adcStrongTimeoutTimerHandle
Timer for strong mode timeout This timer is used for a timeout moving back to STRONG_NORMAL if we entered a STRONG_PUFF or STRONG_SIP mode and no action was triggered.
TimerHandle_t adcStrongTimerHandle
Timer for strong mode delay This timer is used for waiting before checking for the additional action (up,down,left,right)
SemaphoreHandle_t adcStrongSem
Semaphore, to signal a short delay for checking strong mode.
Detailed Description
HAL TASK + FUNCTIONAL TASK - This module contains the hardware abstraction as well as the calculations of the ADC.
The hal_adc files are used to measure all ADC inputs (4 direction sensors and 1 pressure sensor). In addition, depending on the configuration, different ADC tasks are loaded. One of these tasks is loaded:
halAdcMouse - Use the ADC values as mouse input
halAdcThreshold - Use the ADC values to trigger virtual buttons (keyboard actions for example)
halAdcJoystick - Use the ADC input to control the HID joystick
These tasks are HAL tasks, which means they might be reloaded/changed, but they are not managed outside this module.
In addition, the FUNCTIONAL task task_calibration can be used to trigger a zero-point calibration of the mouthpiece.
See also
adc_config_t
Todo:
Add CIM reporting (if we implement it at all)
Definition in file hal_adc.c.
Macro Definition Documentation
HAL_ADC_RAW_DIVIDER
#define HAL_ADC_RAW_DIVIDER 16
Define how much ADC readings are skipped until one is printed.
Definition at line 52 of file hal_adc.c.
Referenced by halAdcProcessPressure(), and halAdcReportRaw().
LOG_LEVEL_ADC
#define LOG_LEVEL_ADC ESP_LOG_INFO
ADC log level.
Definition at line 49 of file hal_adc.c.
Referenced by halAdcInit().
LOG_TAG
#define LOG_TAG "hal_adc"
Tag for ESP_LOG logging.
Definition at line 46 of file hal_adc.c.
Referenced by halAdcCalibrate(), halAdcInit(), halAdcProcessPressure(), halAdcProcessStrongMode(), halAdcReportRaw(), halAdcStrongTimeout(), halAdcTaskThreshold(), and halAdcUpdateConfig().
REPORT_RAW_COUNT
#define REPORT_RAW_COUNT 8
Referenced by halAdcReportRaw().
Typedef Documentation
adcData_t
typedef struct adcData adcData_t
strong_action_t
typedef enum strong_action strong_action_t
Current strong sip&puff + mouthpiece mode.
It is possible to add another 8 virtual buttons by triggering a strong sip or puff and move the mouthpiece in one of four directions.
Note
If the VB for strong sip/puff is assigned (!= "no command"), it is not possible to use strong sip/puff + up/down/left/right!
Enumeration Type Documentation
strong_action
enum strong_action
Current strong sip&puff + mouthpiece mode.
It is possible to add another 8 virtual buttons by triggering a strong sip or puff and move the mouthpiece in one of four directions.
Note
If the VB for strong sip/puff is assigned (!= "no command"), it is not possible to use strong sip/puff + up/down/left/right!
Enumerator
STRONG_NORMAL
STRONG_PUFF
STRONG_SIP
Definition at line 62 of file hal_adc.c.
Function Documentation
halAdcCalibrate()
void halAdcCalibrate (void)
Calibration function.
This method is called to calibrate the offset value for x and y axis of the mouthpiece. Either triggered by the functional task task_calibration or on a config change.
Note
Can be called directly.
Definition at line 883 of file hal_adc.c.
Referenced by app_main(), cmdCa(), configSwitcherTask(), halAdcProcessPressure(), and handler_vb().
halAdcInit()
esp_err_t halAdcInit (adc_config_t * params)
Init the ADC driver module.
This method initializes the HAL ADC driver with the given config Depending on the configuration, different tasks are initialized to switch the mouthpiece mode from e.g., Joystick to Mouse to Alternative Mode (Threshold operated).
Parameters
params ADC config for intialization
Returns
ESP_OK on success, ESP_FAIL otherwise (wrong config, no memory, already initialized)
Definition at line 1282 of file hal_adc.c.
Referenced by app_main().
halAdcProcessPressure()
void halAdcProcessPressure (adcData_t * D)
Process pressure sensor (sip & puff)
This function takes care of pressure handling. If the pressure value is within the sip/puff range (but not in strong range), a VB_SIP/VB_PUFF action is triggered.
For STRONG_SIP/STRONG_PUFF, the handling depends on the settings for these buttons (example for puff, the same applies for sip):
If VB_STRONGPUFF_UP/DOWN/LEFT/RIGHT is active, the device enters the strong mode. In this case, strong_mode will be set to sip/puff. Further handling is done in halAdcProcessStrongMode. If VB_STRONGPUFF_UP/DOWN/LEFT/RIGHT is unset (none of these are active), the VB_STRONGPUFF action is triggered immediately.
See also
halAdcProcessStrongMode
Parameters
D Currently measured ADC data.
Definition at line 478 of file hal_adc.c.
Referenced by halAdcTaskThreshold().
halAdcProcessStrongMode()
void halAdcProcessStrongMode (adcData_t * D)
Trigger strong sip/puff + action according to input data.
This method is used to trigger VBs for actions of type STRONG_SIP or STRONG_PUFF combined with an additional mouthpiece movement. It should only be triggered if there is no VB_STRONGPUFF / VB_STRONGSIP action is defined (this is handled in halAdcProcessPressure).
We use 2 RTOS timers here: One for a delay between entering strong mode and triggering an action. The second timer is used for a timeout, if no additional action is triggered and we should leave the strong mode.
See also
halAdcProcessPressure
VB_STRONGPUFF
VB_STRONGSIP
VB_STRONGSIP_UP
VB_STRONGSIP_DOWN
VB_STRONGSIP_LEFT
VB_STRONGSIP_RIGHT
VB_STRONGPUFF_UP
VB_STRONGPUFF_DOWN
VB_STRONGPUFF_LEFT
VB_STRONGPUFF_RIGHT
Parameters
D ADC data from calling task
Definition at line 162 of file hal_adc.c.
Referenced by halAdcProcessPressure(), and halAdcTaskThreshold().
halAdcReportRaw()
void halAdcReportRaw (uint32_t up, uint32_t down, uint32_t left, uint32_t right, uint32_t pressure, int32_t x, int32_t y)
Report raw values via serial interface.
All values are sent in predefined string:
VALUES:<pressure>,<up>,<down>,<left>,<right>,<x>,<y> \r \n
Parameters
up Up value
down Down value
left Left value
right Right value
x X value
y Y value
pressure Pressure value
Definition at line 270 of file hal_adc.c.
Referenced by halAdcProcessPressure(), and halAdcTaskThreshold().
halAdcStrongDelay()
void halAdcStrongDelay (TimerHandle_t xTimer)
Definition at line 1242 of file hal_adc.c.
Referenced by halAdcInit().
halAdcStrongTimeout()
void halAdcStrongTimeout (TimerHandle_t xTimer)
Definition at line 1247 of file hal_adc.c.
Referenced by halAdcInit().
halAdcTaskThreshold()
void halAdcTaskThreshold (void * pvParameters)
HAL TASK - Threshold task for ADC.
This task is used for threshold mode of the moutpiece. It is invoked on config changes and reads out all 4 sensors, calculates x and y values and compares it to thresholds.
If one value exceeds the threshold, the corresponding virtual button flags are set or cleared.
Definition at line 961 of file hal_adc.c.
Referenced by halAdcUpdateConfig().
halAdcUpdateConfig()
esp_err_t halAdcUpdateConfig (adc_config_t * params)
Reload ADC config.
This method reloads the ADC config. Depending on the configuration, a task switch might be initiated to switch the mouthpiece mode from e.g., Joystick to Mouse to Alternative Mode (Threshold operated).
Parameters
params New ADC config
Returns
ESP_OK on success, ESP_FAIL otherwise (wrong config, out of memory)
Definition at line 1148 of file hal_adc.c.
Referenced by configUpdate(), and halAdcInit().
validate()
uint32_t validate (uint32_t value, uint32_t min, uint32_t max, uint32_t defaultValue)
Validate the input value and replace with default if not matching.
Parameters
value Value to be validated
min Minimum value. If "value" is below this value, "default" is returned
max Maximum value. If "value" is above this value, "default" is returned
defaultValue Default value if parameter "value" is not within given range
Returns
Fixed value
Note
Works only for unsigned values!
Definition at line 128 of file hal_adc.c.
Referenced by halAdcUpdateConfig().
Variable Documentation
adc_conf
adc_config_t adc_conf
current activated ADC config.
See also
adc_config_t
Definition at line 85 of file hal_adc.c.
adcCalibLast
TickType_t adcCalibLast = 0
Last calibrate tick time.
This value is used to determine the last time calibration was started.
See also
HAL_ADC_CALIB_LOCKTIME
Definition at line 92 of file hal_adc.c.
Referenced by halAdcCalibrate().
adcHandle
TaskHandle_t adcHandle = NULL
current loaded ADC task handle, used to delete & recreate an ADC task
See also
halAdcTaskMouse
halAdcTaskJoystick
halAdcTaskThreshold
Definition at line 80 of file hal_adc.c.
Referenced by halAdcUpdateConfig().
adcSem
SemaphoreHandle_t adcSem = NULL
Semaphore for ADC readings.
This semaphore is used to switch between halADCTask<Joystick,Mouse,Threshold> and calibration. In addition, it is used for strong sip&puff + up/down/left/right.
Definition at line 100 of file hal_adc.c.
Referenced by halAdcCalibrate(), halAdcInit(), halAdcProcessPressure(), halAdcTaskThreshold(), and halAdcUpdateConfig().
adcStrongSem
SemaphoreHandle_t adcStrongSem
Semaphore, to signal a short delay for checking strong mode.
Definition at line 119 of file hal_adc.c.
Referenced by halAdcInit(), halAdcProcessStrongMode(), and halAdcStrongDelay().
adcStrongTimeoutTimerHandle
TimerHandle_t adcStrongTimeoutTimerHandle
Timer for strong mode timeout This timer is used for a timeout moving back to STRONG_NORMAL if we entered a STRONG_PUFF or STRONG_SIP mode and no action was triggered.
Definition at line 111 of file hal_adc.c.
Referenced by halAdcInit(), halAdcProcessPressure(), halAdcProcessStrongMode(), and halAdcTaskThreshold().
adcStrongTimerHandle
TimerHandle_t adcStrongTimerHandle
Timer for strong mode delay This timer is used for waiting before checking for the additional action (up,down,left,right)
Definition at line 116 of file hal_adc.c.
Referenced by halAdcInit(), and halAdcProcessStrongMode().
characteristics
esp_adc_cal_characteristics_t characteristics
calibration characteristics, loaded by esp-idf provided methods
Definition at line 103 of file hal_adc.c.
offsetx
int32_t offsetx static
offset values, calibrated via "Calibration middle position"
Definition at line 106 of file hal_adc.c.
Referenced by halAdcCalibrate(), and halAdcReportRaw().
offsety
int32_t offsety static
Definition at line 106 of file hal_adc.c.
Referenced by halAdcCalibrate(), and halAdcReportRaw().