FLipMouse/FABI ESP32 firmware: /home/beni/sync/Projects/FH/FLipMouse-esp32/main/hal/hal_storage.c File Reference
hal_storage.c File Reference
HAL TASK - This file contains the abstraction layer for storing FLipMouse/FABI configs.
#include "hal_storage.h"
Macros
#define LOG_TAG "hal_storage"
Functions
esp_err_t halStorageNVSLoadString (const char *key, char *string)
Load a string from NVS (global, no slot assignment)
esp_err_t halStorageNVSStoreString (const char *key, char *string)
Store a string into NVS (global, no slot assignment)
esp_err_t halStorageGetFree (uint32_t *total, uint32_t *free)
Get free memory (IR & slot storage)
esp_err_t halStorageInit (void)
internal function to init the filesystem if handle is invalid
esp_err_t halStorageChecks (uint32_t tid)
Internal helper to check for a valid WL handle and the correct tid.
void halStorageCreateDefault (uint32_t tid)
Create a new default slot.
uint8_t halStorageGetCurrentSlotNumber (void)
Get number of currently loaded slot.
esp_err_t halStorageGetNumberOfSlots (uint32_t tid, uint8_t *slotsavailable)
Get the number of stored slots.
esp_err_t halStorageGetNameForNumberIR (uint32_t tid, uint8_t slotnumber, char *cmdName)
Get the name of an infrared command stored at the given slot number.
esp_err_t halStorageDeleteIRCmd (uint8_t slotnr, uint32_t tid)
Delete one or all IR commands.
esp_err_t halStorageGetNumberOfIRCmds (uint32_t tid, uint8_t *slotsavailable)
Get the number of stored IR commands.
esp_err_t halStorageGetFreeIRCmdSlot (uint32_t tid, uint8_t *slotavailable)
Get the number of first available slot for an IR command.
esp_err_t halStorageGetNameForNumber (uint32_t tid, uint8_t slotnumber, char *slotname)
Get the name of a slot number.
esp_err_t halStorageGetNumberForName (uint32_t tid, uint8_t *slotnumber, char *slotname)
Get the number of a slotname.
esp_err_t halStorageGetNumberForNameIR (uint32_t tid, uint8_t *slotnumber, char *cmdName)
Get the number of an IR command.
esp_err_t halStorageLoad (hal_storage_load_action navigate, generalConfig_t *cfg, uint32_t tid)
Load a slot by an action.
esp_err_t halStorageLoadNumber (uint8_t slotnumber, generalConfig_t *cfg, uint32_t tid)
Load a slot by a slot number (starting with 1, 0 is default slot)
esp_err_t halStorageLoadName (char *slotname, generalConfig_t *cfg, uint32_t tid)
Load a slot by a slot name.
esp_err_t halStorageDeleteSlot (int16_t slotnr, uint32_t tid)
Delete one or all slots.
esp_err_t halStorageLoadGetVBConfigs (uint8_t vb, void *vb_config, size_t vb_config_size, uint32_t tid)
Load one virtual button config for currently loaded slot.
esp_err_t halStorageStore (uint32_t tid, generalConfig_t *cfg, char *slotname, uint8_t slotnumber)
Store a generalConfig_t struct.
esp_err_t halStorageStoreIR (uint32_t tid, halIOIR_t *cfg, char *cmdName)
Store an infrared command to storage.
esp_err_t halStorageStoreSetVBConfigs (uint8_t slotnumber, generalConfig_t *config, uint32_t tid)
Store a virtual button config struct.
esp_err_t halStorageLoadIR (char *cmdName, halIOIR_t *cfg, uint32_t tid)
Load an IR command by name.
esp_err_t halStorageStartTransaction (uint32_t *tid, TickType_t tickstowait, const char *caller)
Start a storage transaction.
esp_err_t halStorageFinishTransaction (uint32_t tid)
Finish a storage transaction.
Variables
SemaphoreHandle_t halStorageMutex = NULL
Mutex which is used to avoid multiple access to different loaded slots.
static uint32_t storageCurrentTID = 0
Currently active transaction ID, 0 is invalid.
static uint8_t storageCurrentSlotNumber = 0
Currently activated slot number.
static uint8_t storageCurrentVBNumber = 0
Currently used VB number.
static wl_handle_t s_wl_handle = WL_INVALID_HANDLE
Wear levelling handle.
static const char * base_path = "/spiflash"
Partition name (used to define different memory types)
char storageCurrentTIDHolder [32]
Current active storage task.
Detailed Description
HAL TASK - This file contains the abstraction layer for storing FLipMouse/FABI configs.
This module stores general configs & virtual button configurations to a storage area. In case of the ESP32 we use FAT with wear leveling, which is provided by the esp-idf. Warning: Please adjust the esp-idf to us 512Byte sectors and mode "safety"! We don't do any safe copying, just building a checksum to detect faulty slots.
This module can be used to store a config struct (generalConfig_t) and the corresponding virtual button config structs to the storage.
Following commands are implemented here:
list all slot names
load default slot
load next or previous slot
load slot by name or number
store a given slot
delete one slot
delete all slots
delete one or all IR commands
get number of stored IR commands
load an IR command
get names for IR commands
This module starts one task on its own for maintaining the storage access. All methods called from this module will block via a semaphore until the requested operation is finished.
For storing small amounts global, non-volatile data, it is possible to use halStorageNVSLoad & halStorageNVSStore operations. In this case, no transaction id is necessary.
Slots are stored in following naming convention (8.3 rule applies here): general slot config: xxx.fms (slot number, e.g., 001.fms for slot 1) virtual button config for slot xxx xxx_VB.fms
Note
Maximum number of slots: 250! (e.g. 250.fms)
Maximum number of IR commands: 100 (0-100, e.g. IR_99.fms)
Use halStorageStartTransaction and halStorageFinishTransaction on begin/end of loading&storing (except for halStorageNVS* operations)
Warning
Adjust the esp-idf (via "make menuconfig") to use 512B sectors and mode safety!
See also
generalConfig_t
Definition in file hal_storage.c.
Macro Definition Documentation
LOG_TAG
#define LOG_TAG "hal_storage"
Definition at line 73 of file hal_storage.c.
Referenced by halStorageChecks(), halStorageCreateDefault(), halStorageDeleteIRCmd(), halStorageDeleteSlot(), halStorageFinishTransaction(), halStorageGetFreeIRCmdSlot(), halStorageGetNameForNumber(), halStorageGetNameForNumberIR(), halStorageGetNumberForName(), halStorageGetNumberForNameIR(), halStorageGetNumberOfIRCmds(), halStorageGetNumberOfSlots(), halStorageInit(), halStorageLoad(), halStorageLoadGetVBConfigs(), halStorageLoadIR(), halStorageLoadName(), halStorageLoadNumber(), halStorageStartTransaction(), halStorageStore(), halStorageStoreIR(), and halStorageStoreSetVBConfigs().
Function Documentation
halStorageChecks()
esp_err_t halStorageChecks (uint32_t tid)
Internal helper to check for a valid WL handle and the correct tid.
See also
storageCurrentTID
Parameters
tid Currently used TID
Returns
ESP_OK if all checks are valid, ESP_FAIL otherwise
Definition at line 235 of file hal_storage.c.
Referenced by halStorageCreateDefault(), halStorageDeleteIRCmd(), halStorageDeleteSlot(), halStorageGetFreeIRCmdSlot(), halStorageGetNameForNumber(), halStorageGetNameForNumberIR(), halStorageGetNumberForName(), halStorageGetNumberForNameIR(), halStorageGetNumberOfIRCmds(), halStorageGetNumberOfSlots(), halStorageLoadGetVBConfigs(), halStorageLoadIR(), halStorageLoadNumber(), halStorageStore(), halStorageStoreIR(), and halStorageStoreSetVBConfigs().
halStorageCreateDefault()
void halStorageCreateDefault (uint32_t tid)
Create a new default slot.
Create a new default slot in memory. The default settings are hardcoded here to provide a fallback solution.
Parameters
tid Valid transaction ID
Todo:
Change this default slot to usable settings
Definition at line 263 of file hal_storage.c.
Referenced by halStorageLoadNumber(), and printAllSlots().
halStorageDeleteIRCmd()
esp_err_t halStorageDeleteIRCmd (uint8_t slotnr, uint32_t tid)
Delete one or all IR commands.
This function is used to delete one IR command or all commands (depending on parameter slotnr)
Parameters
slotnr Number of slot to be deleted. Use 100 to delete all slots
Note
Setting slotnr to 100 deletes all IR slots.
Parameters
tid Transaction id
Returns
ESP_OK if everything is fine, ESP_FAIL otherwise
Definition at line 610 of file hal_storage.c.
Referenced by doInfraredParsing().
halStorageDeleteSlot()
esp_err_t halStorageDeleteSlot (int16_t slotnr, uint32_t tid)
Delete one or all slots.
This function is used to delete one slot or all slots (depending on parameter slotnr)
Parameters
slotnr Number of slot to be deleted. Use -1 to delete all slots
tid Transaction id
Warning
Deleting all slots, means that a complete factory reset is done. Maybe we change this in release versions.
Returns
ESP_OK if everything is fine, ESP_FAIL otherwise
Definition at line 1234 of file hal_storage.c.
Referenced by configSwitcherTask(), and doGeneralCmdParsing().
halStorageFinishTransaction()
esp_err_t halStorageFinishTransaction (uint32_t tid)
Finish a storage transaction.
This method is used to stop a transaction and needs to be called AFTER storage access, enabling other tasks to acquire the storage module.
See also
halStorageStartTransaction
Parameters
tid Transaction to be finished
Returns
ESP_OK if the tid is freed, ESP_FAIL if the tid is not valid
Definition at line 1915 of file hal_storage.c.
Referenced by configSwitcherTask(), doGeneralCmdParsing(), doInfraredParsing(), doStorageParsing(), infrared_record(), printAllSlots(), task_infrared(), and taskWebGUIInit().
halStorageGetCurrentSlotNumber()
uint8_t halStorageGetCurrentSlotNumber (void)
Get number of currently loaded slot.
An empty device will return 0
See also
storageCurrentSlotNumber
Returns
Currently loaded slot number
Definition at line 487 of file hal_storage.c.
Referenced by configSwitcherTask().
halStorageGetFree()
esp_err_t halStorageGetFree (uint32_t * total, uint32_t * free)
Get free memory (IR & slot storage)
This method returns the number of total and free bytes in current used persistant memory (used for storing IR commands and slot storage).
Parameters
total Pointer where the number of total possible bytes is stored
free Pointer where the number of free bytes is stored
Returns
ESP_OK if reading is valid, ESP_FAIL otherwise
Definition at line 180 of file hal_storage.c.
Referenced by doGeneralCmdParsing().
halStorageGetFreeIRCmdSlot()
esp_err_t halStorageGetFreeIRCmdSlot (uint32_t tid, uint8_t * slotavailable)
Get the number of first available slot for an IR command.
This method returns the number of the first available IR command slot. An empty device will return 0
Parameters
tid Transaction id
slotavailable Variable where the slot number will be stored
See also
halStorageStartTransaction
halStorageFinishTransaction
Returns
ESP_OK if tid is valid and slot count is valid, ESP_FAIL otherwise (no free slot)
Definition at line 722 of file hal_storage.c.
Referenced by halStorageStoreIR().
halStorageGetNameForNumber()
esp_err_t halStorageGetNameForNumber (uint32_t tid, uint8_t slotnumber, char * slotname)
Get the name of a slot number.
This method returns the name of the given slot number. An invalid slotnumber will return ESP_FAIL and an unchanged slotname
Parameters
tid Transaction id
slotname Memory to store the slotname to. Attention: minimum length: SLOTNAME_LENGTH+1
slotnumber Number of slot to be loaded
See also
halStorageStartTransaction
SLOTNAME_LENGTH
halStorageFinishTransaction
Returns
ESP_OK if tid is valid and slot number is valid, ESP_FAIL otherwise
Definition at line 766 of file hal_storage.c.
Referenced by printAllSlots().
halStorageGetNameForNumberIR()
esp_err_t halStorageGetNameForNumberIR (uint32_t tid, uint8_t slotnumber, char * cmdName)
Get the name of an infrared command stored at the given slot number.
This method returns the name of the given slot number for IR commands. An invalid slotnumber will return ESP_FAIL and an unchanged slotname
Parameters
tid Transaction id
cmdName Memory to store the command name to. Attention: minimum length: SLOTNAME_LENGTH+1
slotnumber Number of slot to be loaded
See also
halStorageStartTransaction
SLOTNAME_LENGTH
halStorageFinishTransaction
Returns
ESP_OK if tid is valid and slot number is valid, ESP_FAIL otherwise
Definition at line 554 of file hal_storage.c.
Referenced by doInfraredParsing().
halStorageGetNumberForName()
esp_err_t halStorageGetNumberForName (uint32_t tid, uint8_t * slotnumber, char * slotname)
Get the number of a slotname.
This method returns the number of the given slotname. An invalid name will return ESP_FAIL and a slotnumber of 0
Parameters
tid Transaction id
slotname Name of the slot to be looked for
slotnumber Variable where the slot number will be stored
See also
halStorageStartTransaction
halStorageFinishTransaction
Returns
ESP_OK if tid is valid and slot number is valid, ESP_FAIL otherwise
Definition at line 818 of file hal_storage.c.
Referenced by doGeneralCmdParsing(), doStorageParsing(), and halStorageLoadName().
halStorageGetNumberForNameIR()
esp_err_t halStorageGetNumberForNameIR (uint32_t tid, uint8_t * slotnumber, char * cmdName)
Get the number of an IR command.
This method returns the number of the given IR command name. An invalid name will return ESP_OK and a slotnumber of 0xFF.
Parameters
tid Transaction id
cmdName Name of the IR command to look for
slotnumber Variable where the slot number will be stored
See also
halStorageStartTransaction
halStorageFinishTransaction
Returns
ESP_OK if tid is valid and slot number is valid, ESP_FAIL otherwise
Definition at line 894 of file hal_storage.c.
Referenced by doInfraredParsing(), and halStorageStoreIR().
halStorageGetNumberOfIRCmds()
esp_err_t halStorageGetNumberOfIRCmds (uint32_t tid, uint8_t * slotsavailable)
Get the number of stored IR commands.
This method returns the number of available IR commands. An empty device will return 0
Parameters
tid Transaction id
slotsavailable Variable where the slot count will be stored
See also
halStorageStartTransaction
halStorageFinishTransaction
Returns
ESP_OK if tid is valid and slot count is valid, ESP_FAIL otherwise
Definition at line 679 of file hal_storage.c.
Referenced by doInfraredParsing().
halStorageGetNumberOfSlots()
esp_err_t halStorageGetNumberOfSlots (uint32_t tid, uint8_t * slotsavailable)
Get the number of stored slots.
This method returns the number of available slots (the default slot is not counted). An empty device will return 0
Parameters
tid Transaction id
slotsavailable Variable where the slot count will be stored
See also
halStorageStartTransaction
halStorageFinishTransaction
Returns
ESP_OK if tid is valid and slot count is valid, ESP_FAIL otherwise
Definition at line 504 of file hal_storage.c.
Referenced by doStorageParsing(), halStorageLoad(), and printAllSlots().
halStorageInit()
esp_err_t halStorageInit (void)
internal function to init the filesystem if handle is invalid
Returns
ESP_OK on success, ESP_FAIL otherwise
Definition at line 205 of file hal_storage.c.
Referenced by halStorageStartTransaction().
halStorageLoad()
esp_err_t halStorageLoad (hal_storage_load_action navigate, generalConfig_t * cfg, uint32_t tid)
Load a slot by an action.
This method loads a slot & saves the general config to the given config struct pointer. The slot is defined by the navigate parameter, using next/prev/default
To start loading a slot, call halStorageStartTransaction to acquire a load/store transaction id. This is necessary to enable multitask access.
After loading the general config, load all virtual button configs via halStorageLoadGetVBConfigs to have all necessary slot data.
Finally, if all data is loaded, call halStorageFinishTransaction to free the storage access to the other tasks or the next call.
See also
halStorageStartTransaction
halStorageFinishTransaction
halStorageLoadGetVBConfigs
hal_storage_load_action
Parameters
navigate Action defining the next loaded slot (default or prev/next)
tid Transaction ID, which must match the one given by halStorageStartTransaction
cfg Pointer to a general config struct, which will be used to load the slot into
Returns
ESP_OK if everything is fine, ESP_FAIL if the command was not successful
Definition at line 987 of file hal_storage.c.
Referenced by configSwitcherTask().
halStorageLoadGetVBConfigs()
esp_err_t halStorageLoadGetVBConfigs (uint8_t vb, void * vb_config, size_t vb_config_size, uint32_t tid)
Load one virtual button config for currently loaded slot.
This function is used to load one virtual button config after the slot was loaded (either by name, number or action).
Please use the same transaction id as for loading the slot. It is not possible to use the same tid after halStorageFinishTransaction was called.
See also
halStorageLoad
halStorageLoadName
halStorageLoadNumber
Parameters
vb Number of virtual button config to be loaded
vb_config Pointer to config struct which holds the VB config data
vb_config_size Size of config which will be loaded (differs between types of VB actions).
tid Transaction ID, which must match the one given by halStorageStartTransaction
Returns
ESP_OK if everything is fine, ESP_FAIL if the command was not successful (no config found or no slot loaded)
Definition at line 1332 of file hal_storage.c.
Referenced by configSwitcherTask().
halStorageLoadIR()
esp_err_t halStorageLoadIR (char * cmdName, halIOIR_t * cfg, uint32_t tid)
Load an IR command by name.
This method loads an IR command from storage. The slot is defined by the slot name.
To start loading a command, call halStorageStartTransaction to acquire a load/store transaction id. This is necessary to enable multitask access. Finally, if the command is loaded, call halStorageFinishTransaction to free the storage access to the other tasks or the next call.
See also
halStorageStartTransaction
halStorageFinishTransaction
Parameters
cmdName Name of the slot to be loaded
tid Transaction ID, which must match the one given by halStorageStartTransaction
cfg Pointer to a general config struct, which will be used to load the slot into
Returns
ESP_OK if everything is fine, ESP_FAIL if the command was not successful (slot name not found)
Definition at line 1747 of file hal_storage.c.
Referenced by task_infrared().
halStorageLoadName()
esp_err_t halStorageLoadName (char * slotname, generalConfig_t * cfg, uint32_t tid)
Load a slot by a slot name.
This method loads a slot & saves the general config to the given config struct pointer. The slot is defined by the slot name.
To start loading a slot, call halStorageStartTransaction to acquire a load/store transaction id. This is necessary to enable multitask access.
After loading the general config, load all virtual button configs via halStorageLoadGetVBConfigs to have all necessary slot data
Finally, if all data is loaded, call halStorageFinishTransaction to free the storage access to the other tasks or the next call.
See also
halStorageStartTransaction
halStorageFinishTransaction
halStorageLoadGetVBConfigs
Parameters
slotname Name of the slot to be loaded
tid Transaction ID, which must match the one given by halStorageStartTransaction
cfg Pointer to a general config struct, which will be used to load the slot into
Returns
ESP_OK if everything is fine, ESP_FAIL if the command was not successful (slot name not found)
Definition at line 1212 of file hal_storage.c.
Referenced by configSwitcherTask().
halStorageLoadNumber()
esp_err_t halStorageLoadNumber (uint8_t slotnumber, generalConfig_t * cfg, uint32_t tid)
Load a slot by a slot number (starting with 1, 0 is default slot)
This method loads a slot & saves the general config to the given config struct pointer. The slot is defined by the slotnumber, starting with 1. If you load the slot number 0, the default slot is loaded
To start loading a slot, call halStorageStartTransaction to acquire a load/store transaction id. This is necessary to enable multitask access.
After loading the general config, load all virtual button configs via halStorageLoadGetVBConfigs to have all necessary slot data
Finally, if all data is loaded, call halStorageFinishTransaction to free the storage access to the other tasks or the next call.
See also
halStorageStartTransaction
halStorageFinishTransaction
halStorageLoadGetVBConfigs
Parameters
slotnumber Number of the slot to be loaded
tid Transaction ID, which must match the one given by halStorageStartTransaction
cfg Pointer to a general config struct, which will be used to load the slot into
Returns
ESP_OK if everything is fine, ESP_FAIL if the command was not successful (slot number not found)
Definition at line 1069 of file hal_storage.c.
Referenced by halStorageLoad(), and halStorageLoadName().
halStorageNVSLoadString()
esp_err_t halStorageNVSLoadString (const char * key, char * string)
Load a string from NVS (global, no slot assignment)
This method is used to load a string from a non-volatile storage. No TID is necessary, just call this function.
Parameters
key Key to identify this value, same as used on store
string Buffer for string to be read from flash/eeprom (flash in ESP32)
Warning
Provide sufficient buffer length, otherwise a CPU exception will happen!
Returns
ESP_OK on success, error codes according to nvs_get_str
Definition at line 113 of file hal_storage.c.
Referenced by taskWebGUIInit().
halStorageNVSStoreString()
esp_err_t halStorageNVSStoreString (const char * key, char * string)
Store a string into NVS (global, no slot assignment)
This method is used to store a string in a non-volatile storage. No TID is necessary, just call this function.
Warning
NVS is not as big as FAT storage, use with care! (max ~10kB)
Parameters
key Key to identify this value on read.
string String to be stored in flash/eeprom (flash in ESP32)
Returns
ESP_OK on success, error codes according to nvs_set_str
Definition at line 145 of file hal_storage.c.
Referenced by doGeneralCmdParsing().
halStorageStartTransaction()
esp_err_t halStorageStartTransaction (uint32_t * tid, TickType_t tickstowait, const char * caller)
Start a storage transaction.
This method is used to start a transaction and needs to be called BEFORE any further storage access. If this function is successful (within the given ticks, the storage is getting free), a transaction ID is written, which should be used in further storage access.
After finishing, a transaction is terminated by halStorageFinishTransaction.
See also
halStorageFinishTransaction
Parameters
tid Transaction if this command was successful, 0 if not.
tickstowait Maximum amount of ticks to wait for this command to be successful
caller Name of calling task, used to track storage access
Returns
ESP_OK if the tid is valid, ESP_FAIL if other tasks did not freed the access in time
Definition at line 1859 of file hal_storage.c.
Referenced by configSwitcherTask(), doGeneralCmdParsing(), doInfraredParsing(), doStorageParsing(), infrared_record(), printAllSlots(), task_infrared(), and taskWebGUIInit().
halStorageStore()
esp_err_t halStorageStore (uint32_t tid, generalConfig_t * cfg, char * slotname, uint8_t slotnumber)
Store a generalConfig_t struct.
This method stores the general config for the given slotnumber. A slot contains:
-) General Config -) Slotname -) Slotnumber (used for the filename) -) MD5 sum (to check for corrupted content)
If there is already a slot with this given number, it is overwritten!
!! All following halStorageStoreSetVBConfigs (except the parameter slotnumber is used there) are using this slotnumber until halStorageFinishTransaction is called !!
Parameters
tid Transaction id
cfg Pointer to general config, can be freed after this call
slotname Name of this slot
slotnumber Number where to store this slot
Returns
ESP_OK on success, ESP_FAIL otherwise
See also
halStorageStoreSetVBConfigs
Definition at line 1449 of file hal_storage.c.
Referenced by doStorageParsing(), and halStorageCreateDefault().
halStorageStoreIR()
esp_err_t halStorageStoreIR (uint32_t tid, halIOIR_t * cfg, char * cmdName)
Store an infrared command to storage.
This method stores a set of IR edges with a given length and a given command name. If there is already a cmd with this given name, it is overwritten!
Parameters
tid Transaction id
cfg Pointer to a IR config, can be freed after this call
cmdName Name of this IR command
Returns
ESP_OK on success, ESP_FAIL otherwise
See also
halIOIR_t
halStorageLoadIR
Definition at line 1546 of file hal_storage.c.
Referenced by infrared_record().
halStorageStoreSetVBConfigs()
esp_err_t halStorageStoreSetVBConfigs (uint8_t slotnumber, generalConfig_t * config, uint32_t tid)
Store a virtual button config struct.
This method stores the config structs for virtual buttons.
Configs are provided via generalConfig struct, which contains necessary information:
Size of config
Pointer to current config
Parameters
tid Transaction id
slotnumber Number of the slot on which this config is used. Use 0xFF to ignore and use previous set slot number (by halStorageStore)
config Pointer to the general config struct (containing pointers/size to VB cfg)
Returns
ESP_OK on success, ESP_FAIL otherwise
See also
halStorageStore
storageHeader_t
Warning
size element of generalConfig_t MUST be set to have a successful write.
Note
This method always overwrites an existing config!
Definition at line 1642 of file hal_storage.c.
Referenced by doStorageParsing(), and halStorageCreateDefault().
Variable Documentation
base_path
const char* base_path = "/spiflash" static
Partition name (used to define different memory types)
Definition at line 93 of file hal_storage.c.
Referenced by halStorageDeleteIRCmd(), halStorageDeleteSlot(), halStorageGetFreeIRCmdSlot(), halStorageGetNameForNumber(), halStorageGetNameForNumberIR(), halStorageGetNumberForName(), halStorageGetNumberForNameIR(), halStorageGetNumberOfIRCmds(), halStorageGetNumberOfSlots(), halStorageInit(), halStorageLoadGetVBConfigs(), halStorageLoadIR(), halStorageLoadNumber(), halStorageStore(), halStorageStoreIR(), and halStorageStoreSetVBConfigs().
halStorageMutex
SemaphoreHandle_t halStorageMutex = NULL
Mutex which is used to avoid multiple access to different loaded slots.
See also
storageCurrentTID
Definition at line 77 of file hal_storage.c.
Referenced by halStorageFinishTransaction(), and halStorageStartTransaction().
s_wl_handle
wl_handle_t s_wl_handle = WL_INVALID_HANDLE static
Wear levelling handle.
Definition at line 90 of file hal_storage.c.
Referenced by halStorageChecks(), halStorageInit(), and halStorageStartTransaction().
storageCurrentSlotNumber
uint8_t storageCurrentSlotNumber = 0 static
Currently activated slot number.
Definition at line 81 of file hal_storage.c.
Referenced by halStorageGetCurrentSlotNumber(), halStorageLoad(), halStorageLoadGetVBConfigs(), halStorageLoadNumber(), halStorageStore(), and halStorageStoreSetVBConfigs().
storageCurrentTID
uint32_t storageCurrentTID = 0 static
Currently active transaction ID, 0 is invalid.
Definition at line 79 of file hal_storage.c.
Referenced by halStorageChecks(), halStorageFinishTransaction(), and halStorageStartTransaction().
storageCurrentTIDHolder
char storageCurrentTIDHolder[32]
Current active storage task.
This string is used to determine the currently active task, which holds a tid.
See also
storageCurrentTID
Definition at line 101 of file hal_storage.c.
Referenced by halStorageStartTransaction().
storageCurrentVBNumber
uint8_t storageCurrentVBNumber = 0 static
Currently used VB number.
This number is used for halStorageStoreSetVBConfigs only.
See also
halStorageStoreSetVBConfigs
Definition at line 87 of file hal_storage.c.
Referenced by halStorageStartTransaction().