FLipMouse/FABI ESP32 firmware: /home/beni/sync/Projects/FH/FLipMouse-esp32/main/ble_hid/hal_ble.h File Reference
hal_ble.h File Reference
This file is a C compatible wrapper for Neil Kolbans CPP utils.
#include <freertos/FreeRTOS.h>
#include <freertos/event_groups.h>
#include <freertos/queue.h>
#include <esp_log.h>
#include <keyboard.h>
#include "common.h"
Functions
esp_err_t halBLESetPairing (uint8_t enable)
Activate/deactivate pairing mode.
uint8_t halBLEIsConnected (void)
Get connection status.
esp_err_t halBLEEnDisable (int onoff)
En- or Disable BLE interface.
void halBLEReset (uint8_t exceptDevice)
Reset the BLE data.
esp_err_t halBLEInit (uint8_t enableKeyboard, uint8_t enableMouse, uint8_t enableJoystick)
Main init function to start HID interface (C interface)
Variables
QueueHandle_t hid_ble
Queue for sending mouse reports.
Detailed Description
This file is a C compatible wrapper for Neil Kolbans CPP utils.
It receives data from hid_ble queue, which is equal to hid_usb. C++ classes are instantiated from here.
Note
Thank you very much Neil Kolban and chegewara for this impressive work!
Definition in file hal_ble.h.
Function Documentation
halBLEEnDisable()
esp_err_t halBLEEnDisable (int onoff)
En- or Disable BLE interface.
This method is used to enable or disable the BLE interface. Currently, the ESP32 cannot use WiFi and BLE simultaneously. Therefore, when enabling wifi, it is necessary to disable BLE prior calling taskWebGUIEnDisable.
Note
Calling this method prior to initializing BLE via halBLEInit will result in an error!
Returns
ESP_OK on success, ESP_FAIL otherwise
Parameters
onoff If != 0, switch on BLE, switch off if 0.
Definition at line 837 of file HID_kbdmousejoystick.cpp.
Referenced by app_main(), and wifi_timer_cb().
halBLEInit()
esp_err_t halBLEInit (uint8_t enableKeyboard, uint8_t enableMouse, uint8_t enableJoystick)
Main init function to start HID interface (C interface)
See also
hid_ble
Definition at line 812 of file HID_kbdmousejoystick.cpp.
Referenced by app_main().
halBLEIsConnected()
uint8_t halBLEIsConnected (void)
Get connection status.
Todo:
Add interface to disable BLE & free memory! (see long button handler in main)
Returns
0 if not connected, != 0 if connected
Todo:
Add interface to disable BLE & free memory! (see long button handler in main)
Returns
0 if not connected, != 0 if connected
Definition at line 805 of file HID_kbdmousejoystick.cpp.
halBLEReset()
void halBLEReset (uint8_t exceptDevice)
Reset the BLE data.
Used for slot/config switchers. It resets the keycode array and sets all HID reports to 0 (release all keys, avoiding sticky keys on a config change)
Parameters
exceptDevice if you want to reset only a part of the devices, set flags accordingly:
(1<<0) excepts keyboard (1<<1) excepts joystick (1<<2) excepts mouse If nothing is set (exceptDevice = 0) all are reset
Definition at line 864 of file HID_kbdmousejoystick.cpp.
Referenced by configTimerCallback(), and doGeneralCmdParsing().
halBLESetPairing()
esp_err_t halBLESetPairing (uint8_t enable)
Activate/deactivate pairing mode.
Parameters
enable If set to != 0, pairing will be enabled. Disabled if == 0
Returns
ESP_OK on success, ESP_FAIL otherwise
Definition at line 790 of file HID_kbdmousejoystick.cpp.
Variable Documentation
hid_ble
QueueHandle_t hid_ble
Queue for sending mouse reports.
See also
hid_cmd_t
Definition at line 59 of file flipmouse_fabi_esp32_kbdmouse_main.c.
Referenced by checkqueues(), doJoystickParsing(), halAdcInit(), halAdcProcessPressure(), sendHIDCmd(), and task_hid().