FLipMouse/FABI ESP32 firmware: /home/beni/sync/Projects/FH/FLipMouse-esp32/main/hal/hal_serial.c File Reference
hal_serial.c File Reference
CONTINOUS TASK - This module contains the hardware abstraction for the serial interface to the USB support chip.
#include "hal_serial.h"
Macros
#define LOG_TAG "hal_serial"
#define LOG_LEVEL_SERIAL ESP_LOG_WARN
#define HAL_SERIAL_TASK_STACKSIZE 2048
#define HAL_SERIAL_UART_TIMEOUT_MS 10000
Ticks until the UART receive function has a timeout and gives back received data.*.
#define HAL_SERIAL_I2C_TIMEOUT_MS 100
Timout for receiving ADC data via I2C.
#define WRITE_BIT I2C_MASTER_WRITE /** @brief I2C master write */
#define READ_BIT I2C_MASTER_READ /** @brief I2C master read */
#define ACK_CHECK_EN 0x1 /** @brief I2C master will check ack from slave*/
#define ACK_CHECK_DIS 0x0 /** @brief I2C master will not check ack from slave */
#define ACK_VAL 0x0 /** @brief I2C ack value */
#define NACK_VAL 0x1 /** @brief I2C nack value */
Functions
void halSerialFlushRX (void)
Flush Serial RX input buffer.
void halSerialRXTask (void *pvParameters)
UART RX task for AT command pattern detection and parsing.
esp_err_t halSerialInitI2C (bool deinit)
Initialize I2C for reading ADC values from LPC.
void halSerialHIDTask (void *param)
CONTINOUS TASK - Process HID commands & send via HID wire to LPC.
int halSerialReceiveI2CADC (uint8_t **data)
Read ADC data via I2C from LPC chip.
int halSerialReceiveUSBSerial (uint8_t **data)
Read parsed AT commands from USB-Serial (USB-CDC)
int halSerialSendUSBSerial (char *data, uint32_t length, TickType_t ticks_to_wait)
Send serial bytes to USB-Serial (USB-CDC)
void halSerialReset (uint8_t exceptDevice)
Reset the serial HID report data.
void halSerialRemoveOutputStream (void)
Remove the additional function for outputting the serial data.
void halSerialAddOutputStream (serialoutput_h cb)
Set an additional function for outputting the serial data.
esp_err_t halSerialInit (void)
Initialize the serial HAL.
Variables
static const int BUF_SIZE_RX = 512
serialoutput_h outputcb = NULL
Output callback.
static const int CMDQUEUE_SIZE = 256
Length of queue for AT commands.
static const int BUF_SIZE_TX = 512
static SemaphoreHandle_t serialsendingsem
Mutex for sending to serial port.
Detailed Description
CONTINOUS TASK - This module contains the hardware abstraction for the serial interface to the USB support chip.
Attention: this module does NOT use UART0 (terminal & program interface)
The hardware abstraction takes care of:
sending USB-HID commands
sending USB-serial responses
sending/receiving serial data (to/from USB-serial)
The interaction to other parts of the firmware consists of:
pending on queue for USB commands: hid_usb
halSerialSendUSBSerial / halSerialReceiveUSBSerial for direct sending/receiving (USB-CDC)
The received serial data can be used by different modules, currently the task_commands is used to fetch & parse serial data.
Note
In this firmware, there are 3 pins routed to the USB support chip (RX,TX,HID). RX/TX lines are used as normal UART, which is converted by the LPC USB chip to the USB-CDC interface. The third line (HID) is used as a pulse length modulated output for transmitting HID commands to the host.
Definition in file hal_serial.c.
Macro Definition Documentation
ACK_CHECK_DIS
#define ACK_CHECK_DIS 0x0 /** @brief I2C master will not check ack from slave */
Definition at line 107 of file hal_serial.c.
ACK_CHECK_EN
#define ACK_CHECK_EN 0x1 /** @brief I2C master will check ack from slave*/
Definition at line 106 of file hal_serial.c.
Referenced by halSerialHIDTask(), and halSerialReceiveI2CADC().
ACK_VAL
#define ACK_VAL 0x0 /** @brief I2C ack value */
Definition at line 108 of file hal_serial.c.
Referenced by halSerialReceiveI2CADC().
HAL_SERIAL_I2C_TIMEOUT_MS
#define HAL_SERIAL_I2C_TIMEOUT_MS 100
Timout for receiving ADC data via I2C.
See also
halSerialReceiveI2CADC
Definition at line 75 of file hal_serial.c.
HAL_SERIAL_TASK_STACKSIZE
#define HAL_SERIAL_TASK_STACKSIZE 2048
Definition at line 54 of file hal_serial.c.
Referenced by halSerialInit().
HAL_SERIAL_UART_TIMEOUT_MS
#define HAL_SERIAL_UART_TIMEOUT_MS 10000
Ticks until the UART receive function has a timeout and gives back received data.*.
This value should be adjusted, either if the maximum length of a transmitted command OR the baudrate is changed. If you adjust the
Currently, the value 30ms reflects 115k2 baud and 256 bytes for one AT command:
~87us are necessary for 1 byte (115k2 baud + 10 bit times)
~22ms are necessary for maximum command length
-> next bigger value reflectable in ticks is 30ms.
See also
ATCMD_LENGTH
Todo:
Documentation updates, this define is now used differently...
Definition at line 71 of file hal_serial.c.
Referenced by halSerialReceiveUSBSerial().
LOG_LEVEL_SERIAL
#define LOG_LEVEL_SERIAL ESP_LOG_WARN
Definition at line 52 of file hal_serial.c.
Referenced by halSerialInit().
LOG_TAG
#define LOG_TAG "hal_serial"
Definition at line 49 of file hal_serial.c.
Referenced by halSerialHIDTask(), halSerialInit(), halSerialInitI2C(), halSerialReceiveUSBSerial(), halSerialReset(), halSerialRXTask(), and halSerialSendUSBSerial().
NACK_VAL
#define NACK_VAL 0x1 /** @brief I2C nack value */
Definition at line 109 of file hal_serial.c.
Referenced by halSerialReceiveI2CADC().
READ_BIT
#define READ_BIT I2C_MASTER_READ /** @brief I2C master read */
Definition at line 105 of file hal_serial.c.
Referenced by halSerialReceiveI2CADC().
WRITE_BIT
#define WRITE_BIT I2C_MASTER_WRITE /** @brief I2C master write */
Definition at line 104 of file hal_serial.c.
Referenced by halSerialHIDTask().
Function Documentation
halSerialAddOutputStream()
void halSerialAddOutputStream (serialoutput_h cb)
Set an additional function for outputting the serial data.
This function sets a callback, which is used if the program needs an additional output despite the serial interface. In this case, the webgui registers a callback, which sends all the serial data to the websocket
Parameters
cb Function callback
Definition at line 515 of file hal_serial.c.
Referenced by ws_server().
halSerialFlushRX()
void halSerialFlushRX (void)
Flush Serial RX input buffer.
Definition at line 112 of file hal_serial.c.
halSerialHIDTask()
void halSerialHIDTask (void * param)
CONTINOUS TASK - Process HID commands & send via HID wire to LPC.
This task is used to receive a byte buffer, which contains a HID command for the LPC. These bytes are converted into either long or short pulses for 0 and 1 bits, finished by a "very long" stop bit.
HID commands are built up following this declarations: Byte 0: type of command: K/M/J/C:
K are keyboard reports
M are mouse reports
J are joystick reports
C are set locale commands
Following parameter lenghts are valid: "K": 7 Bytes; 1 modifier + 6 keycode "M": 4 Bytes; Button mask + X + Y + wheel "J": 13 Bytes; Please consult task_joystick.c for a detailed explanation "C": 1 Byte; Locale code, according to HID specification chapter 6.2.1
Parameters
param Unused
See also
hid_command_t
hid_usb
HAL_SERIAL_HIDPIN
Note
Due to the nature of absolute values for some HID input, it is sometimes wanted to update only relative values (e.g. move mouse, but don't change mouse button status). To support only updates of partial reports, the LPC chip supports a feature where the absolute value is NOT changed by sending 0xFF for the corresponding byte. Currently following bytefields support this:
Mouse: buttons
Definition at line 279 of file hal_serial.c.
Referenced by halSerialInit().
halSerialInit()
esp_err_t halSerialInit (void)
Initialize the serial HAL.
This method initializes the serial interface & creates all necessary tasks.
Definition at line 525 of file hal_serial.c.
Referenced by app_main().
halSerialInitI2C()
esp_err_t halSerialInitI2C (bool deinit)
Initialize I2C for reading ADC values from LPC.
This function initializes the I2C, according to the pin settings.
See also
HAL_IO_PIN_SDA
HAL_IO_PIN_SCL
Parameters
deinit If set to true, the driver will be deleted first (used for re-initializing on transmission errors)
Definition at line 219 of file hal_serial.c.
Referenced by halSerialHIDTask(), halSerialInit(), and halSerialReceiveI2CADC().
halSerialReceiveI2CADC()
int halSerialReceiveI2CADC (uint8_t ** data)
Read ADC data via I2C from LPC chip.
This method reads 10Bytes of ADC data from LPC chip via the I2C interface.
Returns
-1 on error, number of read bytes otherwise
Parameters
data Double pointer to save 10 Bytes of data
See also
HAL_SERIAL_I2C_TIMEOUT_MS
Definition at line 331 of file hal_serial.c.
Referenced by halAdcReportRaw().
halSerialReceiveUSBSerial()
int halSerialReceiveUSBSerial (uint8_t ** data)
Read parsed AT commands from USB-Serial (USB-CDC)
This method reads full AT commands from the halSerialATCmds queue.
Returns
-1 on error, number of read bytes otherwise
Parameters
data Double pointer to save the new allocated buffer to.
Warning
Free the data pointer after use!
Note
In timeout, debug information is print. Please uncomment if wanted:
Printing free heap for each VB task
Print task CPU usage (only supported if "Use Trace facilities" is activated)
See also
HAL_SERIAL_UART_TIMEOUT_MS
halSerialATCmds
halSerialRXTask
Definition at line 368 of file hal_serial.c.
Referenced by task_commands().
halSerialRemoveOutputStream()
void halSerialRemoveOutputStream (void)
Remove the additional function for outputting the serial data.
This function removes the callback, which is used if the program needs an additional output despite the serial interface.
Definition at line 502 of file hal_serial.c.
Referenced by wifi_event_handler().
halSerialReset()
void halSerialReset (uint8_t exceptDevice)
Reset the serial HID report data.
Used for slot/config switchers. It resets the keycode array and sets all HID reports to 0 (release all keys, avoiding sticky keys on a config change)
Parameters
exceptDevice if you want to reset only a part of the devices, set flags accordingly:
(1<<0) excepts keyboard (1<<1) excepts joystick (1<<2) excepts mouse If nothing is set (exceptDevice = 0) all are reset
Definition at line 455 of file hal_serial.c.
Referenced by cmdRa(), and configUpdate().
halSerialRXTask()
void halSerialRXTask (void * pvParameters)
UART RX task for AT command pattern detection and parsing.
This task is used to pend on any incoming UART bytes. After receiving bytes, the incoming data is put together into AT commands. On a fully received AT command (terminated either by '\r' or '\n'), the buffer will be sent to the halSerialATCmds queue.
See also
halSerialATCmds
Definition at line 126 of file hal_serial.c.
Referenced by halSerialInit().
halSerialSendUSBSerial()
int halSerialSendUSBSerial (char * data, uint32_t length, TickType_t ticks_to_wait)
Send serial bytes to USB-Serial (USB-CDC)
This method sends bytes to the UART, for USB-CDC
Returns
-1 on error, number of read bytes otherwise
Parameters
data Data to be sent
length Number of maximum bytes to send
ticks_to_wait Maximum time to wait for a free UART
Definition at line 409 of file hal_serial.c.
Referenced by cmdFr(), cmdId(), cmdIl(), fct_infrared_record(), halAdcReportRaw(), halStorageLoadNumber(), printAllSlots(), sendButtonLearn(), sendErrorBack(), and task_commands().
Variable Documentation
BUF_SIZE_RX
const int BUF_SIZE_RX = 512 static
Definition at line 77 of file hal_serial.c.
Referenced by halSerialInit().
BUF_SIZE_TX
const int BUF_SIZE_TX = 512 static
Definition at line 97 of file hal_serial.c.
Referenced by halSerialInit().
CMDQUEUE_SIZE
const int CMDQUEUE_SIZE = 256 static
Length of queue for AT commands.
Note
A maximum of CMDQUEUE_SIZE x ATCMD_LENGTH can be allocated (if no task receives the commands)
C# GUI usually floods the input with AT cmds, set at least to 64 to avoid missing AT commands.
See also
halSerialATCmds
Definition at line 95 of file hal_serial.c.
Referenced by halSerialInit().
outputcb
serialoutput_h outputcb = NULL
Output callback.
If this callback is != NULL, the function halSerialSendUSBSerial will send data to this callback in addition to the serial interface
See also
halSerialSendUSBSerial
serialoutput_h
Definition at line 86 of file hal_serial.c.
Referenced by halSerialAddOutputStream(), halSerialRemoveOutputStream(), and halSerialSendUSBSerial().
serialsendingsem
SemaphoreHandle_t serialsendingsem static
Mutex for sending to serial port.
Definition at line 101 of file hal_serial.c.
Referenced by halSerialInit(), and halSerialSendUSBSerial().