FLipMouse/FABI ESP32 firmware: /home/beni/sync/Projects/FH/FLipMouse-esp32/main/hal/hal_ble.c File Reference
hal_ble.c File Reference
#include "hal_ble.h"
#include "esp_system.h"
#include "esp_wifi.h"
#include "esp_event_loop.h"
#include "esp_log.h"
#include "nvs_flash.h"
#include "esp_bt.h"
#include "hid_desc.h"
#include "hid_dev.h"
#include "esp_hidd_prf_api.h"
#include "esp_bt_defs.h"
#include "esp_gap_ble_api.h"
#include "esp_gatts_api.h"
#include "esp_gatt_defs.h"
#include "esp_bt_main.h"
#include "esp_bt_device.h"
#include "bt_trace.h"
#include "keyboard.h"
Macros
#define LOG_TAG "hal_ble"
Functions
void halBleTaskKeyboardPress (void *param)
void halBleTaskKeyboardRelease (void *param)
void halBleTaskMouse (void *param)
void halBleTaskJoystick (void *param)
void halBLEReset (uint8_t exceptDevice)
esp_err_t halBLEInit (uint8_t deviceIdentifier)
Variables
TaskHandle_t halbletasks [4]
char halbletasknames [4][14] = {"hal_ble_kbd_p", "hal_ble_kbd_r", "hal_ble_mouse", "hal_ble_joyst"}
TaskFunction_t halbletaskfunctions [4]
const char hid_device_name_fabi [] = "FABI"
const char hid_device_name_flipmouse [] = "FLipMouse"
Macro Definition Documentation
LOG_TAG
#define LOG_TAG "hal_ble"
Definition at line 59 of file hal_ble.c.
Referenced by halBleTaskJoystick(), halBleTaskKeyboardPress(), halBleTaskKeyboardRelease(), and halBleTaskMouse().
Function Documentation
halBLEInit()
esp_err_t halBLEInit (uint8_t deviceIdentifier)
initializing BLE HAL
This method initializes the BLE staff: -) Enable BT -) Init GATT & GAP -) Start 4 tasks: Joystick, Mouse, Keyboard Press & Keyboard Release
Parameters
locale Keyboard locale which should be used by this device
deviceIdentifier Which device is using this firmware? FABI or FLipMouse?
See also
DEVICE_FABI
DEVICE_FLIPMOUSE
register the callback function to the gap module
Definition at line 427 of file hal_ble.c.
Referenced by app_main().
halBLEReset()
void halBLEReset (uint8_t exceptDevice)
reset the BLE data Used for slot/config switchers. It resets the keycode array and sets all HID reports to 0 (release all keys, avoiding sticky keys on a config change)
Parameters
exceptDevice if you want to reset only a part of the devices, set flags accordingly:
(1<<0) excepts keyboard (1<<1) excepts joystick (1<<2) excepts mouse If nothing is set (exceptDevice = 0) all are reset
Definition at line 394 of file hal_ble.c.
Referenced by configSwitcherTask(), and doGeneralCmdParsing().
halBleTaskJoystick()
void halBleTaskJoystick (void * param)
Definition at line 354 of file hal_ble.c.
halBleTaskKeyboardPress()
void halBleTaskKeyboardPress (void * param)
Definition at line 181 of file hal_ble.c.
halBleTaskKeyboardRelease()
void halBleTaskKeyboardRelease (void * param)
Definition at line 253 of file hal_ble.c.
halBleTaskMouse()
void halBleTaskMouse (void * param)
Definition at line 305 of file hal_ble.c.
Variable Documentation
halbletaskfunctions
TaskFunction_t halbletaskfunctions[4]
Initial value:
= {
  halBleTaskKeyboardPress,
  halBleTaskKeyboardRelease,
  halBleTaskMouse,
  halBleTaskJoystick,
}
Definition at line 76 of file hal_ble.c.
halbletasknames
char halbletasknames[4][14] = {"hal_ble_kbd_p", "hal_ble_kbd_r", "hal_ble_mouse", "hal_ble_joyst"}
Definition at line 75 of file hal_ble.c.
halbletasks
TaskHandle_t halbletasks[4]
Definition at line 74 of file hal_ble.c.
hid_device_name_fabi
const char hid_device_name_fabi[] = "FABI"
Definition at line 83 of file hal_ble.c.
hid_device_name_flipmouse
const char hid_device_name_flipmouse[] = "FLipMouse"
Definition at line 84 of file hal_ble.c.