FLipMouse/FABI ESP32 firmware: /home/beni/sync/Projects/FH/FLipMouse-esp32/main/hal/hal_io.c File Reference
hal_io.c File Reference
HAL TASK - This file contains the hardware abstraction for all IO related stuff (except ADC).
#include "hal_io.h"
Macros
#define LOG_TAG "halIO"
Log tag.
#define RMT_CLK_DIV 100
Clock divider for RMT engine.
#define RMT_TICK_10_US (80000000/RMT_CLK_DIV/100000)
RMT counter value for 10 us.(Source clock is APB clock)
Functions
static void gpio_isr_handler (void *arg)
GPIO ISR handler for buttons (internal/external)
void halIOIRFree (rmt_channel_t channel, void *arg)
Callback to free the memory after finished transmission.
void halIOIRSendTask (void *param)
HAL TASK - IR sending task.
void halIOIRRecvTask (void *param)
HAL TASK - IR receiving (recording) task.
void halIOBuzzerTask (void *param)
HAL TASK - Buzzer update task.
void halIOLEDTask (void *param)
HAL TASK - LED update task.
void halIOAddLongPressHandler (void(*longpress_h)(void))
Add long press handler for Wifi button.
void halIOTimerCallback (TimerHandle_t xTimer)
Timer callback for calling longpress handler.
esp_err_t halIOInit (void)
Initializing IO HAL.
Variables
QueueHandle_t halIOLEDQueue = NULL
LED update queue.
void(* longpress_handler)(void) = NULL
Currently active long press handler, null if not used.
TimerHandle_t longactiontimer = NULL
Timer handle for long press action.
Detailed Description
HAL TASK - This file contains the hardware abstraction for all IO related stuff (except ADC).
Following peripherals are utilized here:
Input buttons
RGB LED (or maybe a Neopixel LED)
IR receiver (TSOP)
IR LED (sender)
Buzzer
All assigned buttons are processed via one GPIO ISR, which sets press and release flags in the VB input event group. In addition, one button can be configured for executing an extra handler after a long press (this long press is much longer compared to "long press" actions handled by task_debouncer). This handler is usually used for activating and deactivating the WiFi interface.
The LED output is configurable either to 3 PWM outputs for RGB LEDs or a Neopixel string with variable length (RGB LEDs use ledc facilities, Neopixels use RMT engine). To enable easy color settings, macros are provided (LED(r,g,b,m)).
IR receiving / sending is done via the RMT engine and is supported by macros as well.
Note
Compared to the tasks in the folder "function_tasks" all HAL tasks are singletons. Call init to initialize every necessary data structure.
Todo:
Test LED driver (RGB & Neopixel)
Definition in file hal_io.c.
Macro Definition Documentation
LOG_TAG
#define LOG_TAG "halIO"
Log tag.
Definition at line 55 of file hal_io.c.
Referenced by halIOBuzzerTask(), halIOInit(), halIOIRRecvTask(), halIOIRSendTask(), and halIOLEDTask().
RMT_CLK_DIV
#define RMT_CLK_DIV 100
Clock divider for RMT engine.
Definition at line 109 of file hal_io.c.
Referenced by halIOInit().
RMT_TICK_10_US
#define RMT_TICK_10_US (80000000/RMT_CLK_DIV/100000)
RMT counter value for 10 us.(Source clock is APB clock)
Definition at line 112 of file hal_io.c.
Referenced by halIOInit().
Function Documentation
gpio_isr_handler()
static void gpio_isr_handler (void * arg) static
GPIO ISR handler for buttons (internal/external)
This ISR handler is called on rising&falling edge of each button GPIO.
It sets and clears the VB flags accordingly on each call. These flags are used for button debouncing.
See also
task_debouncer
Definition at line 124 of file hal_io.c.
Referenced by halIOInit().
halIOAddLongPressHandler()
void halIOAddLongPressHandler (void(*)(void) longpress_h)
Add long press handler for Wifi button.
One button (define by HAL_IO_PIN_LONGACTION) can be used as long press button for enabling/disabling wifi (in addition to normal press/release actions). If this functionality should be used, add a handler with this method, which will be called after the button is pressed longer than HAL_IO_LONGACTION_TIMEOUT.
Note
HAL_IO_PIN_LONGACTION cannot be used as individual button. Use a pin, which is already used for a normal action, otherwise the handler won't be used (ISR won't get triggered).
Clear the handler by passing a void function pointer.
See also
HAL_IO_LONGACTION_TIMEOUT
HAL_IO_PIN_LONGACTION
Parameters
longpress_h Handler for long press action, use a null pointer to disable the handler.
Definition at line 553 of file hal_io.c.
Referenced by app_main().
halIOBuzzerTask()
void halIOBuzzerTask (void * param)
HAL TASK - Buzzer update task.
This task takes an instance of the buzzer update struct and creates a tone on the buzzer accordingly. Done via the LEDC driver & vTaskDelays
See also
halIOBuzzer_t
halIOBuzzerQueue
Parameters
param Unused.
Definition at line 364 of file hal_io.c.
Referenced by halIOInit().
halIOInit()
esp_err_t halIOInit (void)
Initializing IO HAL.
This method initializes the IO HAL stuff:
GPIO interrupt on 2 external and one internal button
RMT engine (recording and replaying of infrared commands)
LEDc driver for the RGB LED output
PWM for buzzer output
Definition at line 574 of file hal_io.c.
Referenced by app_main().
halIOIRFree()
void halIOIRFree (rmt_channel_t channel, void * arg)
Callback to free the memory after finished transmission.
This method calls free() on the buffer which is transmitted now.
Parameters
channel Channel of RMT enging
arg rmt_item32_t* pointer to the buffer
Definition at line 188 of file hal_io.c.
Referenced by halIOIRSendTask().
halIOIRRecvTask()
void halIOIRRecvTask (void * param)
HAL TASK - IR receiving (recording) task.
This task is used to store data from the RMT unit if the receiving of an IR code is started. By sending an element to the queue halIOIRRecvQueue, this task starts to receive any incoming IR signals. The status of the struct is updated (either finished, timeout or error) on any status change. Poll this value to see if the receiver is finished.
See also
halIOIR_t
halIOIRRecvQueue
Parameters
param Unused.
Definition at line 252 of file hal_io.c.
Referenced by halIOInit().
halIOIRSendTask()
void halIOIRSendTask (void * param)
HAL TASK - IR sending task.
This task receives via halIOIRSendQueue a pointer and a length of waveform array, which is sent to the RMT unit.
See also
halIOIR_t
halIOIRSendQueue
Parameters
param Unused.
Definition at line 202 of file hal_io.c.
Referenced by halIOInit().
halIOLEDTask()
void halIOLEDTask (void * param)
HAL TASK - LED update task.
This task simply takes an uint32_t value from the LED queue and calls the ledc_fading_... methods of the esp-idf.
See also
halIOLEDQueue
Parameters
param Unused
Todo:
It might be possible that we use Neopixel LEDs on the FLipMouse as well. Update if it is known.
Definition at line 422 of file hal_io.c.
Referenced by halIOInit().
halIOTimerCallback()
void halIOTimerCallback (TimerHandle_t xTimer)
Timer callback for calling longpress handler.
Parameters
xTimer Unused
Definition at line 560 of file hal_io.c.
Referenced by halIOInit().
Variable Documentation
halIOLEDQueue
QueueHandle_t halIOLEDQueue = NULL
LED update queue.
This queue is used to update the LED color & brightness Please use one uint32_t value with following content:
<bits 0-7> RED
<bits 8-15> GREEN
<bits 16-23> BLUE
Depending on the LED config (either one RGB LED or Neopixels are used), bits 24-31 are used differently:
RGB LED (LED_USE_NEOPIXEL is NOT defined):
<bits 24-31> Fading time ([10¹ms] -> value of 200 is 2s)
Neopixels (LED_USE_NEOPIXEL is defined):
<bits 24-31> Animation mode:
0 Steady color on all Neopixels
1 3 Neopixels have the given color and are circled around
2-0xFF Currently undefined, further modes might be added.
Note
Call halIOInit to initialize this queue.
See also
halIOInit
LED_USE_NEOPIXEL
LED_NEOPIXEL_COUNT
Definition at line 84 of file hal_io.c.
Referenced by halIOInit(), and halIOLEDTask().
longactiontimer
TimerHandle_t longactiontimer = NULL
Timer handle for long press action.
See also
halIOAddLongPressHandler
Definition at line 106 of file hal_io.c.
Referenced by gpio_isr_handler(), and halIOInit().
longpress_handler
void(* longpress_handler) (void) = NULL
Currently active long press handler, null if not used.
See also
halIOAddLongPressHandler
Definition at line 102 of file hal_io.c.
Referenced by halIOAddLongPressHandler(), and halIOTimerCallback().