FLipMouse/FABI ESP32 firmware: /home/beni/sync/Projects/FH/FLipMouse-esp32/main/hal/hal_serial.h File Reference
hal_serial.h File Reference
CONTINOUS TASK - This module contains the hardware abstraction for the serial interface to the USB support chip.
#include <freertos/FreeRTOS.h>
#include <freertos/event_groups.h>
#include <freertos/semphr.h>
#include <esp_log.h>
#include "driver/uart.h"
#include "driver/i2c.h"
#include "soc/uart_struct.h"
#include "string.h"
#include "common.h"
#include "keyboard.h"
#include "../config_switcher.h"
Data Structures
struct atcmd
AT command type for halSerialATCmds queue.
Macros
#define HAL_SERIAL_TXPIN (GPIO_NUM_17)
TX pin for serial IF to LPC chip.
#define HAL_SERIAL_RXPIN (GPIO_NUM_16)
RTX pin for serial IF to LPC chip.
#define HAL_SERIAL_HIDPIN (GPIO_NUM_18)
signalling pin for serial IF to LPC chip
#define HAL_SERIAL_UART (UART_NUM_2)
UART unit number for serial IF to LPC chip.
#define HAL_SERIAL_EXT_TXPIN (GPIO_NUM_4)
TX pin for serial IF to addon boards.
#define HAL_SERIAL_EXT_RXPIN (GPIO_NUM_19)
RX pin for serial IF to addon boards.
#define HAL_SERIAL_LINE_ENDING "\r\n"
Sets line ending character According to FLipMouse GUI PortIO.cs, is used.
#define HAL_SERIAL_I2C_ADDR_LPC 0x05
I2C Address for LPC chip.
Typedefs
typedef esp_err_t(* serialoutput_h) (char *p_data, size_t length)
Function pointer type for an additional output of a serial stream.
typedef struct atcmd atcmd_t
AT command type for halSerialATCmds queue.
Functions
void halSerialAddOutputStream (serialoutput_h cb)
Set an additional function for outputting the serial data.
void halSerialRemoveOutputStream (void)
Remove the additional function for outputting the serial data.
esp_err_t halSerialInit (void)
Initialize the serial HAL.
void halSerialReset (uint8_t exceptDevice)
Reset the serial HID report data.
int halSerialSendUSBSerial (char *data, uint32_t length, TickType_t ticks_to_wait)
Send serial bytes to USB-Serial (USB-CDC)
void halSerialFlushRX (void)
Flush Serial RX input buffer.
int halSerialReceiveUSBSerial (uint8_t **data)
Read parsed AT commands from USB-Serial (USB-CDC)
int halSerialReceiveI2CADC (uint8_t **data)
Read ADC data via I2C from LPC chip.
Variables
QueueHandle_t halSerialATCmds
Queue for parsed AT commands.
Detailed Description
CONTINOUS TASK - This module contains the hardware abstraction for the serial interface to the USB support chip.
Attention: this module does NOT use UART0 (terminal & program interface)
The hardware abstraction takes care of:
sending USB-HID commands
sending USB-serial responses
sending/receiving serial data (to/from USB-serial)
The interaction to other parts of the firmware consists of:
pending on queue for USB commands: hid_usb
halSerialSendUSBSerial / halSerialReceiveUSBSerial for direct sending/receiving (USB-CDC)
The received serial data can be used by different modules, currently the task_commands is used to fetch & parse serial data.
Note
In this firmware, there are 3 pins routed to the USB support chip (RX,TX,HID). RX/TX lines are used as normal UART, which is converted by the LPC USB chip to the USB-CDC interface. The third line (HID) is used as a pulse length modulated output for transmitting HID commands to the host.
Definition in file hal_serial.h.
Macro Definition Documentation
HAL_SERIAL_EXT_RXPIN
#define HAL_SERIAL_EXT_RXPIN (GPIO_NUM_19)
RX pin for serial IF to addon boards.
Note
Currently unused, reserved for future additions
Definition at line 78 of file hal_serial.h.
HAL_SERIAL_EXT_TXPIN
#define HAL_SERIAL_EXT_TXPIN (GPIO_NUM_4)
TX pin for serial IF to addon boards.
Note
Currently unused, reserved for future additions
Definition at line 75 of file hal_serial.h.
HAL_SERIAL_HIDPIN
#define HAL_SERIAL_HIDPIN (GPIO_NUM_18)
signalling pin for serial IF to LPC chip
See also
halSerialSendUSBSerial
Definition at line 69 of file hal_serial.h.
HAL_SERIAL_I2C_ADDR_LPC
#define HAL_SERIAL_I2C_ADDR_LPC 0x05
I2C Address for LPC chip.
Definition at line 85 of file hal_serial.h.
Referenced by halSerialHIDTask(), and halSerialReceiveI2CADC().
HAL_SERIAL_LINE_ENDING
#define HAL_SERIAL_LINE_ENDING "\r\n"
Sets line ending character According to FLipMouse GUI PortIO.cs, is used.
Definition at line 82 of file hal_serial.h.
Referenced by halSerialSendUSBSerial().
HAL_SERIAL_RXPIN
#define HAL_SERIAL_RXPIN (GPIO_NUM_16)
RTX pin for serial IF to LPC chip.
Definition at line 66 of file hal_serial.h.
Referenced by halSerialInit().
HAL_SERIAL_TXPIN
#define HAL_SERIAL_TXPIN (GPIO_NUM_17)
TX pin for serial IF to LPC chip.
Definition at line 64 of file hal_serial.h.
Referenced by halSerialInit().
HAL_SERIAL_UART
#define HAL_SERIAL_UART (UART_NUM_2)
UART unit number for serial IF to LPC chip.
Definition at line 71 of file hal_serial.h.
Referenced by halSerialFlushRX(), halSerialInit(), halSerialRXTask(), and halSerialSendUSBSerial().
Typedef Documentation
atcmd_t
typedef struct atcmd atcmd_t
AT command type for halSerialATCmds queue.
This type of data is used to pass one AT command (in format of "AT MX 100") to any pending task.
See also
halSerialATCmds
serialoutput_h
typedef esp_err_t(* serialoutput_h) (char *p_data, size_t length)
Function pointer type for an additional output of a serial stream.
Definition at line 101 of file hal_serial.h.
Function Documentation
halSerialAddOutputStream()
void halSerialAddOutputStream (serialoutput_h cb)
Set an additional function for outputting the serial data.
This function sets a callback, which is used if the program needs an additional output despite the serial interface. In this case, the webgui registers a callback, which sends all the serial data to the websocket
Parameters
cb Function callback
Definition at line 515 of file hal_serial.c.
Referenced by ws_server().
halSerialFlushRX()
void halSerialFlushRX (void)
Flush Serial RX input buffer.
Definition at line 112 of file hal_serial.c.
halSerialInit()
esp_err_t halSerialInit (void)
Initialize the serial HAL.
This method initializes the serial interface & creates all necessary tasks
This method initializes the serial interface & creates all necessary tasks.
Definition at line 525 of file hal_serial.c.
Referenced by app_main().
halSerialReceiveI2CADC()
int halSerialReceiveI2CADC (uint8_t ** data)
Read ADC data via I2C from LPC chip.
This method reads 10Bytes of ADC data from LPC chip via the I2C interface.
Returns
-1 on error, number of read bytes otherwise
Parameters
data Double pointer to save 10 Bytes of data
See also
HAL_SERIAL_I2C_TIMEOUT_MS
Definition at line 331 of file hal_serial.c.
Referenced by halAdcReportRaw().
halSerialReceiveUSBSerial()
int halSerialReceiveUSBSerial (uint8_t ** data)
Read parsed AT commands from USB-Serial (USB-CDC)
This method reads full AT commands from the halSerialATCmds queue.
Returns
-1 on error, number of read bytes otherwise
Parameters
data Double pointer to save the new allocated buffer to.
Warning
Free the data pointer after use!
See also
HAL_SERIAL_UART_TIMEOUT_MS
halSerialATCmds
halSerialRXTask
This method reads full AT commands from the halSerialATCmds queue.
Returns
-1 on error, number of read bytes otherwise
Parameters
data Double pointer to save the new allocated buffer to.
Warning
Free the data pointer after use!
Note
In timeout, debug information is print. Please uncomment if wanted:
Printing free heap for each VB task
Print task CPU usage (only supported if "Use Trace facilities" is activated)
See also
HAL_SERIAL_UART_TIMEOUT_MS
halSerialATCmds
halSerialRXTask
Definition at line 368 of file hal_serial.c.
Referenced by task_commands().
halSerialRemoveOutputStream()
void halSerialRemoveOutputStream (void)
Remove the additional function for outputting the serial data.
This function removes the callback, which is used if the program needs an additional output despite the serial interface.
Definition at line 502 of file hal_serial.c.
Referenced by wifi_event_handler().
halSerialReset()
void halSerialReset (uint8_t exceptDevice)
Reset the serial HID report data.
Used for slot/config switchers. It resets the keycode array and sets all HID reports to 0 (release all keys, avoiding sticky keys on a config change)
Parameters
exceptDevice if you want to reset only a part of the devices, set flags accordingly:
(1<<0) excepts keyboard (1<<1) excepts joystick (1<<2) excepts mouse If nothing is set (exceptDevice = 0) all are reset
Definition at line 455 of file hal_serial.c.
Referenced by cmdRa(), and configUpdate().
halSerialSendUSBSerial()
int halSerialSendUSBSerial (char * data, uint32_t length, TickType_t ticks_to_wait)
Send serial bytes to USB-Serial (USB-CDC)
This method sends bytes to the UART, for USB-CDC
Returns
-1 on error, number of read bytes otherwise
Parameters
data Data to be sent
length Number of maximum bytes to send
ticks_to_wait Maximum time to wait for a free UART
Definition at line 409 of file hal_serial.c.
Referenced by cmdFr(), cmdId(), cmdIl(), fct_infrared_record(), halAdcReportRaw(), halStorageLoadNumber(), printAllSlots(), sendButtonLearn(), sendErrorBack(), and task_commands().
Variable Documentation
halSerialATCmds
QueueHandle_t halSerialATCmds
Queue for parsed AT commands.
This queue is read by halSerialReceiveUSBSerial (which receives from the queue and frees the memory afterwards). AT commands are sent by halSerialRXTask, which parses each byte.
Note
Pass structs of type atcmd_t, no pointer!
See also
halSerialRXTask
halSerialReceiveUSBSerial
CMDQUEUE_SIZE
atcmd_t
Definition at line 98 of file hal_serial.h.
Referenced by fct_macro(), halSerialInit(), halSerialReceiveUSBSerial(), halSerialRXTask(), halStorageLoadNumber(), task_commands(), and ws_server_netconn_serve().