FLipMouse/FABI ESP32 firmware: /home/beni/sync/Projects/FH/FLipMouse-esp32/main/hal/hal_adc.h File Reference
hal_adc.h File Reference
HAL TASK + FUNCTIONAL TASK - This module contains the hardware abstraction as well as the calculations of the ADC.
#include <string.h>
#include <freertos/FreeRTOS.h>
#include <freertos/event_groups.h>
#include <freertos/queue.h>
#include <esp_log.h>
#include <driver/adc.h>
#include "esp_adc_cal.h"
#include "common.h"
#include "hal_serial.h"
#include "math.h"
Macros
#define HAL_IO_ADC_TASK_PRIORITY 4
Task priority for ADC task.
#define TASK_CALIB_STACKSIZE 1024
Stacksize for functional task task_calibration.
#define ACCELTIME_MAX 20000
Parameter for mouse acceleration calculation.
Functions
void halAdcCalibrate (void)
Calibration function.
void task_calibration (taskNoParameterConfig_t *param)
FUNCTIONAL TASK - Trigger zero-point calibration of mouthpiece.
esp_err_t halAdcUpdateConfig (adc_config_t *params)
Reload ADC config.
esp_err_t halAdcInit (adc_config_t *params)
Init the ADC driver module.
Detailed Description
HAL TASK + FUNCTIONAL TASK - This module contains the hardware abstraction as well as the calculations of the ADC.
The hal_adc files are used to measure all ADC inputs (4 direction sensors and 1 pressure sensor). In addition, depending on the configuration, different ADC tasks are loaded. One of these tasks is loaded:
halAdcMouse - Use the ADC values as mouse input
halAdcThreshold - Use the ADC values to trigger virtual buttons (keyboard actions for example)
halAdcJoystick - Use the ADC input to control the HID joystick
These tasks are HAL tasks, which means they might be reloaded/changed, but they are not managed outside this module.
In addition, the FUNCTIONAL task task_calibration can be used to trigger a zero-point calibration of the mouthpiece.
See also
adc_config_t
Todo:
Add raw value reporting for: CIM mode and serial interface
Definition in file hal_adc.h.
Macro Definition Documentation
ACCELTIME_MAX
#define ACCELTIME_MAX 20000
Parameter for mouse acceleration calculation.
Definition at line 127 of file hal_adc.h.
Referenced by halAdcProcessPressure().
HAL_IO_ADC_TASK_PRIORITY
#define HAL_IO_ADC_TASK_PRIORITY 4
Task priority for ADC task.
Definition at line 121 of file hal_adc.h.
TASK_CALIB_STACKSIZE
#define TASK_CALIB_STACKSIZE 1024
Stacksize for functional task task_calibration.
See also
task_calibration
Definition at line 124 of file hal_adc.h.
Referenced by configSwitcherTask().
Function Documentation
halAdcCalibrate()
void halAdcCalibrate (void)
Calibration function.
This method is called to calibrate the offset value for x and y axis of the mouthpiece. Either triggered by the functional task task_calibration or on a config change.
Note
Can be called directly.
Definition at line 726 of file hal_adc.c.
Referenced by app_main(), configSwitcherTask(), halAdcInit(), halAdcUpdateConfig(), and task_calibration().
halAdcInit()
esp_err_t halAdcInit (adc_config_t * params)
Init the ADC driver module.
This method initializes the HAL ADC driver with the given config Depending on the configuration, different tasks are initialized to switch the mouthpiece mode from e.g., Joystick to Mouse to Alternative Mode (Threshold operated).
Parameters
params ADC config for intialization
Returns
ESP_OK on success, ESP_FAIL otherwise (wrong config, no memory, already initialized)
Todo:
init differently for FABI!
Definition at line 1095 of file hal_adc.c.
Referenced by app_main().
halAdcUpdateConfig()
esp_err_t halAdcUpdateConfig (adc_config_t * params)
Reload ADC config.
This method reloads the ADC config. Depending on the configuration, a task switch might be initiated to switch the mouthpiece mode from e.g., Joystick to Mouse to Alternative Mode (Threshold operated).
Parameters
params New ADC config
Returns
ESP_OK on success, ESP_FAIL otherwise (wrong config, out of memory)
This method reloads the ADC config. Depending on the configuration, a task switch might be initiated to switch the mouthpiece mode from e.g., Joystick to Mouse to Alternative Mode (Threshold operated).
Parameters
params New ADC config
Todo:
Clear pending VB flags on a config switch
Returns
ESP_OK on success, ESP_FAIL otherwise (wrong config, out of memory)
Definition at line 983 of file hal_adc.c.
Referenced by configUpdate(), halAdcInit(), and printAllSlots().
task_calibration()
void task_calibration (taskNoParameterConfig_t * param)
FUNCTIONAL TASK - Trigger zero-point calibration of mouthpiece.
This task is used to trigger a zero-point calibration of up/down/left/right input.
Parameters
param Task configuration
See also
halAdcCalibrate
taskNoParameterConfig_t
Definition at line 796 of file hal_adc.c.
Referenced by configSwitcherTask(), and doMouthpieceSettingsParsing().