FLipMouse/FABI ESP32 firmware: /home/beni/sync/Projects/FH/FLipMouse-esp32/main/function_tasks/handler_hid.h File Reference
handler_hid.h File Reference
Event Handler - HID.
#include <freertos/FreeRTOS.h>
#include <freertos/event_groups.h>
#include <freertos/queue.h>
#include <esp_log.h>
#include <esp_event.h>
#include "common.h"
#include "fct_macros.h"
#include "../config_switcher.h"
Functions
esp_err_t handler_hid_init (void)
Init for the HID handler.
hid_cmd_t * handler_hid_getCmdChain (void)
Get current root of HID command chain.
esp_err_t handler_hid_setCmdChain (hid_cmd_t *chain)
Set current root of HID command chain!
esp_err_t handler_hid_addCmd (hid_cmd_t *newCmd, uint8_t replace)
Add a new HID command for a virtual button.
esp_err_t handler_hid_delCmd (uint8_t vb)
Remove HID command for a virtual button.
esp_err_t handler_hid_clearCmds (void)
Clear all stored HID commands.
esp_err_t handler_hid_getAT (char *output, uint8_t vb)
Reverse Parsing - get AT command for HID VB.
bool handler_hid_active (uint8_t vb)
Check if a VB is active in this handler.
Detailed Description
Event Handler - HID.
This module is used as an event handler for all HID based virtual buttons, containing:
Mouse clicking, holding, pressing & release as well as movement (X/Y/Z)
Keyboard press,hold,release & write
Joystick press,hold,release & axis movement
handler_hid_init is initializing the mutex for adding a command to the chained list and adding handler_hid to the system event queue.
Note
Currently, we use the system event queue (because there is already a task attached). Maybe we switch to an unique one.
Mouse/keyboard/joystick control by mouthpiece is done in hal_adc!
See also
hal_adc
Definition in file handler_hid.h.
Function Documentation
handler_hid_active()
bool handler_hid_active (uint8_t vb)
Check if a VB is active in this handler.
This function returns true if a given vb is active in this handler (is located in the command chain with a given command).
Parameters
vb Number of virtual button to check
Returns
true if active, false if not
This function returns true if a given vb is active in this handler (is located in the command chain with a given command).
Parameters
vb Number of virtual button to check
Returns
true if active, false if not
Note
We don't care if press/release is active here. Any associated action will return true.
Definition at line 486 of file handler_hid.c.
Referenced by halAdcProcessPressure().
handler_hid_addCmd()
esp_err_t handler_hid_addCmd (hid_cmd_t * newCmd, uint8_t replace)
Add a new HID command for a virtual button.
This method adds the given HID command to the list of HID commands which will be processed if the corresponding VB is triggered.
Note
Highest bit determines press/release action. If set, it is a press!
If VB number is set to VB_SINGLESHOT, the command will be sent immediately.
We will malloc for each command here. To free the memory, call handler_hid_clearCmds .
Parameters
newCmd New command to be added.
replace If set to != 0, any previously assigned command is removed from list.
Returns
ESP_OK if added, ESP_FAIL if not added (out of memory)
Definition at line 220 of file handler_hid.c.
Referenced by sendHIDCmd().
handler_hid_clearCmds()
esp_err_t handler_hid_clearCmds (void)
Clear all stored HID commands.
This method clears all stored HID commands and frees the allocated memory.
Returns
ESP_OK if commands are cleared, ESP_FAIL otherwise
Definition at line 371 of file handler_hid.c.
Referenced by handler_hid_setCmdChain().
handler_hid_delCmd()
esp_err_t handler_hid_delCmd (uint8_t vb)
Remove HID command for a virtual button.
This method removes any HID command from the list of HID commands which are assigned to this VB.
Parameters
vb VB which should be removed
Returns
ESP_OK if deleted, ESP_FAIL if not in list
Definition at line 171 of file handler_hid.c.
Referenced by cmdNc(), handler_hid_addCmd(), and sendVBCmd().
handler_hid_getAT()
esp_err_t handler_hid_getAT (char * output, uint8_t vb)
Reverse Parsing - get AT command for HID VB.
This function parses the current configuration of a virtual button to an AT command used to print the configuration.
Parameters
output Output string, where the full AT command will be stored
vb Number of virtual button for getting the AT command
Returns
ESP_OK if everything went fine, ESP_FAIL otherwise
Definition at line 430 of file handler_hid.c.
Referenced by storeSlot().
handler_hid_getCmdChain()
hid_cmd_t* handler_hid_getCmdChain (void)
Get current root of HID command chain.
Warning
Modifying this chain without acquiring the hidCmdSem could result in undefined behaviour!
Returns
Pointer to root of HID chain
Definition at line 319 of file handler_hid.c.
handler_hid_init()
esp_err_t handler_hid_init (void)
Init for the HID handler.
We create the mutex and add handler_hid to the system event queue.
Returns
ESP_OK on success, ESP_FAIL on an error.
Definition at line 147 of file handler_hid.c.
Referenced by app_main().
handler_hid_setCmdChain()
esp_err_t handler_hid_setCmdChain (hid_cmd_t * chain)
Set current root of HID command chain!
Warning
By using this function, previously used HID commands are cleared!
Parameters
chain Pointer to root of HID chain
Returns
ESP_OK if chain is saved, ESP_FAIL otherwise (lock was not free, deleting old chain failed..)
Definition at line 329 of file handler_hid.c.