FLipMouse/FABI ESP32 firmware: /home/beni/sync/Projects/FH/FLipMouse-esp32/main/ble_hid/hid_device_le_prf.c File Reference
hid_device_le_prf.c File Reference
#include "hidd_le_prf_int.h"
#include <string.h>
#include "bt_types.h"
#include "bt_trace.h"
Data Structures
struct prf_char_pres_fmt
characteristic presentation information
Macros
#define HI_UINT16(a) (((a) >> 8) & 0xFF)
#define LO_UINT16(a) ((a) & 0xFF)
#define CHAR_DECLARATION_SIZE (sizeof(uint8_t))
Enumerations
enum {
BAS_IDX_SVC, BAS_IDX_BATT_LVL_CHAR, BAS_IDX_BATT_LVL_VAL, BAS_IDX_BATT_LVL_NTF_CFG,
BAS_IDX_BATT_LVL_PRES_FMT, BAS_IDX_NB
}
Battery Service Attributes Indexes.
Functions
void esp_hidd_prf_cb_hdl (esp_gatts_cb_event_t event, esp_gatt_if_t gatts_if, esp_ble_gatts_cb_param_t *param)
void hidd_le_create_service (esp_gatt_if_t gatts_if)
void hidd_set_countrycode (uint8_t countrycode)
void hidd_le_init (void)
void hidd_clcb_alloc (uint16_t conn_id, esp_bd_addr_t bda)
bool hidd_clcb_dealloc (uint16_t conn_id)
esp_err_t hidd_register_cb (void)
void hidd_set_attr_value (uint16_t handle, uint16_t val_len, const uint8_t *value)
void hidd_get_attr_value (uint16_t handle, uint16_t *length, uint8_t **value)
Variables
hidd_le_env_t hidd_le_env
uint8_t hidReportMapLen = sizeof(hidReportMap)
uint8_t hidProtocolMode = HID_PROTOCOL_MODE_REPORT
uint16_t hid_count = 0
esp_gatts_incl_svc_desc_t incl_svc = {0}
Macro Definition Documentation
CHAR_DECLARATION_SIZE
#define CHAR_DECLARATION_SIZE (sizeof(uint8_t))
Definition at line 247 of file hid_device_le_prf.c.
HI_UINT16
#define HI_UINT16 (a) (((a) >> 8) & 0xFF)
Definition at line 191 of file hid_device_le_prf.c.
LO_UINT16
#define LO_UINT16 (a) ((a) & 0xFF)
Definition at line 192 of file hid_device_le_prf.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Battery Service Attributes Indexes.
Enumerator
BAS_IDX_SVC
BAS_IDX_BATT_LVL_CHAR
BAS_IDX_BATT_LVL_VAL
BAS_IDX_BATT_LVL_NTF_CFG
BAS_IDX_BATT_LVL_PRES_FMT
BAS_IDX_NB
Definition at line 179 of file hid_device_le_prf.c.
Function Documentation
esp_hidd_prf_cb_hdl()
void esp_hidd_prf_cb_hdl (esp_gatts_cb_event_t event, esp_gatt_if_t gatts_if, esp_ble_gatts_cb_param_t * param)
Definition at line 505 of file hid_device_le_prf.c.
Referenced by hidd_register_cb().
hidd_clcb_alloc()
void hidd_clcb_alloc (uint16_t conn_id, esp_bd_addr_t bda)
Definition at line 611 of file hid_device_le_prf.c.
Referenced by esp_hidd_prf_cb_hdl().
hidd_clcb_dealloc()
bool hidd_clcb_dealloc (uint16_t conn_id)
Definition at line 628 of file hid_device_le_prf.c.
Referenced by esp_hidd_prf_cb_hdl().
hidd_get_attr_value()
void hidd_get_attr_value (uint16_t handle, uint16_t * length, uint8_t ** value)
Definition at line 660 of file hid_device_le_prf.c.
hidd_le_create_service()
void hidd_le_create_service (esp_gatt_if_t gatts_if)
Definition at line 588 of file hid_device_le_prf.c.
Referenced by esp_hidd_prf_cb_hdl().
hidd_le_init()
void hidd_le_init (void)
Definition at line 604 of file hid_device_le_prf.c.
hidd_register_cb()
esp_err_t hidd_register_cb (void)
Definition at line 641 of file hid_device_le_prf.c.
Referenced by esp_hidd_register_callbacks().
hidd_set_attr_value()
void hidd_set_attr_value (uint16_t handle, uint16_t val_len, const uint8_t * value)
Definition at line 648 of file hid_device_le_prf.c.
hidd_set_countrycode()
void hidd_set_countrycode (uint8_t countrycode)
set the bCountryCode field of the HID info.
Warning
Set this before initializing anything else!
Definition at line 599 of file hid_device_le_prf.c.
Variable Documentation
hid_count
uint16_t hid_count = 0
Definition at line 244 of file hid_device_le_prf.c.
hidd_le_env
hidd_le_env_t hidd_le_env
Definition at line 194 of file hid_device_le_prf.c.
Referenced by esp_hidd_profile_deinit(), esp_hidd_profile_init(), esp_hidd_register_callbacks(), esp_hidd_send_consumer_value(), esp_hidd_send_keyboard_value(), and esp_hidd_send_mouse_value().
hidProtocolMode
uint8_t hidProtocolMode = HID_PROTOCOL_MODE_REPORT
Definition at line 198 of file hid_device_le_prf.c.
hidReportMapLen
uint8_t hidReportMapLen = sizeof(hidReportMap)
Definition at line 197 of file hid_device_le_prf.c.
incl_svc
esp_gatts_incl_svc_desc_t incl_svc = {0}
Definition at line 245 of file hid_device_le_prf.c.
Referenced by esp_hidd_prf_cb_hdl().