FLipMouse/FABI ESP32 firmware: /home/beni/sync/Projects/FH/FLipMouse-esp32/main/ble_hid/hid_dev.c File Reference
hid_dev.c File Reference
#include "hid_dev.h"
#include "keylayouts.h"
#include "bt_trace.h"
#include <stdint.h>
#include <string.h>
#include <stdbool.h>
#include <stdio.h>
Macros
#define M(x) (x&0xFF)
mask for media keycodes to limit to 8bit
Functions
static hid_report_map_t * hid_dev_rpt_by_id (uint8_t id, uint8_t type)
void hid_dev_register_reports (uint8_t num_reports, hid_report_map_t *p_report)
void hid_dev_send_report (esp_gatt_if_t gatts_if, uint16_t conn_id, uint8_t id, uint8_t type, uint8_t length, uint8_t *data)
void hid_consumer_build_report (uint8_t *buffer, consumer_cmd_t cmd)
Variables
static hid_report_map_t * hid_dev_rpt_tbl
static uint8_t hid_dev_rpt_tbl_Len
Macro Definition Documentation
M
#define M (x) (x&0xFF)
mask for media keycodes to limit to 8bit
Definition at line 24 of file hid_dev.c.
Referenced by hid_consumer_build_report().
Function Documentation
hid_consumer_build_report()
void hid_consumer_build_report (uint8_t * buffer, consumer_cmd_t cmd)
Definition at line 68 of file hid_dev.c.
Referenced by esp_hidd_send_consumer_value().
hid_dev_register_reports()
void hid_dev_register_reports (uint8_t num_reports, hid_report_map_t * p_report)
Definition at line 46 of file hid_dev.c.
Referenced by hid_add_id_tbl().
hid_dev_rpt_by_id()
static hid_report_map_t* hid_dev_rpt_by_id (uint8_t id, uint8_t type) static
Definition at line 33 of file hid_dev.c.
Referenced by hid_dev_send_report().
hid_dev_send_report()
void hid_dev_send_report (esp_gatt_if_t gatts_if, uint16_t conn_id, uint8_t id, uint8_t type, uint8_t length, uint8_t * data)
Definition at line 53 of file hid_dev.c.
Referenced by esp_hidd_send_consumer_value(), esp_hidd_send_keyboard_value(), and esp_hidd_send_mouse_value().
Variable Documentation
hid_dev_rpt_tbl
hid_report_map_t* hid_dev_rpt_tbl static
Definition at line 30 of file hid_dev.c.
Referenced by hid_dev_rpt_by_id().
hid_dev_rpt_tbl_Len
uint8_t hid_dev_rpt_tbl_Len static
Definition at line 31 of file hid_dev.c.