FLipMouse/FABI ESP32 firmware: /home/beni/sync/Projects/FH/FLipMouse-esp32/main/keyboard_layout_helper/keyboard.c File Reference
keyboard.c File Reference
Keyboard layout/keycode helper functions.
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include "keyboard.h"
#include "esp_log.h"
#include "undefkeylayouts.h"
#include "keylayouts.h"
Macros
#define LOG_TAG "KB"
#define COMP(x, y) (memcmp(x,y,sizeof(y)-1) == 0)
#define SAVE(x) if(buf_len > sizeof(x)) { memcpy(buffer,x,sizeof(x)); } else { return 2; } break
#define LAYOUT_US_INTERNATIONAL
#define LAYOUT_US_ENGLISH
#define LAYOUT_US_INTERNATIONAL
#define LAYOUT_US_ENGLISH
#define LAYOUT_US_INTERNATIONAL
#define LAYOUT_US_INTERNATIONAL
Functions
uint8_t keycode_is_modifier (uint16_t keycode)
Is this keycode a modifier?
uint16_t unicode_to_keycode (uint16_t cpoint, uint8_t locale)
Parse a decoded code point to a keycode, step 2.
uint16_t deadkey_to_keycode (uint16_t keycode, uint8_t locale)
Parse a keycode for deadkey input, step 3.
uint8_t keycode_to_key (uint16_t keycode)
Mask the keycode to get the HID keycode, step 4.
uint8_t keycode_to_modifier (uint16_t keycode, uint8_t locale)
Mask the keycode to get the modifiers, step 5.
uint8_t parse_for_keycode (uint8_t inputdata, uint8_t locale, uint8_t *keycode_modifier, uint8_t *deadkey_first_keycode)
Parse an incoming byte for a keycode.
uint8_t remove_keycode (uint8_t keycode, uint8_t *keycode_arr)
Remove a keycode from the given HID keycode array.
uint8_t add_keycode (uint8_t keycode, uint8_t *keycode_arr)
Add a keycode to the given HID keycode array.
uint16_t parseIdentifierToKeycode (char *keyidentifier)
Parse a key identifier to a keycode.
uint16_t parseKeycodeToIdentifier (uint16_t keycode, char *buffer, uint8_t buf_len)
Parse a keycode to a key identifier.
uint8_t get_keycode (uint16_t cpoint, uint8_t locale, uint8_t *keycode_modifier, uint8_t *deadkey_first_keystroke)
Get a keycode for the given UTF codepoint.
uint8_t get_hid_country_code (uint8_t locale)
Getting the HID country code for a given locale.
Variables
const uint16_t deadkey_USINT [2][5]
Defines the bits and deadkeys itself for all available deadkeys for US_INTERNATIONAL. All other layouts have an equal array. If a layout does not have deadkeys at all, this array is of [2][1] dimension and initialised with {0,0}.
const uint16_t keycodes_masks [][5]
Defines all masks necessary for either getting modifiers or the keycode.
const uint16_t * keycodes_deadkey_bits []
Array of pointers to a deadkey bits array for each locale.
const uint16_t * keycodes_deadkey []
Array of pointers to a deadkey keycodes array for each locale.
const uint16_t keycodes_ascii [][96]
Array of all keycodes for ASCII symbols.
const uint16_t keycodes_iso_8859_1 [][96]
Array of all keycodes for ISO8859 (unicode) symbols/code points.
Detailed Description
Keyboard layout/keycode helper functions.
This module is basically a wrapper around Paul Stoffregen's keylayouts.h file, which contains all keycodes & locales. This file supports following tasks:
Get a keycode for one or more ASCII/Unicode bytes
Get a HID country code for a locale
Get a keycode for a key identifier (e.g., KEY_A)
Get a key identifier for a keycode
Fill/empty a keycode array for HID reports
This file is mostly used by task_kbd and task_commands modules.
This file is built around keylayouts.h, a header file for all keyboard layouts from Paul Stoffregen. To avoid modifying the header file, this file is playing some tricks with preprocessor defines:
1.) Include header "undefkeylayouts.h", which removes all previously set keycodes and different bit sets
2.) Define the currently used keyboard layout
3.) Include the "keylayouts.h" header
4.) Use all the bits, masks and keycodes
5.) Redo steps 1-4 for all different arrays for all keyboard layouts
Note
Once again: Thank you very much Paul for these layouts!
Definition in file keyboard.c.
Macro Definition Documentation
COMP
#define COMP (x, y) (memcmp(x,y,sizeof(y)-1) == 0)
Helper macro to compare key identifiers, y must be of fixed size!
Definition at line 67 of file keyboard.c.
Referenced by parseIdentifierToKeycode().
LAYOUT_US_ENGLISH [1/2]
#define LAYOUT_US_ENGLISH
Referenced by get_hid_country_code(), and unicode_to_keycode().
LAYOUT_US_ENGLISH [2/2]
#define LAYOUT_US_ENGLISH
LAYOUT_US_INTERNATIONAL [1/4]
#define LAYOUT_US_INTERNATIONAL
Referenced by get_hid_country_code().
LAYOUT_US_INTERNATIONAL [2/4]
#define LAYOUT_US_INTERNATIONAL
LAYOUT_US_INTERNATIONAL [3/4]
#define LAYOUT_US_INTERNATIONAL
LAYOUT_US_INTERNATIONAL [4/4]
#define LAYOUT_US_INTERNATIONAL
LOG_TAG
#define LOG_TAG "KB"
Definition at line 64 of file keyboard.c.
Referenced by deadkey_to_keycode(), get_hid_country_code(), keycode_to_modifier(), and unicode_to_keycode().
SAVE
#define SAVE (x) if(buf_len > sizeof(x)) { memcpy(buffer,x,sizeof(x)); } else { return 2; } break
Helper macro to save key identifier, x must be a static string!
Definition at line 69 of file keyboard.c.
Referenced by parseKeycodeToIdentifier().
Function Documentation
add_keycode()
uint8_t add_keycode (uint8_t keycode, uint8_t * keycode_arr)
Add a keycode to the given HID keycode array.
Note
The size of the keycode_arr parameter MUST be 6
Parameters
keycode Keycode to be added
keycode_arr Keycode to add this keycode to
Returns
0 if the keycode was added, 1 if the keycode was already in the array, 2 if there was no space
Definition at line 2131 of file keyboard.c.
Referenced by halBleTaskKeyboardPress(), and halSerialTaskKeyboardPress().
deadkey_to_keycode()
uint16_t deadkey_to_keycode (uint16_t keycode, uint8_t locale)
Parse a keycode for deadkey input, step 3.
This method parses a keycode for a possible deadkey sequence. If the parsed keycode needs a deadkey press, the corresponding keycode is returned. If no deadkey is required, 0 is returned. To get a keycode, use the method unicode_to_keycode.
See also
unicode_to_keycode
keycodes_masks
Parameters
keycode Keycode which might need a deadkey pressed
locale Currently used keyboard layout
Returns
0 if no deadkey needs to be pressed, the deadkey keycode otherwise
Definition at line 1983 of file keyboard.c.
Referenced by doKeyboardParsing(), and parse_for_keycode().
get_hid_country_code()
uint8_t get_hid_country_code (uint8_t locale)
Getting the HID country code for a given locale.
Source: USB Device class definition for HID, page 33
See also
keyboard_layouts
Returns
bCountryCode value for HID info
Parameters
locale Locale number, as defined in keyboard_layouts
Definition at line 2553 of file keyboard.c.
Referenced by halBLEInit().
get_keycode()
uint8_t get_keycode (uint16_t cpoint, uint8_t locale, uint8_t * keycode_modifier, uint8_t * deadkey_first_keystroke)
Get a keycode for the given UTF codepoint.
This method parses a 16bit unicode character to a keycode. If a modifier is needed the given modifier byte is updated.
See also
keyboard_layouts
Parameters
cpoint 16bit Unicode-codepoint to parse
locale Use this locale/layout to parse
keycode_modifier If a modifier is needed, it will be written here
deadkey_first_keystroke If a deadkey stroke is needed, it will be written here
Returns
0 if no keycode is found; the keycode otherwise
Definition at line 2531 of file keyboard.c.
keycode_is_modifier()
uint8_t keycode_is_modifier (uint16_t keycode)
Is this keycode a modifier?
This method is used to determine if a keycode is a modifier key (without any other keys)
Parameters
keycode Keycode to be tested
Returns
0 if a normal keycode, 1 if a modifier key
Definition at line 354 of file keyboard.c.
Referenced by doKeyboardParsing().
keycode_to_key()
uint8_t keycode_to_key (uint16_t keycode)
Mask the keycode to get the HID keycode, step 4.
This method masks out all modifier bits and returns the direct HID keycode, which can be used in HID reports.
Parameters
keycode Keycode from other parsing methods
Returns
8-bit keycode for HID
Definition at line 2008 of file keyboard.c.
Referenced by doKeyboardParsing(), and parse_for_keycode().
keycode_to_modifier()
uint8_t keycode_to_modifier (uint16_t keycode, uint8_t locale)
Mask the keycode to get the modifiers, step 5.
This method masks out all keycode bits and returns the direct HID modifier byte, which can be used in HID reports.
Parameters
keycode Keycode from other parsing methods
locale Currently used keyboard layout
Returns
8-bit keycode for HID
Todo:
Add remaining modifier keys (according to keylayouts.h, for example KEY_GUI)
Definition at line 2026 of file keyboard.c.
Referenced by doKeyboardParsing(), and parse_for_keycode().
parse_for_keycode()
uint8_t parse_for_keycode (uint8_t inputdata, uint8_t locale, uint8_t * keycode_modifier, uint8_t * deadkey_first_keycode)
Parse an incoming byte for a keycode.
This method parses one incoming byte for the given locale. It returns 0 if there is no keycode or another byte is needed (Unicode input). If a modifier is needed the given modifier byte is updated.
See also
keyboard_layouts
Parameters
inputdata Input byte to parse for a keycode
locale Use this keyboard layout
keycode_modifier If a modifier is needed, it will be written here
deadkey_first_keycode If a deadkey stroke is needed, it will be written here
Returns
0 if another byte is needed or no keycode is found; the keycode otherwise
Definition at line 2051 of file keyboard.c.
Referenced by get_keycode(), halBleTaskKeyboardPress(), and halBleTaskKeyboardRelease().
parseIdentifierToKeycode()
uint16_t parseIdentifierToKeycode (char * keyidentifier)
Parse a key identifier to a keycode.
This method is used to parse a key identifier (e.g., KEY_A) to a keycode which is used for a task_keyboard config.
Warning
If you use key identifiers, no keyboard locale is taken into account!
Parameters
keyidentifier Key identifier string
Returns
Keycode if found, 0 otherwise
See also
parseKeycodeToIdentifier
Definition at line 2169 of file keyboard.c.
Referenced by doKeyboardParsing().
parseKeycodeToIdentifier()
uint16_t parseKeycodeToIdentifier (uint16_t keycode, char * buffer, uint8_t buf_len)
Parse a keycode to a key identifier.
This method is used to parse a key code to a key identifier which can be used for sending back the task_keyboard config.
Warning
If you use key identifiers, no keyboard locale is taken into account!
Parameters
keycode Keycode to be parsed to a key identifier
buffer Char buffer where the key identifier is saved to
buf_len Length of buffer
Returns
1 if found, 2 if buffer is too small, 0 if no key identifier was found
See also
parseIdentifierToKeycode
Definition at line 2349 of file keyboard.c.
Referenced by task_keyboard_getAT().
remove_keycode()
uint8_t remove_keycode (uint8_t keycode, uint8_t * keycode_arr)
Remove a keycode from the given HID keycode array.
Note
The size of the keycode_arr parameter MUST be 6
Parameters
keycode Keycode to be removed
keycode_arr Keycode to remove this keycode from
Returns
0 if the keycode was removed, 1 if the keycode was not in the array
Definition at line 2109 of file keyboard.c.
Referenced by halBleTaskKeyboardRelease(), and halSerialTaskKeyboardRelease().
unicode_to_keycode()
uint16_t unicode_to_keycode (uint16_t cpoint, uint8_t locale)
Parse a decoded code point to a keycode, step 2.
This method parses a fully assembled code point to a keycode. To get a fully assembled cpoint, use the method parse_for_keycode.
See also
parse_for_keycode
keycodes_masks
keycodes_ascii
keycodes_iso_8859_1
Parameters
cpoint Fully assembled ASCII or ISO8859-1 code point
locale Currently used keyboard layout
Returns
0 if no keycode was found (invalid cpoint), the keycode otherwise
Definition at line 1925 of file keyboard.c.
Referenced by doKeyboardParsing(), and parse_for_keycode().
Variable Documentation
deadkey_USINT
const uint16_t deadkey_USINT[2][5]
Defines the bits and deadkeys itself for all available deadkeys for US_INTERNATIONAL. All other layouts have an equal array. If a layout does not have deadkeys at all, this array is of [2][1] dimension and initialised with {0,0}.
Definition at line 78 of file keyboard.c.
keycodes_ascii
const uint16_t keycodes_ascii[][96]
Array of all keycodes for ASCII symbols.
The array offset is on the one hand the locale as it is defined in keyboard_layouts and on the other hand the ASCII number - 0x20. –> ASCII 0x22 character ('2') is for US_ENGLISH on position [0][2]
See also
keyboard_layouts
Warning
Locale offset is different to the deadkey arrays, we have LAYOUT_US_ENGLISH here.
Definition at line 470 of file keyboard.c.
Referenced by unicode_to_keycode().
keycodes_deadkey
const uint16_t* keycodes_deadkey[]
Initial value:
= {
  deadkey_USINT[1],
  deadkey_DE[1],
  deadkey_DEMAC[1],
  deadkey_CAFR[1],
  deadkey_CAINT[1],
  deadkey_UK[1],
  deadkey_FI[1],
  deadkey_FR[1],
  deadkey_DK[1],
  deadkey_NW[1],
  deadkey_SW[1],
  deadkey_ES[1],
  deadkey_PT[1],
  deadkey_IT[1],
  deadkey_PTBR[1],
  deadkey_FRBE[1],
  deadkey_DESW[1],
  deadkey_FRSW[1],
  deadkey_ESLAT[1],
  deadkey_IR[1],
  deadkey_IC[1],
  deadkey_TK[1],
  deadkey_CZ[1],
  deadkey_SR[1]
}
Array of pointers to a deadkey keycodes array for each locale.
We are using offset 1 from the deadkey_XXX array, because it contains the keycodes.
See also
deadkey_USINT (or any other language)
Warning
Locale offset is different here, because there is no LAYOUT_US_ENGLISH (no deadkeys at all)
Definition at line 411 of file keyboard.c.
Referenced by deadkey_to_keycode().
keycodes_deadkey_bits
const uint16_t* keycodes_deadkey_bits[]
Initial value:
= {
  deadkey_USINT[0],
  deadkey_DE[0],
  deadkey_DEMAC[0],
  deadkey_CAFR[0],
  deadkey_CAINT[0],
  deadkey_UK[0],
  deadkey_FI[0],
  deadkey_FR[0],
  deadkey_DK[0],
  deadkey_NW[0],
  deadkey_SW[0],
  deadkey_ES[0],
  deadkey_PT[0],
  deadkey_IT[0],
  deadkey_PTBR[0],
  deadkey_FRBE[0],
  deadkey_DESW[0],
  deadkey_FRSW[0],
  deadkey_ESLAT[0],
  deadkey_IR[0],
  deadkey_IC[0],
  deadkey_TK[0],
  deadkey_CZ[0],
  deadkey_SR[0]
}
Array of pointers to a deadkey bits array for each locale.
We are using offset 0 from the deadkey_XXX array, because it contains the bitmasks.
See also
deadkey_USINT (or any other language)
Warning
Locale offset is different here, because there is no LAYOUT_US_ENGLISH (no deadkeys at all)
Definition at line 374 of file keyboard.c.
Referenced by deadkey_to_keycode().
keycodes_iso_8859_1
const uint16_t keycodes_iso_8859_1[][96]
Array of all keycodes for ISO8859 (unicode) symbols/code points.
The array offset is on the one hand the locale as it is defined in keyboard_layouts and on the other hand the unicode number - 0xA0. –> unicode 0xA2 character is for US_INTERNATIONAL on position [0][2]
See also
keyboard_layouts
Warning
Locale offset is different to the ASCII array, we don't have LAYOUT_US_ENGLISH here.
Definition at line 1211 of file keyboard.c.
Referenced by unicode_to_keycode().
keycodes_masks
const uint16_t keycodes_masks[][5]
Defines all masks necessary for either getting modifiers or the keycode.
Definition at line 241 of file keyboard.c.
Referenced by deadkey_to_keycode(), keycode_to_modifier(), parse_for_keycode(), and unicode_to_keycode().