FLipMouse/FABI ESP32 firmware: /home/beni/sync/Projects/FH/FLipMouse-esp32/main/function_tasks/task_debouncer.c File Reference
task_debouncer.c File Reference
CONTINOUS TASK - This file contains the task implementation for the virtual button debouncer.
#include "task_debouncer.h"
Data Structures
struct debouncer_cfg
Timer config struct This struct is used to control one timer for debouncing.
Macros
#define LOG_TAG "task_debouncer"
Tag for ESP_LOG logging.
#define LOG_LEVEL_DEBOUNCE ESP_LOG_INFO
Debouncer log level.
Typedefs
typedef struct debouncer_cfg debouncer_cfg_t
Timer config struct This struct is used to control one timer for debouncing.
Enumerations
enum debouncer_direction_t {
TIMER_IDLE, TIMER_PRESS, TIMER_RELEASE, TIMER_DEADTIME,
TIMER_ERROR
}
Debounce timer, current direction for this timer When a debounce timer is started, a parameter struct of type debouncer_param_t is used for starting this timer. It includes the given direction of the timer as it is defined here.
Functions
esp_err_t startTimer (debouncer_cfg_t *cfg, uint16_t debounceTime)
Start a timer with a given config and debounce time.
debouncer_direction_t isDebouncerActive (uint32_t virtualButton)
Look for a possibly running debouncing timer.
int cancelTimer (uint32_t virtualButton, uint8_t stop)
Cancel a possibly running debouncing timer.
void sendButtonLearn (uint32_t vb, vb_event_t press, generalConfig_t *cfg)
Send feedback on pressed buttons to host (for button learning)
void debouncerCallback (void *arg)
Timer callback for debouncing.
void task_debouncer (void *param)
Debouncing main task.
Variables
debouncer_cfg_t xTimers [VB_MAX]
Array of timer configs.
Detailed Description
CONTINOUS TASK - This file contains the task implementation for the virtual button debouncer.
This debouncer task (task_debouncer) waits for incoming events (of type raw_action_t)on the debouncer_in queue. If an incoming event is registered, a timer (esp_timer) will be started. On a finished debounce event, the corresponding event is sent to the system event loop.
The debouncing itself can be controlled via following variables (these settings are located in the global config):
Press debounce time
Release debounce time
Deadtime between two consecutive actions
If one of these values is set for one dedicated VB, it will be used. If there is no setting, the device's default will be used. If the there is no default setting for this device, a hardcoded debounce time of DEBOUNCETIME_MS is used.
Note
For each VB, a debouncer_cfg_t element will be used. The size of this array is determined by VB_MAX. Please set this define accordingly!
See also
VB_MAX
DEBOUNCETIME_MS
debouncer_in
raw_action_t
generalConfig_t
Definition in file task_debouncer.c.
Macro Definition Documentation
LOG_LEVEL_DEBOUNCE
#define LOG_LEVEL_DEBOUNCE ESP_LOG_INFO
Debouncer log level.
Definition at line 62 of file task_debouncer.c.
Referenced by task_debouncer().
LOG_TAG
#define LOG_TAG "task_debouncer"
Tag for ESP_LOG logging.
Definition at line 59 of file task_debouncer.c.
Referenced by cancelTimer(), debouncerCallback(), startTimer(), and task_debouncer().
Typedef Documentation
debouncer_cfg_t
typedef struct debouncer_cfg debouncer_cfg_t
Timer config struct This struct is used to control one timer for debouncing.
Enumeration Type Documentation
debouncer_direction_t
enum debouncer_direction_t
Debounce timer, current direction for this timer When a debounce timer is started, a parameter struct of type debouncer_param_t is used for starting this timer. It includes the given direction of the timer as it is defined here.
See also
debouncer_param_t
Enumerator
TIMER_IDLE
TIMER_PRESS
Timer is in idle and should not be triggering.
TIMER_RELEASE
Debouncer timer is active for a press event.
TIMER_DEADTIME
Debouncer timer is active for a release event.
TIMER_ERROR
Debouncer timer is active for a deadtime between next event (lock-out)
We have an error. Might be a virtualbutton out of range.
Definition at line 70 of file task_debouncer.c.
Function Documentation
cancelTimer()
int cancelTimer (uint32_t virtualButton, uint8_t stop)
Cancel a possibly running debouncing timer.
This method does a look-up in the xTimers array to find a running timer with the given VB number (used as timer id) and cancel it
Parameters
virtualButton Number of VB to look for a running timer, use VB_MAX to cancel all timers.
stop Should we stop the timer before deleting (if set != 0)
Returns
Array offset where this running timer was found & canceled,\ -1 if no timer was found (or all were cleared)
Note
If VB_MAX is given, all timers are canceled.
Definition at line 139 of file task_debouncer.c.
Referenced by debouncerCallback(), startTimer(), and task_debouncer().
debouncerCallback()
void debouncerCallback (void * arg)
Timer callback for debouncing.
This callback is executed on an expired debounce timer. Depending on the timer functionality (determined by the argument struct), either the PRESS or RELEASE events are sent via the event loop.
See also
debouncer_cfg_t
Todo:
Add/test the deadtime functionality here
Parameters
arg Timer argument, of type debouncer_cfg_t
Todo:
Maybe we can replace this switch statement with a more flexible solution.
Definition at line 218 of file task_debouncer.c.
Referenced by startTimer().
isDebouncerActive()
debouncer_direction_t isDebouncerActive (uint32_t virtualButton)
Look for a possibly running debouncing timer.
This method does a look-up in the xTimers array to return the timer status for the given VB number (stored within the debouncer_cfg_t struct).
See also
debouncer_cfg_t
Parameters
virtualButton Number of VB to look for a running timer
Returns
Timer direction of this VB.
Definition at line 121 of file task_debouncer.c.
Referenced by startTimer(), and task_debouncer().
sendButtonLearn()
void sendButtonLearn (uint32_t vb, vb_event_t press, generalConfig_t * cfg)
Send feedback on pressed buttons to host (for button learning)
This method sends back to the host which buttons are pressed, if enabled. Can be enabled by "AT BL 1" and disabled by "AT BL 0".
Parameters
vb Virtual button which was triggered
press See vb_event_t
cfg Pointer to current config
See also
generalConfig_t.button_learn
vb_event_t
Definition at line 189 of file task_debouncer.c.
Referenced by debouncerCallback().
startTimer()
esp_err_t startTimer (debouncer_cfg_t * cfg, uint16_t debounceTime)
Start a timer with a given config and debounce time.
Parameters
cfg Config for the timer to be started
debounceTime Timeout for the new timer, unit: [ms]
Returns
ESP_OK on success, ESP_FAIL if timer cannot be started
Definition at line 315 of file task_debouncer.c.
Referenced by debouncerCallback(), and task_debouncer().
task_debouncer()
void task_debouncer (void * param)
Debouncing main task.
This task is pending on raw actions, sent to the debouncer_in queue. If there is a raw action posted, this task either:
Starts a new timer (no timer is running)
Cancels a running timer (timer is running in the opposite debouncer direction)
Does nothing (timer is already running in the same direction)
See also
DEBOUNCERCHANNELS
DEBOUNCE_RESOLUTION_MS
xTimers
debouncerCallback
Todo:
Add anti-tremor & deadtime functionality
Note
We send here an additional release, just to be sure to release any actions (avoiding sticky actions for keys...)
I think we should cancel only in the event of a set anti-tremor time. Otherwise we might loose e.g., key release events -> sticky keys...
Definition at line 366 of file task_debouncer.c.
Referenced by app_main().
Variable Documentation
xTimers
debouncer_cfg_t xTimers[VB_MAX]
Array of timer configs.
This array contains all possible running timer handles. A maximum of DEBOUNCERCHANNELS timers can be concurrently running.
See also
DEBOUNCERCHANNELS
debouncer_cfg_t
Definition at line 110 of file task_debouncer.c.