FLipMouse/FABI ESP32 firmware: /home/beni/Projects/FLipMouse-esp32/main/function_tasks/task_mqtt.h File Reference
task_mqtt.h File Reference
CONTINOUS TASK - MQTT handling.
#include <freertos/FreeRTOS.h>
#include <freertos/event_groups.h>
#include <freertos/queue.h>
#include <freertos/task.h>
#include <esp_log.h>
#include "common.h"
#include <inttypes.h>
#include "hal_storage.h"
#include "lwip/sockets.h"
#include "lwip/dns.h"
#include "lwip/netdb.h"
#include "mqtt_client.h"
#include "esp_err.h"
#include "esp_wifi.h"
#include "esp_event_loop.h"
#include "esp_event_legacy.h"
#include "nvs.h"
#include "nvs_flash.h"
Macros
#define TASK_MQTT_STACKSIZE 4096
Stack size for the MQTT task.
#define MQTT_DELIMITER ':'
Default mqtt delimter character.
Functions
esp_err_t taskMQTTInit (void)
Init the MQTT task and the wifi.
esp_err_t taskMQTTDeInit (void)
Deinit the MQTT task and the wifi.
esp_err_t taskMQTTPublish (char *topic_payload)
Publish data via MQTT.
Detailed Description
CONTINOUS TASK - MQTT handling.
This module is used for connecting the FLipMouse/FABI to a MQTT broker.
Warning
Please note, only one WiFi mode is possible: either this device operates in AP mode and serves the webGUI (see task_webgui.h) OR it operates in station mode, connects to a given Wifi and transmits data via MQTT (if enabled)
Note
Initialise this module only if a MQTT command is used in the configuration.
See also
task_webgui.h
Definition in file task_mqtt.h.
Macro Definition Documentation
MQTT_DELIMITER
#define MQTT_DELIMITER ':'
Default mqtt delimter character.
Note
This is the default character, if no other is set via "AT MS". It is used to split the "AT MQ" string into topic and payload.
Definition at line 69 of file task_mqtt.h.
TASK_MQTT_STACKSIZE
#define TASK_MQTT_STACKSIZE 4096
Stack size for the MQTT task.
Definition at line 64 of file task_mqtt.h.
Function Documentation
taskMQTTDeInit()
esp_err_t taskMQTTDeInit (void)
Deinit the MQTT task and the wifi.
This function deactives MQTT/WiFi in station mode. It is necessary if the webGUI should be switched on.
Returns
ESP_OK on success, ESP_FAIL otherwise
Definition at line 251 of file task_mqtt.c.
taskMQTTInit()
esp_err_t taskMQTTInit (void)
Init the MQTT task and the wifi.
This init function initializes the wifi in station mode and the MQTT task.
See also
NVS_STATIONNAME
NVS_STATIONPW
NVS_MQTT_BROKER
Note
Please activate only if necessary by any configuration.
Returns
ESP_OK on success, ESP_FAIL otherwise
MQTT broker host name/ip
Definition at line 144 of file task_mqtt.c.
Referenced by taskMQTTPublish().
taskMQTTPublish()
esp_err_t taskMQTTPublish (char * topic_payload)
Publish data via MQTT.
This function publishes the given data. The parameter topic_payload will be split into the topic name and the corresponding payload to publish. The splitting is done by the currently set MQTT delimiter character, which can be modified with "AT MS". MQTT_DELIMITER will be used if no other character is set.
See also
MQTT_DELIMITER
Returns
ESP_OK on success, ESP_FAIL otherwise
Definition at line 281 of file task_mqtt.c.
Referenced by cmdMq(), and handler_vb().