FLipMouse/FABI ESP32 firmware: /home/beni/sync/Projects/FH/FLipMouse-esp32/main/function_tasks/task_infrared.c File Reference
task_infrared.c File Reference
FUNCTIONAL TASK - Infrared remotes.
#include "task_infrared.h"
Macros
#define LOG_TAG "task_IR"
Logging tag for this module.
Functions
void task_infrared (taskInfraredConfig_t *param)
FUNCTIONAL TASK - Infrared command sending.
esp_err_t infrared_record (char *cmdName)
Trigger an IR command recording.
esp_err_t infrared_set_edge_timeout (uint8_t timeout)
Set the time between two IR edges which will trigger the timeout (end of received command)
esp_err_t task_infrared_getAT (char *output, void *cfg)
Reverse Parsing - get AT command for IR VB.
Detailed Description
FUNCTIONAL TASK - Infrared remotes.
This module is used as functional task for sending pre-recorded infrared commands. Recording of an infrared command is done here, but NOT within a functional task.
Pinning and low-level interfacing for infrared is done in hal_io.c.
See also
hal_io.c
task_infrared
VB_SINGLESHOT
Definition in file task_infrared.c.
Macro Definition Documentation
LOG_TAG
#define LOG_TAG "task_IR"
Logging tag for this module.
Definition at line 39 of file task_infrared.c.
Referenced by infrared_record(), and task_infrared().
Function Documentation
infrared_record()
esp_err_t infrared_record (char * cmdName)
Trigger an IR command recording.
This method is used to record one infrared command. It will block until either the timeout is reached or a command is received. The command is stored vial hal_storage.
See also
halStorageStoreIR
TASK_HAL_IR_RECV_TIMEOUT
Parameters
cmdName Name of command which will be used to store.
Returns
ESP_OK if command was stored, ESP_FAIL otherwise (timeout)
Definition at line 149 of file task_infrared.c.
Referenced by doInfraredParsing().
infrared_set_edge_timeout()
esp_err_t infrared_set_edge_timeout (uint8_t timeout)
Set the time between two IR edges which will trigger the timeout (end of received command)
This method is used to set the timeout between two edges which is used to trigger the timeout, therefore the finished signal for an IR command recording.
See also
infrared_trigger_record
generalConfig_t
Parameters
timeout Timeout in [ms], 2-100
Returns
ESP_OK if parameter is set, ESP_FAIL otherwise (out of range)
Definition at line 229 of file task_infrared.c.
task_infrared()
void task_infrared (taskInfraredConfig_t * param)
FUNCTIONAL TASK - Infrared command sending.
This task is used to trigger an IR command on a VB action. The IR command which should be sent is identified by a name.
See also
taskInfraredConfig_t
Parameters
param Task config
See also
VB_SINGLESHOT
Definition at line 51 of file task_infrared.c.
Referenced by doInfraredParsing().
task_infrared_getAT()
esp_err_t task_infrared_getAT (char * output, void * cfg)
Reverse Parsing - get AT command for IR VB.
This function parses the current configuration of a virtual button to an AT command used to print the configuration.
Parameters
output Output string, where the full AT command will be stored
cfg Pointer to current infrared configuration, used to parse.
Returns
ESP_OK if everything went fine, ESP_FAIL otherwise
Definition at line 249 of file task_infrared.c.
Referenced by printAllSlots().