FLipMouse/FABI ESP32 firmware: /home/beni/sync/Projects/FH/FLipMouse-esp32/main/function_tasks/task_commands.c File Reference
task_commands.c File Reference
CONTINOUS TASK - Main command parser for serial AT commands.
#include "task_commands.h"
Macros
#define LOG_TAG "cmdparser"
#define LOG_LEVEL_CMDPARSER ESP_LOG_INFO
Set a global log limit for this file.
#define CMD_TARGET_TYPE generalConfig_t
Functions
void sendErrorBack (const char *extrainfo)
void printAllSlots (uint8_t printconfig)
Print the current slot configurations (general settings + VBs)
void storeSlot (char *slotname)
Save current config to flash.
static int checkqueues (void)
void sendHIDCmd (hid_cmd_t *sendCmd, uint8_t vb, uint8_t *atorig, uint8_t replace)
Helper to route a HID cmd either directly to queue or add it to the list.
void sendVBCmd (vb_cmd_t *sendCmd, uint8_t vb, uint8_t *atorig, uint8_t replace)
Helper to route a VB cmd either directly to queue or add it to the list.
esp_err_t cmdId (char *orig, void *p1, void *p2)
esp_err_t cmdBm (char *orig, void *p1, void *p2)
esp_err_t cmdMa (char *orig, void *p1, void *p2)
esp_err_t cmdWa (char *orig, void *p1, void *p2)
esp_err_t cmdRo (char *orig, void *p1, void *p2)
esp_err_t cmdBt (char *orig, void *p1, void *p2)
esp_err_t cmdTt (char *orig, void *p1, void *p2)
esp_err_t cmdAp (char *orig, void *p1, void *p2)
esp_err_t cmdAr (char *orig, void *p1, void *p2)
esp_err_t cmdAi (char *orig, void *p1, void *p2)
esp_err_t cmdFr (char *orig, void *p1, void *p2)
esp_err_t cmdPw (char *orig, void *p1, void *p2)
esp_err_t cmdFw (char *orig, void *p1, void *p2)
esp_err_t cmdCl (char *orig, void *p1, void *p2)
esp_err_t cmdCr (char *orig, void *p1, void *p2)
esp_err_t cmdCm (char *orig, void *p1, void *p2)
esp_err_t cmdCd (char *orig, void *p1, void *p2)
esp_err_t cmdHl (char *orig, void *p1, void *p2)
esp_err_t cmdHr (char *orig, void *p1, void *p2)
esp_err_t cmdHm (char *orig, void *p1, void *p2)
esp_err_t cmdRl (char *orig, void *p1, void *p2)
esp_err_t cmdRr (char *orig, void *p1, void *p2)
esp_err_t cmdRm (char *orig, void *p1, void *p2)
esp_err_t cmdTl (char *orig, void *p1, void *p2)
esp_err_t cmdTr (char *orig, void *p1, void *p2)
esp_err_t cmdTm (char *orig, void *p1, void *p2)
esp_err_t cmdWu (char *orig, void *p1, void *p2)
esp_err_t cmdWd (char *orig, void *p1, void *p2)
esp_err_t cmdWs (char *orig, void *p1, void *p2)
esp_err_t cmdMx (char *orig, void *p1, void *p2)
esp_err_t cmdMy (char *orig, void *p1, void *p2)
esp_err_t keyboard_helper_parsekeycode (char t, uint8_t *buf)
esp_err_t cmdKw (char *orig, void *p1, void *p2)
esp_err_t cmdKp (char *orig, void *p1, void *p2)
esp_err_t cmdKh (char *orig, void *p1, void *p2)
esp_err_t cmdKr (char *orig, void *p1, void *p2)
esp_err_t cmdKt (char *orig, void *p1, void *p2)
esp_err_t cmdRa (char *orig, void *p1, void *p2)
esp_err_t cmdSa (char *orig, void *p1, void *p2)
esp_err_t cmdLo (char *orig, void *p1, void *p2)
esp_err_t cmdLa (char *orig, void *p1, void *p2)
esp_err_t cmdLi (char *orig, void *p1, void *p2)
esp_err_t cmdNe (char *orig, void *p1, void *p2)
esp_err_t cmdDe (char *orig, void *p1, void *p2)
esp_err_t cmdDl (char *orig, void *p1, void *p2)
esp_err_t cmdDn (char *orig, void *p1, void *p2)
esp_err_t cmdNc (char *orig, void *p1, void *p2)
esp_err_t cmdMm (char *orig, void *p1, void *p2)
esp_err_t cmdSw (char *orig, void *p1, void *p2)
esp_err_t cmdSr (char *orig, void *p1, void *p2)
esp_err_t cmdEr (char *orig, void *p1, void *p2)
esp_err_t cmdCa (char *orig, void *p1, void *p2)
void joystick_helper_axis (uint8_t val1, uint8_t val2, uint16_t v)
esp_err_t cmdJx (char *orig, void *p1, void *p2)
esp_err_t cmdJy (char *orig, void *p1, void *p2)
esp_err_t cmdJz (char *orig, void *p1, void *p2)
esp_err_t cmdJt (char *orig, void *p1, void *p2)
esp_err_t cmdJs (char *orig, void *p1, void *p2)
esp_err_t cmdJu (char *orig, void *p1, void *p2)
esp_err_t cmdJp (char *orig, void *p1, void *p2)
esp_err_t cmdJc (char *orig, void *p1, void *p2)
esp_err_t cmdJr (char *orig, void *p1, void *p2)
esp_err_t cmdJh (char *orig, void *p1, void *p2)
esp_err_t cmdIr (char *orig, void *p1, void *p2)
esp_err_t cmdIp (char *orig, void *p1, void *p2)
esp_err_t cmdIh (char *orig, void *p1, void *p2)
esp_err_t cmdIc (char *orig, void *p1, void *p2)
esp_err_t cmdIw (char *orig, void *p1, void *p2)
esp_err_t cmdIl (char *orig, void *p1, void *p2)
esp_err_t cmdIx (char *orig, void *p1, void *p2)
void task_commands (void *params)
esp_err_t taskCommandsInit (void)
Init the command parser.
esp_err_t taskCommandsRestart (void)
Restart the command parser task.
cmd_retval cmdParser (char *data, generalConfig_t *target)
Main parser.
Variables
hid_cmd_t joystick
Global HID command for joystick This command is set by the command handlers. If one field was modified by a handler, it will be sent to task_hid.
hid_cmd_t joystickR
Global release HID command for joystick This command is set by the command handlers. If one field was modified by a handler, it will be sent to task_hid.
hid_cmd_t mouse
Global HID command for mouse This command is set by the command handlers. If one field was modified by a handler, it will be sent to task_hid.
hid_cmd_t general
Global HID command for general data transmitted via the HID interface. This command is set by the command handlers. If one field was modified by a handler, it will be sent to task_hid.
hid_cmd_t mouseR
Global release HID command for mouse This command is set by the command handlers. If one field was modified by a handler, it will be sent to task_hid.
hid_cmd_t mouseD
Global HID command for mouse - 2nd action This command is set by the command handlers. This one is just used for double click. If one field was modified by a handler, it will be sent to task_hid.
hid_cmd_t keyboard
Global HID command for keyboard This command is set by the command handlers. If one field was modified by a handler, it will be sent to task_hid.
hid_cmd_t keyboardR
Global release HID command for keyboard This command is set by the command handlers. If one field was modified by a handler, it will be sent to task_hid.
vb_cmd_t vbaction
Global VB command.
generalConfig_t * currentCfg = NULL
Pointer to current configuration.
static TaskHandle_t currentCommandTask = NULL
uint8_t requestUpdate = 0
uint8_t requestVBUpdate = VB_SINGLESHOT
Currently used virtual button number.
uint8_t requestBM = 0
Currently used virtual button number.
const onecmd_t commands []
Detailed Description
CONTINOUS TASK - Main command parser for serial AT commands.
This module is used to parse any incoming serial data from hal_serial for valid AT commands. If a valid command is detected, the corresponding action is triggered (mostly by invoking task_hid or task_vb via a hid_cmd_t or vb_cmd_t).
By issueing an AT BM command, the next issued AT command will be assigned to a virtual button. This is done via setting the requestVBUpdate variable to the VB number. One time only commands (without AT BM) are defined as VB==VB_SINGLESHOT
See also
VB_SINGLESHOT
hal_serial
atcmd_api
hid_cmd_t
vb_cmd_t
Note
Currently we are using unicode_to_keycode, because terminal programs use it this way. For supporting unicode keystreams (UTF-8), the method parse_for_keycode needs to be used
The command parser itself is based on the cmd_parser project. See: <addlinkhere>
Definition in file task_commands.c.
Macro Definition Documentation
CMD_TARGET_TYPE
#define CMD_TARGET_TYPE generalConfig_t
Definition at line 914 of file task_commands.c.
Referenced by cmdParser().
LOG_LEVEL_CMDPARSER
#define LOG_LEVEL_CMDPARSER ESP_LOG_INFO
Set a global log limit for this file.
Definition at line 50 of file task_commands.c.
Referenced by taskCommandsInit().
LOG_TAG
#define LOG_TAG "cmdparser"
Tag for ESP_LOG logging
Definition at line 48 of file task_commands.c.
Referenced by cmdDe(), cmdDl(), cmdDn(), cmdIc(), cmdIl(), cmdIr(), cmdIw(), cmdIx(), cmdKw(), keyboard_helper_parsekeycode(), printAllSlots(), sendErrorBack(), sendHIDCmd(), sendVBCmd(), storeSlot(), task_commands(), and taskCommandsInit().
Function Documentation
checkqueues()
static int checkqueues (void) static
just check all queues if they are initialized
Returns
0 on uninitialized queues, 1 if all are initialized
Definition at line 161 of file task_commands.c.
Referenced by task_commands().
cmdAi()
esp_err_t cmdAi (char * orig, void * p1, void * p2)
Definition at line 300 of file task_commands.c.
cmdAp()
esp_err_t cmdAp (char * orig, void * p1, void * p2)
Definition at line 288 of file task_commands.c.
cmdAr()
esp_err_t cmdAr (char * orig, void * p1, void * p2)
Definition at line 294 of file task_commands.c.
cmdBm()
esp_err_t cmdBm (char * orig, void * p1, void * p2)
Definition at line 246 of file task_commands.c.
cmdBt()
esp_err_t cmdBt (char * orig, void * p1, void * p2)
Definition at line 277 of file task_commands.c.
cmdCa()
esp_err_t cmdCa (char * orig, void * p1, void * p2)
Definition at line 727 of file task_commands.c.
cmdCd()
esp_err_t cmdCd (char * orig, void * p1, void * p2)
Definition at line 335 of file task_commands.c.
cmdCl()
esp_err_t cmdCl (char * orig, void * p1, void * p2)
Definition at line 326 of file task_commands.c.
cmdCm()
esp_err_t cmdCm (char * orig, void * p1, void * p2)
Definition at line 332 of file task_commands.c.
cmdCr()
esp_err_t cmdCr (char * orig, void * p1, void * p2)
Definition at line 329 of file task_commands.c.
cmdDe()
esp_err_t cmdDe (char * orig, void * p1, void * p2)
Definition at line 652 of file task_commands.c.
cmdDl()
esp_err_t cmdDl (char * orig, void * p1, void * p2)
Definition at line 661 of file task_commands.c.
cmdDn()
esp_err_t cmdDn (char * orig, void * p1, void * p2)
Definition at line 670 of file task_commands.c.
cmdEr()
esp_err_t cmdEr (char * orig, void * p1, void * p2)
Definition at line 722 of file task_commands.c.
cmdFr()
esp_err_t cmdFr (char * orig, void * p1, void * p2)
Definition at line 306 of file task_commands.c.
cmdFw()
esp_err_t cmdFw (char * orig, void * p1, void * p2)
Definition at line 320 of file task_commands.c.
cmdHl()
esp_err_t cmdHl (char * orig, void * p1, void * p2)
Definition at line 339 of file task_commands.c.
cmdHm()
esp_err_t cmdHm (char * orig, void * p1, void * p2)
Definition at line 347 of file task_commands.c.
cmdHr()
esp_err_t cmdHr (char * orig, void * p1, void * p2)
Definition at line 343 of file task_commands.c.
cmdIc()
esp_err_t cmdIc (char * orig, void * p1, void * p2)
Definition at line 825 of file task_commands.c.
cmdId()
esp_err_t cmdId (char * orig, void * p1, void * p2)
Definition at line 242 of file task_commands.c.
cmdIh()
esp_err_t cmdIh (char * orig, void * p1, void * p2)
Definition at line 822 of file task_commands.c.
cmdIl()
esp_err_t cmdIl (char * orig, void * p1, void * p2)
Definition at line 861 of file task_commands.c.
cmdIp()
esp_err_t cmdIp (char * orig, void * p1, void * p2)
Definition at line 810 of file task_commands.c.
cmdIr()
esp_err_t cmdIr (char * orig, void * p1, void * p2)
Definition at line 802 of file task_commands.c.
cmdIw()
esp_err_t cmdIw (char * orig, void * p1, void * p2)
Definition at line 847 of file task_commands.c.
cmdIx()
esp_err_t cmdIx (char * orig, void * p1, void * p2)
Definition at line 899 of file task_commands.c.
cmdJc()
esp_err_t cmdJc (char * orig, void * p1, void * p2)
Definition at line 786 of file task_commands.c.
cmdJh()
esp_err_t cmdJh (char * orig, void * p1, void * p2)
Definition at line 796 of file task_commands.c.
cmdJp()
esp_err_t cmdJp (char * orig, void * p1, void * p2)
Definition at line 781 of file task_commands.c.
cmdJr()
esp_err_t cmdJr (char * orig, void * p1, void * p2)
Definition at line 791 of file task_commands.c.
cmdJs()
esp_err_t cmdJs (char * orig, void * p1, void * p2)
Definition at line 769 of file task_commands.c.
cmdJt()
esp_err_t cmdJt (char * orig, void * p1, void * p2)
Definition at line 763 of file task_commands.c.
cmdJu()
esp_err_t cmdJu (char * orig, void * p1, void * p2)
Definition at line 775 of file task_commands.c.
cmdJx()
esp_err_t cmdJx (char * orig, void * p1, void * p2)
Definition at line 745 of file task_commands.c.
cmdJy()
esp_err_t cmdJy (char * orig, void * p1, void * p2)
Definition at line 751 of file task_commands.c.
cmdJz()
esp_err_t cmdJz (char * orig, void * p1, void * p2)
Definition at line 757 of file task_commands.c.
cmdKh()
esp_err_t cmdKh (char * orig, void * p1, void * p2)
Definition at line 608 of file task_commands.c.
cmdKp()
esp_err_t cmdKp (char * orig, void * p1, void * p2)
Definition at line 606 of file task_commands.c.
cmdKr()
esp_err_t cmdKr (char * orig, void * p1, void * p2)
Definition at line 610 of file task_commands.c.
cmdKt()
esp_err_t cmdKt (char * orig, void * p1, void * p2)
Definition at line 612 of file task_commands.c.
cmdKw()
esp_err_t cmdKw (char * orig, void * p1, void * p2)
Definition at line 521 of file task_commands.c.
cmdLa()
esp_err_t cmdLa (char * orig, void * p1, void * p2)
Definition at line 634 of file task_commands.c.