FLipMouse/FABI ESP32 firmware: /home/beni/sync/Projects/FH/FLipMouse-esp32/main/function_tasks/task_macros.c File Reference
task_macros.c File Reference
FUNCTIONAL TASK - Execute macros.
#include "task_macros.h"
Macros
#define LOG_TAG "macro"
Logging tag for this module.
Functions
void task_macro (taskMacrosConfig_t *param)
FUNCTIONAL TASK - Macro execution.
esp_err_t task_macro_getAT (char *output, void *cfg)
Reverse Parsing - get AT command for macro VB.
Detailed Description
FUNCTIONAL TASK - Execute macros.
This module is used as functional task for sending macros to the command parser.
Macros in context of FLipMouse/FABI are a string of concatenated AT commands, equal to normal AT commands sent by the host.
Note
AT command separation is done by a semicolon (';')
Warning
If you want to write the semicolon within a macro, use AT KP with the corresponding keycode!
See also
task_macros
VB_SINGLESHOT
Definition in file task_macros.c.
Macro Definition Documentation
LOG_TAG
#define LOG_TAG "macro"
Logging tag for this module.
Definition at line 39 of file task_macros.c.
Referenced by task_macro().
Function Documentation
task_macro()
void task_macro (taskMacrosConfig_t * param)
FUNCTIONAL TASK - Macro execution.
This task is used to trigger macro on a VB action.
See also
taskMacrosConfig_t
Parameters
param Task config
See also
VB_SINGLESHOT
Definition at line 50 of file task_macros.c.
Referenced by configSwitcherTask(), and doMacroParsing().
task_macro_getAT()
esp_err_t task_macro_getAT (char * output, void * cfg)
Reverse Parsing - get AT command for macro VB.
This function parses the current configuration of a virtual button to an AT command used to print the configuration.
Parameters
output Output string, where the full AT command will be stored
cfg Pointer to current macro configuration, used to parse.
Returns
ESP_OK if everything went fine, ESP_FAIL otherwise
Definition at line 196 of file task_macros.c.
Referenced by printAllSlots().