FLipMouse/FABI ESP32 firmware: /home/beni/sync/Projects/FH/FLipMouse-esp32/main/function_tasks/task_webgui.h File Reference
task_webgui.h File Reference
CONTINOUS TASK - Web server & WebGUI handling.
#include <freertos/FreeRTOS.h>
#include <freertos/event_groups.h>
#include <freertos/queue.h>
#include <freertos/task.h>
#include <esp_log.h>
#include "common.h"
#include <inttypes.h>
#include "esp_wifi.h"
#include "esp_event_loop.h"
#include "nvs.h"
#include "nvs_flash.h"
#include "esp_partition.h"
#include "esp_err.h"
#include "esp_vfs.h"
#include "esp_vfs_fat.h"
#include "lwip/api.h"
#include "lwip/err.h"
#include "lwip/netdb.h"
#include "captdns.h"
#include "websocket.h"
Macros
#define TASK_WEBGUI_WEBSOCKET_STACKSIZE 4096
Stack size for websocket server task.
#define TASK_WEBGUI_SERVER_STACKSIZE 4096
Stack size for web server task.
#define TASK_WEBGUI_WSPORT 1804
Websocket port.
Functions
esp_err_t taskWebGUIInit (void)
Init the web / DNS server and the web gui.
esp_err_t taskWebGUIEnDisable (int onoff, bool fromISR)
En- or Disable WiFi interface.
Detailed Description
CONTINOUS TASK - Web server & WebGUI handling.
This module is used to serve the web- & DNS server for captive portal mode and the web configuration GUI.
In addition, AT commands are sent to the command parser, the same way as if they would be sent by any host configuration software. In this mode feedback (which is usually sent to the serial interface) is sent back to the webgui for parsing in JS.
See also
hal_serial
task_commands
atcmd_api
Definition in file task_webgui.h.
Macro Definition Documentation
TASK_WEBGUI_SERVER_STACKSIZE
#define TASK_WEBGUI_SERVER_STACKSIZE 4096
Stack size for web server task.
Definition at line 70 of file task_webgui.h.
Referenced by taskWebGUIInit().
TASK_WEBGUI_WEBSOCKET_STACKSIZE
#define TASK_WEBGUI_WEBSOCKET_STACKSIZE 4096
Stack size for websocket server task.
Definition at line 67 of file task_webgui.h.
Referenced by wifiEnDisable().
TASK_WEBGUI_WSPORT
#define TASK_WEBGUI_WSPORT 1804
Websocket port.
Definition at line 73 of file task_webgui.h.
Referenced by ws_server().
Function Documentation
taskWebGUIEnDisable()
esp_err_t taskWebGUIEnDisable (int onoff, bool fromISR)
En- or Disable WiFi interface.
This method is used to enable or disable the wifi interface. In order to provide a safe FLipMouse/FABI device, the Wifi hotspot is for configuration purposes only. Therefore, an enabled Wifi hotspot will be automatically disabled within a defined time (see WIFI_OFF_TIME) after the last client was disconnected. In addition, other parts of the software might disable the Wifi prior to the automatic disconnect.
Note
Calling this method prior to initializing wifi with taskWebGUIInit will result in an error!
Returns
ESP_OK on success, ESP_FAIL otherwise
Parameters
onoff If != 0, switch on WiFi, switch off if 0.
fromISR Set to != 0 if this function is called from ISR context. Otherwise a reset will happen.
See also
WIFI_OFF_TIME
Definition at line 575 of file task_webgui.c.
Referenced by switch_radio(), and wifi_timer_cb().
taskWebGUIInit()
esp_err_t taskWebGUIInit (void)
Init the web / DNS server and the web gui.
This init function initializes the wifi, web server, dns server (captive portal) and the websocket.
The web page is served from FAT file system (same partition as config files) via the http_server task. Communication between web page and FLipMouse/FABI is done by a websocket, which is provided via the ws_server task.
Todo:
Activate/fix/test captive portal
Note
Wifi is not enabled by default (BLE has priority), see taskWebGUIEnDisable
IP Adress of the device is 192.168.10.1
See also
taskWebGUIEnDisable
CONFIG_AP_PASSWORD
NVS_WIFIPW
Returns
ESP_OK on success, ESP_FAIL otherwise
This init function initializes the wifi, web server, dns server (captive portal) and the websocket.
The web page is served from FAT file system (same partition as config files) via the http_server task. Communication between web page and FLipMouse/FABI is done by a websocket, which is provided via the ws_server task.
Todo:
Activate/fix/test captive portal
Note
Wifi is not enabled by default (BLE has priority), see taskWebGUIEnDisable
IP Adress of the device is 192.168.10.1
See also
taskWebGUIEnDisable
CONFIG_AP_PASSWORD
NVS_WIFIPW
Returns
ESP_OK on success, ESP_FAIL otherwise
Definition at line 739 of file task_webgui.c.
Referenced by app_main().