FLipMouse/FABI ESP32 firmware: /home/beni/sync/Projects/FH/FLipMouse-esp32/main/function_tasks/task_mouse.c File Reference
task_mouse.c File Reference
FUNCTIONAL TASK - mouse handling.
#include "task_mouse.h"
Macros
#define LOG_TAG "task_mouse"
Logging tag for this module.
Functions
uint8_t mouse_set_wheel (uint8_t steps)
Set current mouse wheel step size.
uint8_t mouse_get_wheel (void)
Get the current mouse wheel step size.
void task_mouse (taskMouseConfig_t *param)
FUNCTIONAL TASK - Trigger mouse action.
esp_err_t task_mouse_getAT (char *output, void *cfg)
Reverse Parsing - get AT command for mouse VB.
Detailed Description
FUNCTIONAL TASK - mouse handling.
This module is used as functional task for mouse control. It supports right/left/middle clicks (clicking, press&hold, release), left double clicks, mouse wheel and mouse X/Y actions. In addition, single shot is possible.
Note
Mouse control by mouthpiece is done in hal_adc!
See also
hal_adc
task_mouse
VB_SINGLESHOT
Definition in file task_mouse.c.
Macro Definition Documentation
LOG_TAG
#define LOG_TAG "task_mouse"
Logging tag for this module.
Definition at line 37 of file task_mouse.c.
Referenced by mouse_set_wheel(), task_mouse(), and task_mouse_getAT().
Function Documentation
mouse_get_wheel()
uint8_t mouse_get_wheel (void)
Get the current mouse wheel step size.
Returns
Current step size
Definition at line 62 of file task_mouse.c.
Referenced by doMouseParsing().
mouse_set_wheel()
uint8_t mouse_set_wheel (uint8_t steps)
Set current mouse wheel step size.
This method is used to set the current step size for the mouse wheel
Parameters
steps Amount of wheel steps, range: 0-126
Returns
0 if everything was fine, 1 if stepsize is out of range
Definition at line 44 of file task_mouse.c.
Referenced by doMouseParsing().
task_mouse()
void task_mouse (taskMouseConfig_t * param)
FUNCTIONAL TASK - Trigger mouse action.
This task is used to trigger a mouse action, possible actions are defined in taskMouseConfig_t. Can be used as singleshot method by using VB_SINGLESHOT as virtual button configuration.
Parameters
param Task configuration
See also
VB_SINGLESHOT
taskMouseConfig_t
Definition at line 79 of file task_mouse.c.
Referenced by configSwitcherTask(), and doMouseParsing().
task_mouse_getAT()
esp_err_t task_mouse_getAT (char * output, void * cfg)
Reverse Parsing - get AT command for mouse VB.
This function parses the current configuration of a virtual button to an AT command used to print the configuration.
Parameters
output Output string, where the full AT command will be stored
cfg Pointer to current mouse configuration, used to parse.
Returns
ESP_OK if everything went fine, ESP_FAIL otherwise
Definition at line 265 of file task_mouse.c.
Referenced by printAllSlots().