FLipMouse/FABI ESP32 firmware: /home/beni/sync/Projects/FH/FLipMouse-esp32/main/function_tasks/task_smarthome.h File Reference
task_smarthome.h File Reference
CONTINOUS TASK - MQTT handling.
#include <freertos/FreeRTOS.h>
#include <freertos/event_groups.h>
#include <freertos/queue.h>
#include <freertos/task.h>
#include <esp_log.h>
#include "common.h"
#include <inttypes.h>
#include "hal_storage.h"
#include "lwip/sockets.h"
#include "lwip/dns.h"
#include "lwip/netdb.h"
#include "mqtt_client.h"
#include "esp_err.h"
#include "esp_wifi.h"
#include "esp_event_loop.h"
#include "esp_event_legacy.h"
#include "esp_http_client.h"
#include "nvs.h"
#include "nvs_flash.h"
Macros
#define TASK_MQTT_STACKSIZE 4096
Stack size for the MQTT task.
#define MQTT_DELIMITER ':'
Default mqtt delimter character.
Functions
esp_err_t taskMQTTDeInit (void)
Deinit the MQTT task and the wifi.
esp_err_t taskREST (char *URL)
Publish data via MQTT.
esp_err_t taskMQTTPublish (char *topic_payload)
Publish data via MQTT.
esp_err_t taskWifiInit (void)
Init Wifi.
Detailed Description
CONTINOUS TASK - MQTT handling.
This module is used for connecting the FLipMouse/FABI to a MQTT broker.
Warning
Please note, only one WiFi mode is possible: either this device operates in AP mode and serves the webGUI (see task_webgui.h) OR it operates in station mode, connects to a given Wifi and transmits data via MQTT (if enabled)
Note
Initialise this module only if a MQTT command is used in the configuration.
See also
task_webgui.h
Definition in file task_smarthome.h.
Macro Definition Documentation
MQTT_DELIMITER
#define MQTT_DELIMITER ':'
Default mqtt delimter character.
Note
This is the default character, if no other is set via "AT MS". It is used to split the "AT MQ" string into topic and payload.
Definition at line 70 of file task_smarthome.h.
TASK_MQTT_STACKSIZE
#define TASK_MQTT_STACKSIZE 4096
Stack size for the MQTT task.
Definition at line 65 of file task_smarthome.h.
Function Documentation
taskMQTTDeInit()
esp_err_t taskMQTTDeInit (void)
Deinit the MQTT task and the wifi.
This function deactives MQTT/WiFi in station mode. It is necessary if the webGUI should be switched on.
Returns
ESP_OK on success, ESP_FAIL otherwise
Deinit the MQTT task and the wifi.
This function deactives MQTT
Returns
ESP_OK on success, ESP_FAIL otherwise
Definition at line 313 of file task_smarthome.c.
Referenced by taskWifiDeInit().
taskMQTTPublish()
esp_err_t taskMQTTPublish (char * topic_payload)
Publish data via MQTT.
This function publishes the given data. The parameter topic_payload will be split into the topic name and the corresponding payload to publish. The splitting is done by the currently set MQTT delimiter character, which can be modified with "AT MS". MQTT_DELIMITER will be used if no other character is set.
See also
MQTT_DELIMITER
Parameters
topic_payload Topic name and payload to be published. E.g., "/topic1:ON". Delimiter can be changed via NVS key NVS_MQTT_DELIM.
Returns
ESP_OK on success, ESP_FAIL otherwise
Note
Wifi will be enabled here, if MQTT is not active.
Wifi credentials and broker information must be in NVS BEFORE calling this function.
See also
NVS_STATIONNAME
NVS_STATIONPW
NVS_MQTT_BROKER
This function publishes the given data. The parameter topic_payload will be split into the topic name and the corresponding payload to publish. The splitting is done by the currently set MQTT delimiter character, which can be modified with "AT MS". MQTT_DELIMITER will be used if no other character is set.
See also
MQTT_DELIMITER
Returns
ESP_OK on success, ESP_FAIL otherwise
Definition at line 366 of file task_smarthome.c.
Referenced by cmdMq(), and handler_vb().
taskREST()
esp_err_t taskREST (char * uri)
Publish data via MQTT.
This function publishes the given data. The parameter topic_payload will be split into the topic name and the corresponding payload to publish. The splitting is done by the currently set MQTT delimiter character, which can be modified with "AT MS". MQTT_DELIMITER will be used if no other character is set.
See also
MQTT_DELIMITER
Returns
ESP_OK on success, ESP_FAIL otherwise
Publish data via MQTT.
This function calls the given URL via http/s GET. If Wifi is not initialized, it will be started. On the first call, there might be a delay until wifi is connected.
Note
Wifi is activated here, if this was not done before. There might be a timeout or missed REST call if wifi is not active. Nevertheless, we will wait 5s for the Wifi to be active.
Returns
ESP_OK on success, ESP_FAIL otherwise
Definition at line 424 of file task_smarthome.c.
Referenced by cmdRe(), and handler_vb().
taskWifiInit()
esp_err_t taskWifiInit (void)
Init Wifi.
This init function initializes the wifi in station mode.
See also
NVS_STATIONNAME
NVS_STATIONPW
Note
Please activate only if necessary by any configuration.
Returns
ESP_OK on success, ESP_FAIL otherwise
Definition at line 227 of file task_smarthome.c.
Referenced by taskMQTTInit(), and taskREST().