FLipMouse/FABI ESP32 firmware: /home/beni/sync/Projects/FH/FLipMouse-esp32/main/function_tasks/task_webgui.c File Reference
task_webgui.c File Reference
CONTINOUS TASK - Web server & WebGUI handling.
#include "task_webgui.h"
Macros
#define LOG_TAG "web"
Logging tag for this module.
#define CONFIG_AP_AUTHMODE WIFI_AUTH_WPA2_PSK
Authentication mode for wifi hotspot.
#define CONFIG_AP_SSID_HIDDEN 0
Set AP visibility, 1 if it should be hidden.
#define CONFIG_AP_SSID "FLipMouse"
Name of the wifi hotspot.
#define CONFIG_AP_PASSWORD "foundation"
Hotspot default password.
#define CONFIG_AP_CHANNEL 0
Wifi channel to be used, 0 means automatic (right?)
#define CONFIG_AP_MAX_CONNECTIONS 4
Wifi max number of connection.
#define CONFIG_AP_BEACON_INTERVAL 100
Wifi beacon interval.
Functions
static int8_t getNumberOfWifiStations (void)
Get the number of currently connected Wifi stations.
void wifiStartStopOffTimer (int onoff)
Simply reset & start OR stop the auto-off timer.
void ws_server (void *pvParameters)
CONTINOUS TASK - Websocket server task.
void fat_serve (char *resource, struct netconn *conn)
Serve static content from FAT.
static void http_server_netconn_serve (struct netconn *conn)
Handle an incoming HTTP connection.
static void http_server (void *pvParameters)
CONTINOUS TASK - Main webserver task.
static esp_err_t wifi_event_handler (void *ctx, system_event_t *event)
Event handler for wifi status updates.
esp_err_t taskWebGUIEnDisable (int onoff)
En- or Disable WiFi interface.
void wifi_timer_cb (TimerHandle_t xTimer)
Timer callback for disabling wifi.
esp_err_t taskWebGUIInit (void)
Init the web / DNS server and the web gui.
Variables
static const char * base_path = "/spiflash"
Partition name (used to define different memory types)
static char wifipw [64]
Currently used wifi password.
static const char http_html_hdr [] = "HTTP/1.1 200 OK\nContent-type: text/html\n\n"
Static HTTP HTML header.
static const char http_404_hdr [] = "HTTP/1.1 404 NOT FOUND\n\n"
Static HTTP 404 header.
TimerHandle_t wifiTimer
Timer handle for auto-disabling wifi.
Detailed Description
CONTINOUS TASK - Web server & WebGUI handling.
This module is used to serve the web- & DNS server for captive portal mode and the web configuration GUI.
In addition, AT commands are sent to the command parser, the same way as if they would be sent by any host configuration software. In this mode feedback (which is usually sent to the serial interface) is sent back to the webgui for parsing in JS.
See also
hal_serial
task_commands
atcmd_api
Todo:
Add wifi settings to cfg struct in hal_storage/common; default fallback should be defined
After implementing, test everything....
Definition in file task_webgui.c.
Macro Definition Documentation
CONFIG_AP_AUTHMODE
#define CONFIG_AP_AUTHMODE WIFI_AUTH_WPA2_PSK
Authentication mode for wifi hotspot.
Definition at line 47 of file task_webgui.c.
Referenced by taskWebGUIInit().
CONFIG_AP_BEACON_INTERVAL
#define CONFIG_AP_BEACON_INTERVAL 100
Wifi beacon interval.
Definition at line 59 of file task_webgui.c.
Referenced by taskWebGUIInit().
CONFIG_AP_CHANNEL
#define CONFIG_AP_CHANNEL 0
Wifi channel to be used, 0 means automatic (right?)
Definition at line 55 of file task_webgui.c.
CONFIG_AP_MAX_CONNECTIONS
#define CONFIG_AP_MAX_CONNECTIONS 4
Wifi max number of connection.
Definition at line 57 of file task_webgui.c.
Referenced by taskWebGUIInit().
CONFIG_AP_PASSWORD
#define CONFIG_AP_PASSWORD "foundation"
Hotspot default password.
Definition at line 53 of file task_webgui.c.
Referenced by taskWebGUIInit().
CONFIG_AP_SSID
#define CONFIG_AP_SSID "FLipMouse"
Name of the wifi hotspot.
Definition at line 51 of file task_webgui.c.
Referenced by taskWebGUIInit().
CONFIG_AP_SSID_HIDDEN
#define CONFIG_AP_SSID_HIDDEN 0
Set AP visibility, 1 if it should be hidden.
Definition at line 49 of file task_webgui.c.
Referenced by taskWebGUIInit().
LOG_TAG
#define LOG_TAG "web"
Logging tag for this module.
Definition at line 44 of file task_webgui.c.
Referenced by fat_serve(), http_server(), taskWebGUIEnDisable(), taskWebGUIInit(), wifi_event_handler(), wifi_timer_cb(), wifiStartStopOffTimer(), and ws_server().
Function Documentation
fat_serve()
void fat_serve (char * resource, struct netconn * conn)
Serve static content from FAT.
This method is used to send data from the FAT partition to a client
Parameters
resource Name of the resource to be sent
conn Currently active connection
Definition at line 166 of file task_webgui.c.
Referenced by http_server_netconn_serve().
getNumberOfWifiStations()
static int8_t getNumberOfWifiStations (void) static
Get the number of currently connected Wifi stations.
Returns
Number of connected clients
Definition at line 76 of file task_webgui.c.
Referenced by wifi_event_handler().
http_server()
static void http_server (void * pvParameters) static
CONTINOUS TASK - Main webserver task.
This task is used to handle incoming connections via netconn_accept. Each time a connection is opened, it will be served by http_server_netconn_serve.
See also
http_server_netconn_serve
Parameters
pvParameters Unused.
Definition at line 261 of file task_webgui.c.
Referenced by taskWebGUIInit().
http_server_netconn_serve()
static void http_server_netconn_serve (struct netconn * conn) static
Handle an incoming HTTP connection.
This handler is used to server the webpage to a connected client. Data is read from the FAT/VFS partition of the flash. The partition is created and uploaded by make makefatfs flashfatfs
Parameters
conn Current active net connection
Definition at line 213 of file task_webgui.c.
Referenced by http_server().
taskWebGUIEnDisable()
esp_err_t taskWebGUIEnDisable (int onoff)
En- or Disable WiFi interface.
This method is used to enable or disable the wifi interface. In order to provide a safe FLipMouse/FABI device, the Wifi hotspot is for configuration purposes only. Therefore, an enabled Wifi hotspot will be automatically disabled within a defined time (see WIFI_OFF_TIME) after the last client was disconnected. In addition, other parts of the software might disable the Wifi prior to the automatic disconnect.
Note
Calling this method prior to initializing wifi with taskWebGUIInit will result in an error!
Returns
ESP_OK on success, ESP_FAIL otherwise
Parameters
onoff If != 0, switch on WiFi, switch off if 0.
See also
WIFI_OFF_TIME
Definition at line 377 of file task_webgui.c.
Referenced by app_main(), switch_radio(), and wifi_timer_cb().
taskWebGUIInit()
esp_err_t taskWebGUIInit (void)
Init the web / DNS server and the web gui.
This init function initializes the wifi, web server, dns server (captive portal) and the websocket.
The web page is served from FAT file system (same partition as config files) via the http_server task. Communication between web page and FLipMouse/FABI is done by a websocket, which is provided via the ws_server task.
Todo:
Activate/fix/test captive portal
Note
Wifi is not enabled by default (BLE has priority), see taskWebGUIEnDisable
IP Adress of the device is 192.168.10.1
See also
taskWebGUIEnDisable
CONFIG_AP_PASSWORD
NVS_WIFIPW
Returns
ESP_OK on success, ESP_FAIL otherwise
Definition at line 461 of file task_webgui.c.
Referenced by app_main().
wifi_event_handler()
static esp_err_t wifi_event_handler (void * ctx, system_event_t * event) static
Event handler for wifi status updates.
This handler is used to update flags for connected clients & active wifi. In addition, if a client is connected, an additional serial stream is added to halSerial, which is used to transfer outgoing data to the websocket (in addition to the normal serial interface).
See also
connectionRoutingStatus
WIFI_ACTIVE
WIFI_CLIENT_CONNECTED
Returns
ESP_OK on success, ESP_FAIL otherwise
Parameters
ctx Unused
event Pointer to system event
Definition at line 303 of file task_webgui.c.
Referenced by taskWebGUIInit().
wifi_timer_cb()
void wifi_timer_cb (TimerHandle_t xTimer)
Timer callback for disabling wifi.
This callback is executed, if the time expires after the last client disconnects. It will disable wifi.
Parameters
xTimer Timer handle which was used for calling this CB
Definition at line 427 of file task_webgui.c.
Referenced by taskWebGUIInit().
wifiStartStopOffTimer()
void wifiStartStopOffTimer (int onoff)
Simply reset & start OR stop the auto-off timer.
See also
WIFI_OFF_TIME
Parameters
onoff If 0, timer will be stopped, started otherwise
Definition at line 94 of file task_webgui.c.
Referenced by wifi_event_handler().
ws_server()
void ws_server (void * pvParameters)
CONTINOUS TASK - Websocket server task.
This task is used to handle the websocket on port 1804. Websocket is used for data transmission between a connected client and the FLipMouse/FABI. Incoming data is in the same format as on the serial interface, therefore simply put into the command queue. Outgoing data is equally to serial output data.
See also
halSerialATCmds
halSerialSendUSBSerial
Definition at line 140 of file task_webgui.c.
Referenced by taskWebGUIInit().
Variable Documentation
base_path
const char* base_path = "/spiflash" static
Partition name (used to define different memory types)
Definition at line 62 of file task_webgui.c.
Referenced by fat_serve().
http_404_hdr
const char http_404_hdr[] = "HTTP/1.1 404 NOT FOUND\n\n" static
Static HTTP 404 header.
Definition at line 69 of file task_webgui.c.
Referenced by fat_serve().
http_html_hdr
const char http_html_hdr[] = "HTTP/1.1 200 OK\nContent-type: text/html\n\n" static
Static HTTP HTML header.
Definition at line 67 of file task_webgui.c.
Referenced by fat_serve().
wifipw
char wifipw[64] static
Currently used wifi password.
Definition at line 64 of file task_webgui.c.
Referenced by taskWebGUIInit().
wifiTimer
TimerHandle_t wifiTimer
Timer handle for auto-disabling wifi.
Definition at line 72 of file task_webgui.c.
Referenced by taskWebGUIInit(), and wifiStartStopOffTimer().