FLipMouse/FABI ESP32 firmware: /home/beni/sync/Projects/FH/FLipMouse-esp32/main/function_tasks/task_joystick.h File Reference
task_joystick.h File Reference
FUNCTIONAL TASK - joystick handling.
#include <freertos/FreeRTOS.h>
#include <freertos/event_groups.h>
#include <freertos/queue.h>
#include <esp_log.h>
#include "common.h"
#include "../config_switcher.h"
Data Structures
struct taskJoystickConfig
Macros
#define TASK_JOYSTICK_STACKSIZE 2048
Typedefs
typedef struct taskJoystickConfig taskJoystickConfig_t
Enumerations
enum joystick_action {
BUTTON_PRESS, BUTTON_RELEASE, XAXIS, YAXIS,
ZAXIS, ZROTATE, SLIDER_LEFT, SLIDER_RIGHT,
HAT
}
Functions
void task_joystick (taskJoystickConfig_t *param)
FUNCTIONAL TASK - Trigger joystick action.
esp_err_t joystick_update (int32_t value1, joystick_action axis1, int32_t value2, joystick_action axis2)
Update and send the joystick values.
esp_err_t task_joystick_getAT (char *output, void *cfg)
Reverse Parsing - get AT command for joystick VB.
Detailed Description
FUNCTIONAL TASK - joystick handling.
This module is used as functional task for joystick control.
It supports buttons (clicking, press&hold, release), axis (X/Y/Z), Z rotate and two sliders (left & right).
In addition, single shot is possible.
Note
Joystick control by mouthpiece is done in hal_adc!
See also
hal_adc
task_joystick
VB_SINGLESHOT
Definition in file task_joystick.h.
Macro Definition Documentation
TASK_JOYSTICK_STACKSIZE
#define TASK_JOYSTICK_STACKSIZE 2048
Definition at line 47 of file task_joystick.h.
Referenced by configSwitcherTask().
Typedef Documentation
taskJoystickConfig_t
typedef struct taskJoystickConfig taskJoystickConfig_t
Enumeration Type Documentation
joystick_action
enum joystick_action
type of joystick action which should be triggered by this task:
Enumerator
BUTTON_PRESS
BUTTON_RELEASE
XAXIS
YAXIS
ZAXIS
ZROTATE
SLIDER_LEFT
SLIDER_RIGHT
HAT
Definition at line 53 of file task_joystick.h.
Function Documentation
joystick_update()
esp_err_t joystick_update (int32_t value1, joystick_action axis1, int32_t value2, joystick_action axis2)
Update and send the joystick values.
This method is used to update the globale joystick state and send the updated values to USB/BLE (as configured). Usually this method is used for halAdc to send updates from a mouthpiece in joystick mode to the axis of the joystick.
Parameters
value1 New value for the axis1 parameter
axis1 Axis to map the parameter value1 to.
value2 New value for the axis2 parameter
axis2 Axis to map the parameter value2 to.
Returns
ESP_OK if updating & sending was fine. ESP_FAIL otherwise (params not valid, e.g. buttons are used, or sending failed)
Todo:
Update the global values here and send the joystick state
Definition at line 201 of file task_joystick.c.
task_joystick()
void task_joystick (taskJoystickConfig_t * param)
FUNCTIONAL TASK - Trigger joystick action.
This task is used to trigger a joystick action, possible actions are defined in taskJoystickConfig_t. Can be used as singleshot method by using VB_SINGLESHOT as virtual button configuration.
Parameters
param Task configuration
See also
VB_SINGLESHOT
taskJoystickConfig_t
Definition at line 53 of file task_joystick.c.
Referenced by configSwitcherTask(), and doJoystickParsing().
task_joystick_getAT()
esp_err_t task_joystick_getAT (char * output, void * cfg)
Reverse Parsing - get AT command for joystick VB.
This function parses the current configuration of a virtual button to an AT command used to print the configuration.
Parameters
output Output string, where the full AT command will be stored
cfg Pointer to current joystick configuration, used to parse.
Returns
ESP_OK if everything went fine, ESP_FAIL otherwise
Definition at line 216 of file task_joystick.c.
Referenced by printAllSlots().