FLipMouse/FABI ESP32 firmware: /home/beni/sync/Projects/FH/FLipMouse-esp32/main/function_tasks/task_hid.h File Reference
task_hid.h File Reference
CONTINOUS TASK - HID handling.
#include <freertos/FreeRTOS.h>
#include <freertos/event_groups.h>
#include <freertos/queue.h>
#include <esp_log.h>
#include "common.h"
#include "../config_switcher.h"
Macros
#define TASK_HID_STACKSIZE 2048
Functions
esp_err_t task_hid_enterCritical (void)
Enter critical section for modifying/reading the command chain.
void task_hid_exitCritical (void)
Exit critical section for modifying/reading the command chain.
hid_cmd_t * task_hid_getCmdChain (void)
Get current root of HID command chain.
esp_err_t task_hid_setCmdChain (hid_cmd_t *chain)
Set current root of HID command chain.
void task_hid (void *param)
CONTINOUS TASK - Trigger HID actions.
esp_err_t task_hid_addCmd (hid_cmd_t *newCmd, uint8_t replace)
Add a new HID command for a virtual button.
esp_err_t task_hid_clearCmds (void)
Clear all stored HID commands.
esp_err_t task_hid_getAT (char *output, uint8_t vb)
Reverse Parsing - get AT command for HID VB.
Detailed Description
CONTINOUS TASK - HID handling.
This module is used as continous task for all HID handling based on virtual buttons, containing:
Mouse clicking, holding, pressing & release as well as movement (X/Y/Z)
Keyboard press,hold,release & write
Joystick press,hold,release & axis movement
Note
Mouse/keyboard/joystick control by mouthpiece is done in hal_adc!
See also
hal_adc
Definition in file task_hid.h.
Macro Definition Documentation
TASK_HID_STACKSIZE
#define TASK_HID_STACKSIZE 2048
Definition at line 45 of file task_hid.h.
Referenced by app_main().
Function Documentation
task_hid()
void task_hid (void * param)
CONTINOUS TASK - Trigger HID actions.
This task is used to trigger all active HID commands, which are assigned to virtual buttons.
Parameters
param Unused
Definition at line 69 of file task_hid.c.
Referenced by app_main().
task_hid_addCmd()
esp_err_t task_hid_addCmd (hid_cmd_t * newCmd, uint8_t replace)
Add a new HID command for a virtual button.
This method adds the given HID command to the list of HID commands which will be processed if the corresponding VB is triggered.
Note
Highest bit determines press/release action. If set, it is a press!
If VB number is set to VB_SINGLESHOT, the command will be sent immediately.
We will malloc for each command here. To free the memory, call task_hid_clearCmds .
Parameters
newCmd New command to be added or triggered if vb is VB_SINGLESHOT
replace If set to != 0, any previously assigned command is removed from list.
Returns
ESP_OK if added, ESP_FAIL if not added (out of memory)
Definition at line 166 of file task_hid.c.
Referenced by doJoystickParsing(), doKeyboardParsing(), and doMouseParsing().
task_hid_clearCmds()
esp_err_t task_hid_clearCmds (void)
Clear all stored HID commands.
This method clears all stored HID commands and frees the allocated memory.
Returns
ESP_OK if commands are cleared, ESP_FAIL otherwise
Definition at line 387 of file task_hid.c.
Referenced by task_hid_setCmdChain().
task_hid_enterCritical()
esp_err_t task_hid_enterCritical (void)
Enter critical section for modifying/reading the command chain.
Warning
task_hid_exit_critical MUST be called, otherwise HID commands are blocked.
Returns
ESP_OK if it is safe to proceed, ESP_FAIL otherwise (lock was not free in 10 ticks)
Definition at line 301 of file task_hid.c.
Referenced by task_hid_setCmdChain().
task_hid_exitCritical()
void task_hid_exitCritical (void)
Exit critical section for modifying/reading the command chain.
See also
task_hid_enterCritical
Definition at line 319 of file task_hid.c.
Referenced by task_hid_setCmdChain().
task_hid_getAT()
esp_err_t task_hid_getAT (char * output, uint8_t vb)
Reverse Parsing - get AT command for HID VB.
This function parses the current configuration of a virtual button to an AT command used to print the configuration.
Parameters
output Output string, where the full AT command will be stored
vb Number of virtual button for getting the AT command
Returns
ESP_OK if everything went fine, ESP_FAIL otherwise
Definition at line 449 of file task_hid.c.
Referenced by storeSlot().
task_hid_getCmdChain()
hid_cmd_t* task_hid_getCmdChain (void)
Get current root of HID command chain.
Note
Please call task_hid_enterCritical before reading from cmd chain.
Returns
Pointer to root of HID chain
Definition at line 329 of file task_hid.c.
task_hid_setCmdChain()
esp_err_t task_hid_setCmdChain (hid_cmd_t * chain)
Set current root of HID command chain.
Note
Please do NOT call task_hid_enterCritical before setting the new chain!
Warning
By using this function, previously used HID commands are cleared!
Parameters
chain Pointer to root of HID chain
Returns
ESP_OK if chain is saved, ESP_FAIL otherwise (lock was not free, deleting old chain failed..)
Definition at line 340 of file task_hid.c.