FLipMouse/FABI ESP32 firmware: /home/beni/sync/Projects/FH/FLipMouse-esp32/main/function_tasks/task_mouse.h File Reference
task_mouse.h File Reference
#include <freertos/FreeRTOS.h>
#include <freertos/event_groups.h>
#include <freertos/queue.h>
#include <esp_log.h>
#include "common.h"
Data Structures
struct taskMouseConfig
Macros
#define TIMEOUT 10
#define TASK_MOUSE_STACKSIZE 2048
#define MOUSE_BUTTON_LEFT (1<<0)
#define MOUSE_BUTTON_RIGHT (1<<1)
#define MOUSE_BUTTON_MIDDLE (1<<2)
#define MOUSE_DEFAULT_WHEELSTEPS 4
Typedefs
typedef struct taskMouseConfig taskMouseConfig_t
Enumerations
enum mouse_action {
RIGHT, LEFT, MIDDLE, WHEEL,
X, Y
}
enum mouse_action_param {
M_CLICK, M_HOLD, M_RELEASE, M_DOUBLE,
M_UNUSED
}
Functions
uint8_t mouse_set_wheel (uint8_t steps)
Set current mouse wheel step size.
uint8_t mouse_get_wheel (void)
Get the current mouse wheel step size.
void task_mouse (taskMouseConfig_t *param)
FUNCTIONAL TASK - Trigger mouse action.
Macro Definition Documentation
MOUSE_BUTTON_LEFT
#define MOUSE_BUTTON_LEFT (1<<0)
Definition at line 42 of file task_mouse.h.
Referenced by task_mouse().
MOUSE_BUTTON_MIDDLE
#define MOUSE_BUTTON_MIDDLE (1<<2)
Definition at line 44 of file task_mouse.h.
Referenced by task_mouse().
MOUSE_BUTTON_RIGHT
#define MOUSE_BUTTON_RIGHT (1<<1)
Definition at line 43 of file task_mouse.h.
Referenced by task_mouse().
MOUSE_DEFAULT_WHEELSTEPS
#define MOUSE_DEFAULT_WHEELSTEPS 4
Definition at line 45 of file task_mouse.h.
TASK_MOUSE_STACKSIZE
#define TASK_MOUSE_STACKSIZE 2048
Definition at line 40 of file task_mouse.h.
Referenced by configSwitcherTask().
TIMEOUT
#define TIMEOUT 10
Definition at line 39 of file task_mouse.h.
Typedef Documentation
taskMouseConfig_t
typedef struct taskMouseConfig taskMouseConfig_t
Enumeration Type Documentation
mouse_action
enum mouse_action
type of mouse action which should be triggered by this task:
Enumerator
RIGHT
LEFT
MIDDLE
WHEEL
X
Y
Definition at line 52 of file task_mouse.h.
mouse_action_param
enum mouse_action_param
Enumerator
M_CLICK
M_HOLD
M_RELEASE
M_DOUBLE
M_UNUSED
Definition at line 61 of file task_mouse.h.
Function Documentation
mouse_get_wheel()
uint8_t mouse_get_wheel (void)
Get the current mouse wheel step size.
Returns
Current step size
Definition at line 63 of file task_mouse.c.
Referenced by doMouseParsing().
mouse_set_wheel()
uint8_t mouse_set_wheel (uint8_t steps)
Set current mouse wheel step size.
return 0 on success, 1 otherwise
This method is used to set the current step size for the mouse wheel
Parameters
steps Amount of wheel steps, range: 0-126
Returns
0 if everything was fine, 1 if stepsize is out of range
Definition at line 48 of file task_mouse.c.
Referenced by doMouseParsing().
task_mouse()
void task_mouse (taskMouseConfig_t * param)
FUNCTIONAL TASK - Trigger mouse action.
This task is used to trigger a mouse action, possible actions are defined in taskMouseConfig_t. Can be used as singleshot method by using VB_SINGLESHOT as virtual button configuration.
Parameters
param Task configuration
See also
VB_SINGLESHOT
taskMouseConfig_t
Definition at line 76 of file task_mouse.c.
Referenced by configSwitcherTask().