FLipMouse/FABI ESP32 firmware: /home/beni/sync/Projects/FH/FLipMouse-esp32/main/function_tasks/task_kbd.c File Reference
task_kbd.c File Reference
FUNCTIONAL TASK - trigger keyboard actions.
#include "task_kbd.h"
Macros
#define LOG_TAG "task_kbd"
Logging tag for this module.
Functions
esp_err_t task_keyboard_getAT (char *output, void *cfg)
Reverse Parsing - get AT command for keyboard VB.
void sendKbd (QueueHandle_t qUSB, QueueHandle_t qBLE, uint16_t *key)
Helper function sending to queues depending on connection type.
void task_keyboard (taskKeyboardConfig_t *param)
FUNCTIONAL TASK - trigger keyboard actions.
Detailed Description
FUNCTIONAL TASK - trigger keyboard actions.
This file contains the task implementation for keyboard key triggering. This task is started by the configuration task and it is assigned to one virtual button or triggered as single shot. As soon as this button is triggered, the configured keys are sent to either USB, BLE or both. This task can be deleted all the time to change the configuration of one button.
Keycode configuration is set via taskKeyboardConfig_t.
Warning
Parsing of key identifiers and text is NOT done here. Due to performance reasons, parsing is done prior to initialising/calling this task.
See also
taskKeyboardConfig_t
VB_SINGLESHOT
Definition in file task_kbd.c.
Macro Definition Documentation
LOG_TAG
#define LOG_TAG "task_kbd"
Logging tag for this module.
Definition at line 44 of file task_kbd.c.
Referenced by task_keyboard(), and task_keyboard_getAT().
Function Documentation
sendKbd()
void sendKbd (QueueHandle_t qUSB, QueueHandle_t qBLE, uint16_t * key)
Helper function sending to queues depending on connection type.
This method is used to send data to USB/BLE queues, depending on the bits of connectionRoutingStatus. Either BLE or USB or both can be enabled.
See also
DATATO_USB
DATATO_BLE
Parameters
qUSB Queue for USB commands to send to
qBLE Queue for BLE commands to send to
key Pointer to keycode which is sent to these queues
Definition at line 144 of file task_kbd.c.
Referenced by task_keyboard().
task_keyboard()
void task_keyboard (taskKeyboardConfig_t * param)
FUNCTIONAL TASK - trigger keyboard actions.
This task is used to trigger keyboard actions, as it is defined in taskKeyboardConfig_t. Can be used as singleshot method by using VB_SINGLESHOT as virtual button configuration.
See also
VB_SINGLESHOT
taskKeyboardConfig_t
Parameters
param Task configuration
Definition at line 164 of file task_kbd.c.
Referenced by configSwitcherTask(), and doKeyboardParsing().
task_keyboard_getAT()
esp_err_t task_keyboard_getAT (char * output, void * cfg)
Reverse Parsing - get AT command for keyboard VB.
This function parses the current configuration of a virtual button to an AT command used to print the configuration.
Parameters
output Output string, where the full AT command will be stored
cfg Pointer to current keyboard configuration, used to parse.
Returns
ESP_OK if everything went fine, ESP_FAIL otherwise
Definition at line 55 of file task_kbd.c.
Referenced by printAllSlots().